### ISSUE TITLE
Building Docker Images using bin/dbuild crashes

### ISSUE THREAD

**Issue by edwinclement08** [codebar/planner#1000]
## Description of the issue 📄
While running bin/dbuild for creating the docker images.
apt-get-update fails with

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.

## Screenshots 📷
![image](https://user-images.githubusercontent.com/9532892/60353478-b8e4ac80-99e7-11e9-9d41-22070110cc63.png)
![image](https://user-images.githubusercontent.com/9532892/60353535-d87bd500-99e7-11e9-8749-f90ea741ed0d.png)

## Steps to fix 🛠
Possible fix:
https://superuser.com/questions/1423486/issue-with-fetching-http-deb-debian-org-debian-dists-jessie-updates-inrelease
## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
Hi edwinclement08

Are you still seeing this?

The link you put in suggests it's a temporary mistake with the image.

I don't use Docker much (lack of ram) but I've run `bin/dbuild` without error today.

**Comment by notapatch** [comment]
We use debian, and in docker builds only, through this single line of code:

```
# Dockerfile
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
```

[We can see the line has been put in as recommended in the README.md
](https://github.com/nodesource/distributions)
```
Node.js v8.x:

# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_8.x | bash -
apt-get install -y nodejs
```

When Debian change something and they get it wrong you'll get a Debian error. However, there's nothing that codebar can do about it. [We could look at moving to a more current release but that's covered by another issue. ](https://github.com/codebar/planner/issues/1145).

These problems resolve themselves (by upstream developers fixing them) and you can probably work around it by choosing a different version to install temporarily - planner isn't picky.

**Comment by notapatch** [comment]
@despo this issue is a Debian issue and should be closed
