### ISSUE TITLE
Selenium::WebDriver::Error::SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 75

### ISSUE THREAD

**Issue by docljn** [codebar/planner#1012]
## Description of the issue 📄
On running `bin/drake` a single test fails with the following error message:
```
Failures:

  1) managing workshop attendances an admin can rsvp an invited student to the workshop
     Failure/Error: visit admin_workshop_path(workshop)
     
     Selenium::WebDriver::Error::SessionNotCreatedError:
       session not created: This version of ChromeDriver only supports Chrome version 75
     # #0 0x560055a387a9 <unknown>
```
I am running `Chrome Version 75.0.3770.142 (Official Build) (64-bit)` on MacOS Sierra 10.12.6 (16G2016)

This occurs each time I run the tests, irrespective of seed.

## Screenshots 📷
<img width="916" alt="Screen Shot 2019-07-20 at 17 52 17" src="https://user-images.githubusercontent.com/28825519/61581521-4020ce00-ab17-11e9-9de6-0a94aaee66f6.png">

## Steps to fix 🛠
?

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
Hello @docljn

I would like to try this. I have reproduced the error and have a commit that fixes it for my system and which passes the Travis CI.

**Comment by notapatch** [comment]
@matyikriszta  The pull request https://github.com/codebar/planner/pull/1149 closes this as well. It's the same error but from an earlier chrome version/release cycle.

**Comment by matyikriszta** [comment]
@notapatch cool, I'll close the issue.
