### ISSUE TITLE
Sidemenu is not sticky

### ISSUE THREAD

**Issue by mishabruml** [codebar/planner#1021]
## Description of the issue 📄
Sidemenu does not travel with scroll.
Opening the sidemenu when scrolled far down the page will open an apparently 'blank' menu- the menu items are at the top

IMO the sidemenu content should travel down the page with the user as they scroll, and this behaviour should be persisted through open/close menu events

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by GarySiu** [comment]
This looks interesting, however the offcanvas implementation of the version of Foundation codebar currently uses doesn't play nicely with position: sticky. Briefly, position: sticky doesn't work if any of the containing elements has overflow hidden set and a dynamically calculated height. The current implementation uses this to crop the edge page when it slides to the right to prevent a horizontal scrollbar from showing.

It's possible to hack around this by shrinking the width of the page by the size of the side menu but this changes the appearance slightly so it no longer looks as if the menu is being revealed "off canvas". I can create a PR demonstrating this.

Alternatively we could consider updating to a version of Foundation after this version: https://github.com/zurb/foundation-sites/pull/9357

Supposedly it is reworked with position: sticky support in mind.

**Comment by mishabruml** [comment]
Sounds like a bad scenario. 

To be clear, you agree with the concept, it’s just the tech/framework/tools that is the barrier?

My vote would be to upgrade the framework so that sticky is supported natively, that would be the least damaging in the long run but I appreciate there may be a lot of issues elsewhere in the codebase caused by an upgrade.

**Comment by GarySiu** [comment]
> To be clear, you agree with the concept, it’s just the tech/framework/tools that is the barrier?

Yup. It would definitely be a UX win. Here is a video of the hacky implementation in action:
![video showing sticky nav](https://media.giphy.com/media/PiWtz6WKPHjOzmDwNA/giphy.gif)

> My vote would be to upgrade the framework so that sticky is supported natively, that would be the least damaging in the long run but I appreciate there may be a lot of issues elsewhere in the codebase caused by an upgrade.

This is my first contribution so I wanted to keep it limited and respect the wishes of those who maintain the codebase and those who have already contributed work on the project.  I've submitted the PR and we'll see whether it's considered an acceptable tradeoff.

**Comment by mishabruml** [comment]
> Here is a video of the hacky implementation in action:

That's awesome man! Good work

> This is my first contribution so I wanted to keep it limited and respect the wishes of those who maintain the codebase and those who have already contributed work on the project. I've submitted the PR and we'll see whether it's considered an acceptable tradeoff.

Fully appreciate that, sorry I didn't realise- I thought you were an owner. Let's see what they say!

**Comment by matyikriszta** [comment]
This is going to be resolved by @KimberleyCook's Bootstrap migration work. Going to remove the stale label for now and close it manually when that piece of work goes live.
