### ISSUE TITLE
Travis Errors: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by notapatch** [codebar/planner#1023]
## Description of the issue 📄

[A pull request I was working on](https://github.com/codebar/planner/pull/1022) generated the following error.[ I am also seeing the same error in the last two builds](https://travis-ci.org/codebar/planner/builds)

> could not connect to server: Connection refused
>   Is the server running on host "localhost" (127.0.0.1) and accepting
>   TCP/IP connections on port 5432?
> /home/travis/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
> ...
> ... more stacktrace from postgresql

## Steps to fix 🛠

I have no idea why it has started now - that's never a good start is it? Maybe someone knows better? Otherwise, given that it is a postgresql stack trace and you have a PG gem but nothing explicit in the `.travis.yml`. I wanted to put a pull request that added postgresql as a service. I would also want to force a couple of builds to see if this was an intermittent problem or not but I thought I should mention this first as you might, quite reasonably, question what was going on.

```
# .travis.yml
... 
services:
  - postgresql
... 

```

### Reference
[psql: could not connect to server error on “travis-ci”](https://stackoverflow.com/questions/49850020/psql-could-not-connect-to-server-error-on-travis-ci)

# EDIT:

I now understand.
[Travis have been moving builds up from Travis from Trusty to Xenial](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment). 

[If you look at the last successful build, 13 days ago, it was on Trusty. After that it was on Xenial and the builds start to fail ](https://travis-ci.org/codebar/planner/builds)- even when you fix the postgres addon issue the tests are flaky. We can set it back to Trusty and work on the Xenial issues?
```

# .travis.yml
...
dist: trusty
...

```

**Comment by matyikriszta** [comment]
@notapatch thanks for opening the PR to fix this, as it has now been merged in I'll close this issue.
