### ISSUE TITLE
Admin workshop list does not contain year for event date

### ISSUE THREAD

**Issue by biggianteye** [codebar/planner#1041]
## Description of the issue 📄

The admin workshop list page (Chapter -> View all workshops) shows the date of the event but this date does not show the year. This makes the list confusing if the chapter has been around for more than a year.

## Screenshots 📷

![image](https://user-images.githubusercontent.com/1482649/64924708-42359f00-d7df-11e9-8e80-2ba03794ba9f.png)

## Steps to fix 🛠

Add the year.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [x] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
YES!! I've been meaning to add this issue for a while. Thank you.

**Comment by matyikriszta** [comment]
@biggianteye I've opened a PR for this here if you want to take a look: https://github.com/codebar/planner/pull/1075

**Comment by matyikriszta** [comment]
@biggianteye after I deployed this I realized another way to make this page more informative would be to group and label workshops based on year. Which one would be your preferred solution?

**Comment by biggianteye** [comment]
I'm going to try out the PR this evening so I'll let you know if I have any thoughts.

I've only played with the planner once and was able to sign into my local instance as a regular user. How do I elevate the account to be an admin/organiser so that I can see the admin pages?
