### ISSUE TITLE
chromedriver-helper gem deprecated

### ISSUE THREAD

**Issue by biggianteye** [codebar/planner#1061]
## Description of the issue 📄

When running `bin/dbuild`, the following warning message appears:

```
Post-install message from chromedriver-helper:

  +--------------------------------------------------------------------+
  |                                                                    |
  |  NOTICE: chromedriver-helper is deprecated after 2019-03-31.       |
  |                                                                    |
  |  Please update to use the 'webdrivers' gem instead.                |
  |  See https://github.com/flavorjones/chromedriver-helper/issues/83  |
  |                                                                    |
  +--------------------------------------------------------------------+
```

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@biggianteye there's already an open PR for this here: https://github.com/codebar/planner/pull/1038, if you could take a look and let me know if it looks good for you I'm happy to approve it.

**Comment by notapatch** [comment]
Yeah, so the PR will change the developer's system - which I can't test for. While it's _probably_ going to be just fine - it would be nice for someone else to grab the PR (as detailed in the commit) and see everything is OK with them. Most projects have switched months ago and the new system will keep chromedriver up to date (previously it updated whenever the developer asked for it to update ... which let's be honest was whenever it broke the build).

**Comment by biggianteye** [comment]
> @biggianteye there's already an open PR for this here: #1038, if you could take a look and let me know if it looks good for you I'm happy to approve it.

I've tested the PR with docker and it builds and tests fine for me. I haven't tried it on my local system though as I prefer to keep things contained within docker.

**Comment by notapatch** [comment]
Hey @biggianteye 

The fix for this has just been merged. If you get the latest code you can confirm this and close this.  Or if you're real busy, trust us  :shipit:

**Comment by biggianteye** [comment]
That's fine. It wasn't causing a problem for me. I just wanted to remove a warning that might alarm a newcomer to the project.

**Comment by notapatch** [comment]
Thoughtful 👍
