### ISSUE TITLE
Hacktoberfest / Pull requests for beginners

### ISSUE THREAD

**Issue by notapatch** [codebar/planner#1067]
### Pull requests for beginners 📄

Would you be interested in a few easy issues which you could tag as Beginner / Hacktoberfest as you wish? Any left over at the end of Octoberfest I would submit pull requests for and tidy things up?

### Edited:
Removed Codebar workshop request

**Comment by matyikriszta** [comment]
@notapatch noted, thanks for letting us know. As with everything it might take us a while to get to them but we'll do our best.
