### ISSUE TITLE
Coverage decreasing by 0.2%

### ISSUE THREAD

**Issue by notapatch** [codebar/planner#1068]
## Description of the issue 📄

I'm seeing odd results for coverage. [I'm not alone in seeing the `-0.2% coverage` fail ](https://github.com/codebar/planner/pull/1060)when all I've done is replace [one method name with another ](https://github.com/codebar/planner/pull/1063) or[ remove a line of the schema which, if anything, would increase coverage](https://github.com/codebar/planner/pull/1050) - so far about half the time I'm seeing it in the last ten days.

Coverage allows you to change a setting - [I've seen 0.5%](https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-120924694) but I'm happy with above 0.2% for now and see where it goes.

## Screenshots 📷
![Screenshot 2019-09-30 at 15 43 55](https://user-images.githubusercontent.com/1710795/65890191-64601d00-e39a-11e9-8fc2-5bb42764264c.png)
## To do 📋

[If you agree the codbar settings link is probably about this...](https://coveralls.io/github/codebar/planner/settings)

**Comment by matyikriszta** [comment]
@despo is this something you could amend for us as I don't have access to the Settings page of coveralls.

**Comment by notapatch** [comment]
Thank you @despo  and @matyikriszta  - it's working.
