### ISSUE TITLE
Codebar does not display a page title in browser tab or the history

### ISSUE THREAD

**Issue by notapatch** [codebar/planner#1077]
## Description of the issue 📄

When on the codebar site you will notice the browser tab never shows anything except the site name "codebar.io". If you navigate through the site you would expect the history to build up as a list of page title and site pairings.  Instead you just see a list of sites "codebars"

### Example of CodeBar

![Screenshot 2019-10-03 at 22 21 11](https://user-images.githubusercontent.com/1710795/66165447-a607f680-e62c-11e9-91e8-e5ed12906e33.png)

### Example of Guardian

![Screenshot 2019-10-03 at 22 27 58](https://user-images.githubusercontent.com/1710795/66165660-2595c580-e62d-11e9-8342-83a4fa58fe0a.png)

### Example of BBC with page titles

![Screenshot 2019-10-03 at 22 20 33](https://user-images.githubusercontent.com/1710795/66165428-9be5f800-e62c-11e9-800e-b1944115a928.png)

## Steps to fix 🛠

1. Agree on any change (Nothing agreed yet!)
2. Implement a page title [for example](https://stackoverflow.com/questions/185965/rails-how-to-change-the-title-of-a-page)

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by Nada1996** [comment]
@notapatch can I work on this issue?

**Comment by notapatch** [comment]
Hi Nada,

I am always in favour of other people doing issues. :-)

I am only a contributor to the project. As you may know, the maintainers of the project are @KimberleyCook, @matyikriszta. So, I'm taking the 👍 from @KimberleyCook as a good omen.

I imagined when finished the history should look something like:

```
[Name of page title] |  [Name of application]
```
Example
```
Upcoming events | codebar.io
Workshop at Pennsylvania Avenue | codebar.io
```

If you have any questions just ask.  If you have any setup problems that's a bug and the readme should be updated.

### Further Reading

[rails-3-ideal-way-to-set-title-of-pages](https://stackoverflow.com/questions/3059704/rails-3-ideal-way-to-set-title-of-pages?noredirect=1&lq=1)

**Comment by matyikriszta** [comment]
@Nada1996 yes, please go ahead
