### ISSUE TITLE
Event waiting list functionality

### ISSUE THREAD

**Issue by ambrwlsn** [codebar/planner#1102]
## Description of the issue 📄

When codebar members sign up to a workshop, there is a waiting list functionality that helps organisers see who signed up to the waiting list and in what order.

This is not the case for events, where codebar members have to email codebar in order to get a waiting list spot.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
This issue has been duplicated here #1810
