### ISSUE TITLE
Missing canonical HTTP to HTTPS redirect

### ISSUE THREAD

**Issue by MMasey** [codebar/planner#1103]
## Description of the issue 📄
I noticed that there currently isn't a canonical redirect for the non-www codebar.io domain. 

For example, if you go to [http://www.codebar.io](http://www.codebar.io), it will remain on the http url and not redirect to the https one, which i'm guessing should be [https://codebar.io/](https://codebar.io/)

## Screenshots 📷
N/A

## Steps to fix 🛠
I imagine adding a canonical redirect to the non-www domain, along with a HTTP to HTTPS redirect would solve the issue.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Fixed.
