### ISSUE TITLE
Workshop length is missing

### ISSUE THREAD

**Issue by alextercete** [codebar/planner#1104]
## Description of the issue 📄
The workshop length is missing from the website and emails. A few attendees have asked about this in the last few months, so we should probably make this information more visible.

Pages that are missing the workshop length:

- https://codebar.io/events
- https://codebar.io/workshops/{workshop-id}
- https://codebar.io/{chapter-name}

Emails that are missing the workshop length:

- Workshop Coach Invitation
- Workshop Student Invitation
- Workshop Reminder

## Screenshots 📷

![image](https://user-images.githubusercontent.com/126538/66953052-a903dd80-f055-11e9-9ddb-ec52f87e754b.png)

![image](https://user-images.githubusercontent.com/126538/66953140-cf297d80-f055-11e9-9eeb-7545f39d23a9.png)

## Steps to fix 🛠

We don't necessarily need to add to all pages, the workshop page should be enough (Eventbrite and Meetup seem to do it like this).

I'd suggest something like this:

>**Workshop at Metaswitch**
>Wed, 30th October (in 14 days)
>🕔18:30 - 21:00

For emails, we should keep the subject with just the starting time and add the length to the body.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by jabawack81** [comment]
I can work on this

**Comment by matyikriszta** [comment]
@ jabawack81 please go ahead

**Comment by jabawack81** [comment]
At the moment the Workshops have only `date_and_time` and no end time, so I can see a couple of ways to fix this issue:

- add `duration` to the workshop and calculate the ending time.
- replicate the same approach is used for the events with an `ends_at`.

I imagine that an event can span on multiple days opposite to a Workshop, so having simply a `duration` could make sense for Workshops I would choose the second option for consistency and maybe auto-fill the `ends_at` field for the workshops at 2.5 hours from the beginning.

**Comment by matyikriszta** [comment]
@jabawack81 I agree, let's go with the second option for consistency

**Comment by jabawack81** [comment]
New PR https://github.com/codebar/planner/pull/1108
