### ISSUE TITLE
Make form button text consistent

### ISSUE THREAD

**Issue by notapatch** [codebar/planner#1119]
## Description of the issue 📄

Looking at "New" form buttons across the application:

```
URL                                                Text on Button
http://localhost:3000/admin/workshops/new           Save
http://localhost:3000/admin/meetings/new            update
http://localhost:3000/admin/announcements/new       create
http://localhost:3000/admin/sponsors/new            create sponsor
http://localhost:3000/admin/chapters/new            create chapter
http://localhost:3000/admin/events/new              save
```

I don't have an opinion on the text but I would expect it to be consistent. And that goes for the edit as well. I haven't looked at the code but the changes should be internationalizable - AKA English not added in line - the forms are cleaner and the text is kept in `en.yml` so we can see it's consistent with a sweep of the eye. 

### Bad
```
    .large-12.columns.text-right
      = f.submit 'Save', class: 'button'
                    ^=== bad
```

### Good
[Rails api - form builder - submit](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-submit)

## Steps to fix 🛠

1. Choose a consistent button text (Opinions welcome!)
2. Change them to it (The fun bit).
3. Confirm that it is not hard coded 

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by Charliefea** [comment]
Please can I pick this one up.

**Comment by notapatch** [comment]
Yes indeed @Charliefea. Nobody has claimed it.... so It's yours. If you have any problems just add a comment here.
