### ISSUE TITLE
Sponsor page incorrectly capitalises contact names

### ISSUE THREAD

**Issue by elderfd** [codebar/planner#1126]
## Description of the issue 📄
I added a contact to the sponsor for Wunderdog (https://codebar.io/admin/sponsors/777). The contact has a second name with two words, I entered the name with both parts properly capitalised. On the sponsor page however it shows the last name with the second word lacking capitalisation,

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
The easier bit is to confirm it. Basically the information has been saved as you typed it. Only when it's displayed it's capitalized:

```
  # app/presenters/sponsor_presenter.rb
  Class SponsorPresenter < BasePresenter
  ...
  def contact_full_name
    if model.contact_first_name && model.contact_surname    here ======\/
      "#{model.contact_first_name.capitalize} #{model.contact_surname.capitalize}"
    end
  end
```

#### What is the scope of the issue?

Here's an examples of the issue:

```
 "hello World".capitalize
=> "Hello world"
```

```
"McKenzie".capitalize
=> "Mckenzie"
```

```
"da Vinci".capitalize
=> "Da vinci"
```
Names are complicated. [if you come up with a rule you're probably wrong](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). 


#### What was entered?

For example, we need to know how often capitalization was added by the person entering the data?

What percentage `Barack Obama`  vs `barack obama` ?

So someone with database access is going to have to investigate the data and see what options they have. The good news is I can't find capitalize being used elsewhere eg. Members.
