### ISSUE TITLE
Failing test: session not created

### ISSUE THREAD

**Issue by jhsu802701** [codebar/planner#1144]
## Description of the issue 📄
When I run the test suite, one of the tests fails.  The screen output is:
```
Failures:

  1) managing workshop attendances an admin can rsvp an invited student to the workshop
     Failure/Error: visit admin_workshop_path(workshop)
     
     Selenium::WebDriver::Error::SessionNotCreatedError:
       session not created: This version of ChromeDriver only supports Chrome version 78
     # #0 0x55967636b7e9 <unknown>
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/bridge.rb:102:in `create_session'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/bridge.rb:56:in `handshake'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/chrome/driver.rb:43:in `initialize'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/common/driver.rb:46:in `new'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/common/driver.rb:46:in `for'
     # /usr/local/bundle/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver.rb:88:in `for'
     # /usr/local/bundle/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:49:in `browser'
     # /usr/local/bundle/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:68:in `visit'
     # /usr/local/bundle/gems/capybara-3.29.0/lib/capybara/session.rb:276:in `visit'
     # /usr/local/bundle/gems/capybara-3.29.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/admin/manage_workshop_attendances_spec.rb:47:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:80:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 15.9 seconds (files took 5.13 seconds to load)
485 examples, 1 failure

Failed examples:

rspec ./spec/features/admin/manage_workshop_attendances_spec.rb:42 # managing workshop attendances an admin can rsvp an invited student to the workshop
```

SIDE NOTE: Thank you for providing such clear instructions on how to run the test suite using the docker-compose command, an important part of the workflow that so many others neglect to explain.  So far, the way I've been using Docker is by running a shell inside a Docker container and doing the same things other people do in their host environments.  I will be using this project as a reference on how to properly Dockerize apps.

**Comment by notapatch** [comment]
Hello jhsu802701

Currently we use the deprecated chromedriver-helper - one of the issues with it was that it always downloaded the very latest drivers and they appeared ahead of the Chrome browser update. So depending where we are on the Chrome release cycle you can see this error.

[Version selection with LATEST_RELEASE is deprecated](https://github.com/flavorjones/chromedriver-helper/issues/79)
[Use a compatible version of chromedrive](https://github.com/flavorjones/chromedriver-helper/issues/78)

I don't use Docker much (too slow on my machine) but I have seen the same problem when I was testing Planner with Circle CI. I fixed it by using [the webdrivers pull request.](https://github.com/codebar/planner/pull/1038)



[If you tried it and it worked for you then you can add comment here and it might encourage it getting merged](https://github.com/codebar/planner/issues/1061). The main hang up is I haven't found another native user to test the commit on - so 🤔  it's balancing possible complaints of native users upgrading vs complaints for using what is now a deprecated library.

**Comment by jhsu802701** [comment]
notapatch: Please update that branch.

**Comment by notapatch** [comment]
Do you mean merge the branch into master? I do not have any permissions. People with permissions, maintainers, review things in their free time during the week (KimberleyCook, matyikriszta).

Weekend options available 🏖

1. Update your local drive, rebuild your system, and see everything works. You can then give feedback which helps the maintainers decide what to do. If that sounds interesting:

```
  git fetch upstream pull/1038/head:webdrivers
  git checkout webdrivers
  bin/dbuild 
   # run the tests
```

2. You can also decide to ignore the issue - there is only one test that uses Javascript and you know why it's failing (Chrome and driver incompatibility) - this does not stop the system working - Chrome is only only on the build for that one test.

**Comment by jhsu802701** [comment]
Your branch is 23 commits behind the master.

**Comment by notapatch** [comment]
I do apologise I didn't understand your clear question and it has now been rebased. The webdrivers PR didn't help although I think the error message was clearer.

[I have a PR in to change Chrome install from unstable to stable.](https://github.com/codebar/planner/pull/1149) I've no idea unstable was chosen. It fixes it for me but does it fix the issue for you?

| Chrome type |  Version |
|:--------------|--------:|
| Stable            |  78          |
| Unstable        |  80         |

[The PR is here if you are interested](). 

Not expert on docker - I tested it by changing bin/dbuild to no cache - just to be sure:

```
#!/bin/sh
set +e
docker-compose down -v --remove-orphans
docker-compose build --no-cache
docker-compose run --rm web rake db:create db:migrate db:seed db:test:prepare
```

Then ran `bin/dspec` and it all passed
