### ISSUE TITLE
Any native (non-docker) users of planner?

### ISSUE THREAD

**Issue by notapatch** [codebar/planner#1147]
We have been using an unmaintained Gem for a few months now,  and you won't believe it, but it's caused us a few issues(https://github.com/codebar/planner/issues/1012 https://github.com/codebar/planner/issues/1061 https://github.com/codebar/planner/issues/1144). If a native user can test this and see if there is any wrinkles in using it? When I programmed the pull request it was in a blur and I was googling along and don't know if there was an issue that might hold up a new developer. I've provided instructions and It shouldn't take more than a few minutes of your time. 

https://github.com/codebar/planner/pull/1038

```
   git fetch upstream pull/1038/head:webdrivers
   git checkout webdrivers
   rspec spec       
```

If you know what your doing it's 7 minutes of your time - if it's taking longer then report back because that is an issue. Now, if you've never fetched a pull request before 😮!  Well, you definitely should try - support will be given.

**Comment by jabawack81** [comment]
tested on os x 10.14.6 and I got no errors:

```
Randomized with seed 28665
...............................Capybara starting Puma...
* Version 4.2.1 , codename: Distant Airhorns
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:54365
................................................................................................................................................................................................................
................................................................................................................................................................................................................
.......................................

Finished in 1 minute 47.07 seconds (files took 4.27 seconds to load)
486 examples, 0 failures

Randomized with seed 28665

Coverage report generated for RSpec to /Users/paolofabbri/internetblacksmith/codebar_planner/coverage. 2316 / 2553 LOC (90.72%) covered.
[Coveralls] Outside the CI environment, not sending data.
```

once home I'll test it on Ubuntu

**Comment by notapatch** [comment]
@jabawack81 - That's really helpful thanks! We've just merged the issue. Just do a straight pull now. We haven't tried Ubuntu so that would also be a win. If that works out I can close this issue and not worry.

**Comment by notapatch** [comment]
Closing as I think we're good.

**Comment by jabawack81** [comment]
sorry ti took me a little longer than I said but this is a run on Ubuntu:

```
Randomized with seed 19823
...................................................................................................................................................................................................................................................................................................................................................................Capybara starting Puma...
* Version 4.2.1 , codename: Distant Airhorns
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:46163
...................................................................................................................................

Finished in 4 minutes 39.8 seconds (files took 12.97 seconds to load)
486 examples, 0 failures

Randomized with seed 19823
```

**Comment by notapatch** [comment]
Thanks very much! It's reassuring that there won't be new people to the project being stopped by my PR.

(There's a lot of issues open and I was doing my part to keep them down.)

**Comment by notapatch** [comment]
Can I ask @jabawack81 are you using docker or natively? I have a laughably slow 2014 Mac (the new macbook is looking tasty) and it completes it in about 2 minutes.

```

Randomized with seed 33806
...........................................................................................................................................................................................................................................................................................................................................................Capybara starting Puma...
* Version 4.2.1 , codename: Distant Airhorns
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:56558
...........................................................................................................................................

Finished in 1 minute 58.42 seconds (files took 9.21 seconds to load)
486 examples, 0 failures
```

**Comment by jabawack81** [comment]
I'm native on a MacBook Pro (15-inch, 2018)

**Comment by notapatch** [comment]
Right that's the 1 minute something one ... but the Ubuntu one was almost 5 minutes yes?

**Comment by jabawack81** [comment]
yes I use it on a hand down old laptop with a AMD A10-7300 Radeon R6 4C+6G (4) @ 1.900GHz

**Comment by notapatch** [comment]
Alright, no reason for alarm. 👍
