### ISSUE TITLE
Excessive screen output during the build process

### ISSUE THREAD

**Issue by jhsu802701** [codebar/planner#1148]
During the build process, my terminal is flooded with messages about successful database transactions.  The configuration should be changed to skip printing so many messages, because they make it harder to troubleshoot in the event that something goes wrong.

**Comment by jhsu802701** [comment]
I have submitted Pull Request #1150 to resolve this issue.

**Comment by notapatch** [comment]
So there's an alternative. You can have a rake file and all it does is sets the logging level to info and then call the other rake commands so db:migrate db:seed etc. That way you get lower output not ideal but not bad and it wouldn't have the downside of switching off debug for all development.

[The code looks like this.](https://github.com/notapatch/planner/pull/12/commits/56858bc3dcaa008592febb97776e2e8985097d8c) and the [output looks like this](https://gist.github.com/notapatch/8565634c81e2535d9ab3dbe3d9a7e256)

Does this look OK to you? If it does the next step is to ask the maintainers if they are interested.

**Comment by biggianteye** [comment]
I agree that the screen output when building the project is excessive. It also feels quite hostile to newcomers. I agree that it needs reducing to be more useful.

The approach offered by @notapatch seems useful as it offers a way to maintain debug during application use (where it's useful) but shuts it up during setup. Can rails take in values from environment variables? I would assume yes. If so, that might be a better approach as it requires less new code.

eg. `bin/dbuild` would contain something like:

```
LOG_LEVEL="INFO" docker-compose run --rm web rake db:create db:migrate db:seed db:test:prepare
```

`config/environments/development.rb` would then be tweaked a little to use `LOG_LEVEL` if it exists.

**Comment by notapatch** [comment]
I was thinking the script should try to be as much like a standard Bash script as possible:

`bin/dbuild`  - defaults to warn or higher
`bin/dbuild -h` - displays help about -i and -w etc
`bin/dbuild -i` outputs at info 
`bin/dbuild -w` outputs at warn etc

**Comment by biggianteye** [comment]
> I was thinking the script should try to be as much like a standard Bash script as possible:

Sounds sensible. Though the common pattern would be silent with no params and `-v`, `-vv`, `-vvv`, etc for increasing levels of verbosity.

**Comment by notapatch** [comment]
Very good `-v, -vv, -vvv`. I intend to pass or my _brilliant_ script ideas through you.  👍

**Comment by notapatch** [comment]
@matyikriszta has "OKed" the work.

A Thor task with minimal logging will run the same commands we do already do (db:migrate db:seed etc) and only change the logging level during setup. The task should allow for additional flags so we can change, in future PRs - for example seeding levels.  [I've done a rake version to give an idea](https://github.com/notapatch/planner/pull/12/commits/56858bc3dcaa008592febb97776e2e8985097d8c) but rake doesn't handle flags cleanly - the PR should try with Thor.  ⚡️ 🔨

I will leave the issue open if @jhsu802701 wants to do it, or anyone else.  

#### Reference
[Open Issue](https://github.com/codebar/planner/issues/1148)
[Thor - Railscasts - old but good overview](http://railscasts.com/episodes/242-thor?autoplay=true)
[Calling Rake Tasks with Thor](https://github.com/erikhuda/thor/wiki/Calling-Rake-tasks-with-Thor)
[Thor](https://github.com/erikhuda/thor)
