### ISSUE TITLE
Timestamps deprecation warnings

### ISSUE THREAD

**Issue by jhsu802701** [codebar/planner#1151]
Running the database migrations leads to multiple instances of the following deprecation warning message:
```
WARN -- : DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing.
```

**Comment by notapatch** [comment]
Good spot 👍 

What we have:

```
class CreateInvitations < ActiveRecord::Migration
  def change
    create_table :invitations do |t|
      t.references :sessions, index: true
      ...
      t.timestamps
    end
  end
end
```

Rails 5 is changing the default[1]: 
> Changed the default null value for timestamps to false. (commit)

We should want to stay with the default. I don't think we are doing anything clever with the timestamps? In that case what we want is:

```
class CreateInvitations < ActiveRecord::Migration
  def change
    create_table :invitations do |t|
      t.references :sessions, index: true
      ...
      t.timestamps null: false        <= this gives no nulls in column
    end
  end
end
```

[The way to do it is to use `change_column_null`](https://api.rubyonrails.org/v6.0.0/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column_null) 

The main worry is that the table could have a null timestamp (always possible). In that case you can use a fourth parameter which sets the default. For our example the migration should look something like this (untested!):


```ruby
def change
  change_column_null :invitations, :timestamps, false, Time.now
end

```

Where **false means no nul**l.

The verification would be:

```sql
planner=# \d invitations
                                          Table "public.invitations"
     Column     |            Type             | Collation | Nullable |       Default
----------------+-----------------------------+-----------+-------------------------
 id             | integer                     |           | not null | next...
 created_at     | timestamp without time zone |           | not null |  <=== this
 updated_at     | timestamp without time zone |           | not null |   <=== this

```

Clearly, we can knock out these migrations in a few minutes - the main issue is time updating production. 


### References
[1] [Rails 5.0 Release notes - active-record-notable changes](https://guides.rubyonrails.org/5_0_release_notes.html#active-record-notable-changes)
[How to change a nullable column to not nullable in a Rails migration?](https://stackoverflow.com/questions/5966840/how-to-change-a-nullable-column-to-not-nullable-in-a-rails-migration)
