### ISSUE TITLE
Attendance list does not show all RSVP times

### ISSUE THREAD

**Issue by biggianteye** [codebar/planner#1156]
## Description of the issue 📄
The attendance list visible in the admin interface (`https://codebar.io/admin/workshops/<id>`) shows RSVP times for both students and coaches. The list is incomplete though. Only some entries have dates and it is unclear why.

I've put my hypothesis about why this might happen under the screenshot because it requires that context.

## Screenshots 📷
This screenshot shows the attendance list for a workshop that took place on 12th November and was set up on 5th November. It demonstrates that some students have RSVP times and some don't.

![image](https://user-images.githubusercontent.com/1482649/68755057-d8c7e600-05ff-11ea-872b-380cfa4edba1.png)

Not shown above is the fact that none of the waitlist entries have RSVP times listed. This observation combined with the fact that the only dates shown are on the day the event created gives me a hypothesis:

> The people who don't have an RSVP time are people who have been added from the waitlist.

Note that this hypothesis is disproven for coaches because the coach list for this event had a coach without a date and there was no waitlist for coaches in this instance. I don't know if coaches and students are handled differently, so the hypothesis may still be valid.

## Steps to fix 🛠
Without knowing the source of the problem, it's hard to say. Assuming my hypothesis is correct, keeping track of RSVP times for people in the waitlist would probably fix this.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
So, a many of the readers of the issues are not power users of Planner. It is going to help if you give a URL. Do you have a URL?

As it happens I'm also a part time detective (🦌 🎩 👓 - err, that was meant to be Sherlock Holmes deerstalker - future generations will wonder how we coped with so few emojis). So, I reckon you are on about this controller and this view:

```haml
# controller: 
app/controllers/admin/workshops_controller.rb 

# view
# app/views/admin/workshops/show.html.haml
  .stripe.reverse#invitations
    = render partial: 'invitation_management'

  #
  # this renders the inviation_management partial
  # app/views/admin/workshops/_invitation_management.html.haml
  #
  %br

  .row
    .medium-6.columns
      %h4
        Students
        %label.label.round.secondary #{@attending_students.count}#{(" of " + @workshop.host.seats.to_s) if @workshop.has_host?}
        %label.label.round.signed-in #{ @attending_students.count(&:attended) }
        ######################################################
        # This partial
      = render partial: 'admin/workshop/attendances', locals: { invitations: @attending_students }
        #########################################################
      = render partial: 'admin/workshop/waiting_list', locals: { waiting_list: @student_waiting_list }
    .medium-6.columns
      .row
        %h4
          Coaches
          %label.label.round.secondary #{@attending_coaches.count}#{(" of " + @workshop.host.coach_spots.to_s) if @workshop.has_host?}
          %label.label.round.signed-in #{ @attending_coaches.count(&:attended) }
      = render partial: 'admin/workshop/attendances', locals: { invitations: @attending_coaches }
      = render partial: 'admin/workshop/waiting_list', locals: { waiting_list: @coach_waiting_list }
```

Which leads us to the partial (partials start with _ ) `_attendances.html.haml` and the bit you're interested in, I think, is the highlighted with asterisks. 

```haml
# app/views/admin/workshop/_attendances.html.haml
.row
  %table.attendances.large-12.columns
    %tbody
      - invitations.each do |invitation|
        %tr.row.attendee
          %td.small-1.columns
            - if (invitation.parent.date_and_time - 30.minutes).past?
              - if invitation.attended.nil?
                = link_to admin_workshop_invitation_path(@workshop, invitation, attended: true), class: 'verify_attendance', title: 'Verify attendance', method: :put, remote: true do
                  %i.fa.fa-square-o
              - else
                %i.fa.fa-check-square-o
            - else
              = link_to admin_workshop_invitation_path(@workshop, invitation, attending: false), class: 'cancel_attendance', title: 'Cancel RSVP', data: { confirm: "Are you sure you want to remove #{invitation.member.full_name} from the list of attendees?" }, method: :put, remote: true do
                %i.fa.fa-minus-square-o
          %td.small-5.columns
            - if invitation.member.newbie?
              %span.has-tip{ 'data-tooltip': '', 'aria-haspopup': 'true', title: 'New attendee.' }
                %i.fa.fa-paw
            - elsif invitation.member.more_than_two_absences?
              %span.has-tip{ 'data-tooltip': '', 'aria-haspopup': 'true', title: 'More than 2 no-shows' }
                %i.fa.fa-exclamation-circle

            = link_to admin_member_path(invitation.member) do
              - if invitation.member.full_name.blank?
                = invitation.member.email
              - else
                = invitation.member.full_name
          %td.small-6.columns
            %small=invitation.note
           ###############################################
            - if invitation.rsvp_time.present?
           ###############################################
              %span.has-tip{ 'data-tooltip': '', 'aria-haspopup': 'true',  title: 'Time of RSVP' }
                %small
                  %i.fa.fa-clock-o
                  =l(invitation.rsvp_time)
```

The invitation is a workshop invitation (it's the only attribute in the database schema that's rsvp_time. So it's a datetime and we're checking if it's `present?` which works out as meaning not` blank?`. 

```ruby
  # db/schema.rb
  create_table "workshop_invitations", force: :cascade do |t|
    t.integer  "workshop_id"
    t.integer  "member_id"
    t.boolean  "attending"
    t.boolean  "attended"
    t.text     "note"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "token"
    t.string   "role"
    t.datetime "reminded_at"
    t.datetime "rsvp_time"
  end

```

A Workshop invitations have_one waiting_list

```ruby
class WorkshopInvitation < ActiveRecord::Base
  has_one :waiting_list, foreign_key: :invitation_id
  ...
end
```

The waiting_list database schema is

```ruby
  # db/schema.rb
  create_table "waiting_lists", force: :cascade do |t|
    t.integer  "invitation_id"
    t.boolean  "auto_rsvp",     default: true
    t.datetime "created_at"
    t.datetime "updated_at"
  end

```

Investigate 1: If I had to _guess_ the actual rsvp time is sent on the controller (you could set the time in Javascript but it would be easier in the controller). In which case this is the code I would check first. So when someone accepts the invitation the time is taken.


```
  # app/controlleres/invitation_controller.rb

  def accept_with_note
    @workshop = WorkshopPresenter.new(@invitation.workshop)
    ##################################################################
    @invitation.update(note: params[:workshop_invitation][:note], rsvp_time: Time.zone.now)
    ##################################################################
    ...
  end
```

Investigate2: The other possibility is `invitation_controller_concerns.rb` concerns is a ruby rails way of code reuse and you can see in the code `include invitationControllerConcerns` at the top of the `invitation_controller` this also sets rsvp_time.

```ruby
      @workshop = WorkshopPresenter.new(@invitation.workshop)
      if (@invitation.for_student? && @workshop.student_spaces?) || (@invitation.for_coach? && @workshop.coach_spaces?)
        @invitation.update(attending: true, rsvp_time: Time.zone.now)
       ...
      end
```

I hope I guessed right - it helps me understand the system better regardless. So, In that case does that help the hypothesis?


### Reference
[Haml](https://github.com/haml/haml)
[datetime](https://api.rubyonrails.org/classes/DateTime.html)
[Present?](https://api.rubyonrails.org/classes/Object.html#method-i-present-3F)
[Blank?](https://api.rubyonrails.org/classes/Object.html#method-i-blank-3F)
[Rails associations including has_one](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html)

**Comment by biggianteye** [comment]
> So, a many of the readers of the issues are not power users of Planner. It is going to help if you give a URL. Do you have a URL?

Oops. Sorry about that. I've updated the description with url. It's `https://codebar.io/admin/workshops/<id>`.

**Comment by biggianteye** [comment]
Great investigation. I'll have a proper think about it when I have a bit of spare time.

**Comment by notapatch** [comment]
I've updated the message so you can remove this message to keep it cleaner:

> So, a many of the readers of the issues are not power users of Planner. It is going to help if you give a URL. Do you have a URL?
> 
> Oops. Sorry about that. I've updated the description with url. It's https://codebar.io/admin/workshops/<id>.
> 

I'll then delete this

**Comment by biggianteye** [comment]
Based on the structures of the `workshop_invitations` and `waiting_lists` tables, it looks my hypothesis was correct. Waiting list entries don't have an RSVP time. Unclear if this was an oversight or a design choice.

**Comment by notapatch** [comment]
I'm working from memory here and this has chance of being wrong - and happy to spend more time if this gets approval.

So we know what we're talking about. This should be a state diagram but, _err_, table is easier here.

|Type                              |  invitation sent | Responded | Attending | rsvp time           | on list            |
|:----------------------|:---------------|:------------|:----------|----------------|:--------------:
| workshop_invitations  |  true                  | true             | true          |  respond time    | attending list |
| waiting_lists                | true                   | true             | false        |  nil                       | waiting list |
| waiting_lists => workship_invitations      | true                   | true             | true        |  nil                       | attending list |

If you were serious about making a change I would look at the commits to see if there's helpful comments. If no good reason and if the intention is to remove a nil from the system, and assuming you get approval, be my guest. The fewer nils, the fewer logic branches, the less chance of exceptions. I'd go as far as looking if it's possible to always have an rsvp time at all times but this may or may not be possible. 

There's also a already approved request to [add the waiting list to events](https://github.com/codebar/planner/issues/1102). So getting an understanding of waiting lists  - and removing the "odd" things from it is going to help when discussing that PR. 

---
To turn your hypothesis into concrete work. Is the request, assuming your investigation works out, to give someone moving from the waiting_list to the workshop invitations list (or whatever it's called) an rsvp time?

**Comment by despo** [comment]
When this code was initially put in place, the reminded_time was displayed and not the RSVP time. At some point this was [changed to log the rsvp_time](https://github.com/codebar/planner/commit/89ae3bf85a8534a74142f2151639ff0ec03674cc).

I don't know if it was done intentionally but I definitely see the value in not having RSVP time if it hapenned automatically. 

To resolve this we should 
---------------------------
- add a new field `automated_rsvp: boolean`
- when people are moved to the list from the waiting list track `rsvp_at` along with `automated_rsvp`
- extend the page to include `automated_rsvp` and also to render `reminded_at` so we are aware if reminder emails have also been sent
