### ISSUE TITLE
Chapter organisers should not see Review Jobs and View Feedback in menu

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1163]
## Description of the issue 📄
Chapter organisers should not see "View Feedback" and "Review Jobs" in the menu. Only admins should see this.

## Screenshots 📷

![image (1)](https://user-images.githubusercontent.com/2683270/69439941-d4a67180-0d3f-11ea-9d7a-3b43c0656570.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by shen-sat** [comment]
Hi @KimberleyCook, I'd like to take on this issue if possible? I've contributed to open source once bfeore, and I've been learning to use Rails (for over 3 months) in my current job. I've not worked on on any authorisation features before, but keen to jump in :)

**Comment by KimberleyCook** [comment]
@shen-sat please do :)

**Comment by despo** [comment]
Resolved by attached PR

**Comment by shen-sat** [comment]
Apologies for not working on this PR. I signed up to a couple of other OS projects and wasn't realistic with my time management. I should have given you a heads up :(
