### ISSUE TITLE
Sign-up Issue on Safari

### ISSUE THREAD

**Issue by HedgehogHolly** [codebar/planner#1190]
## Description of the issue 📄
A user signed up for a github account and when they tried to sign up as a student the information had been pre-filled and they weren't able to edit the field or press next because the fields were apparently blank.

The issue occurred using Safari on macOS Catalina (10.15.3).  When the user switched to using Chrome, they were able to edit the fields and sign up properly.

If you need anymore information, let me know.

## Screenshots 📷
![Screenshot 2020-02-10 at 16 13 32](https://user-images.githubusercontent.com/41140803/74248087-fd0a9000-4cde-11ea-9ea2-56a98ddc933b.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@HedgehogHolly looking at the screenshot the fields have not been pre filled, those are placeholder values. Are you sure they weren't able to edit the fields e.g. click inside them and add other text. I do agree however that the placeholders are a bit confusing, we do have a PR in the works that removes them.

**Comment by HedgehogHolly** [comment]
@matyikriszta Oh! I didn't realise those were placeholder values. I think because it auto filled her email address and the text colour is very similar it looked like it auto filled all the other information as well.  Either way, for some reason she was still unable to click into the fields to add her information.

**Comment by Indrajitnaiya09** [comment]
@matyikriszta @HedgehogHolly Then this is not an issue right!!
