### ISSUE TITLE
Rename `date_and_time` to `start_date_and_time` in all Event models

### ISSUE THREAD

**Issue by despo** [codebar/planner#1224]
## Description of the issue 📄

- Rename the Workshop, Event and Meeting `date_and_time` field to `start_date_and_time`
- Rename `time` to `start_time` in DateTimeConcerns
- Ensure there are tests in place to verify that the fucntionality has been updated where needed (event pages, shared pages (event listing, homepage), reusable partials. Add more tests if needed

https://github.com/codebar/planner/pull/1220#discussion_r392937309

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
### Rename the Workshop, Event and Meeting date_and_time field to start_date_and_time

I think it's a great idea to change away from date_and_time - I found it confusing too. However, if I understand correctly `start_date_and_time` would pair with `ends_at` ?

| Table | Beginning time attribute | Ending time attribute |
|:-------|:--------------------------|:--------------------|
| events | date_and_time                   | ends_at                    |
| meetings | date_and_time               | N/A                          |
| workshops | date_and_time               | ends_at                 |

- I would have thought either `start_date_and_time` becomes `starts_at ` or you change both so `start_date_and_time` and `end_date_and_time`


---
### Rename time to start_time in DateTimeConcerns

On the replacement of time to start_time

Search for "time" would be by any standards an act of self harm, with over a thousand results. I think a regex of `\.time\b` might help the search? There may be better searches.

```
\.       = escape full stop
time  = match text 'time'
\b      = word boundary
```
