### ISSUE TITLE
HTML text not displayed properly in workshop page

### ISSUE THREAD

**Issue by brunogirin** [codebar/planner#1227]
## Description of the issue 📄
When creating a workshop, we can now enter HTML in the workshop description. That HTML is displayed properly on the admin version of the workshop page but not on the attendee version.

## Screenshots 📷
Admin version with link:
![Annotation 2020-03-18 201013](https://user-images.githubusercontent.com/216028/77003246-e6e29600-6954-11ea-9865-4557e32644ce.png)

Attendee version with HTML code showing:
<img width="1326" alt="Screenshot 2020-03-18 at 20 09 27" src="https://user-images.githubusercontent.com/216028/77003274-f366ee80-6954-11ea-8184-33b27f3f04ef.png">

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Fixed by #1228 and deployed to production.

**Comment by despo** [comment]
And confirmed!

<img width="1140" alt="Screen Shot 2020-03-18 at 22 52 48" src="https://user-images.githubusercontent.com/159200/77014884-303de000-696b-11ea-96b5-1adbc8803e9a.png">
