### ISSUE TITLE
Any event invitations should not be emailed to banned members

### ISSUE THREAD

**Issue by despo** [codebar/planner#1259]
## Description of the issue 📄
Even though banned members are unable to RSVP to the monthlies, they still receive invitations. 

The process sending out monthlies invitations should be updated to not include banned members.

## Steps to fix 🛠
Have a look at `InvitationManager` as thsi is where all event invitations are trigerred from
`app/models/invitation_manager.rb`

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
Quick clarification @despo:  so emails generated by all of these methods?

```
  # app/models/invitation_manager.rb
  def send_event_emails(event, chapter)
  def send_monthly_attendance_reminder_emails(monthly)
  def send_course_emails(course)
```
Or just `send_monthly_attendance_reminder_emails` ?

---

If anyone reading this wants to have a go, please do... 

There seems to be a scope in member called `not_banned` that might be useful.

```
Class Member
  ...
  scope :not_banned, lambda {
                       joins('LEFT OUTER JOIN bans ON members.id = bans.member_id')
                         .where('bans.id is NULL or bans.expires_at < CURRENT_DATE')
                     }
 ...
```

**Comment by despo** [comment]
By having a brief look I think only the monthlies emails would have to be updated as it seems like the `Member` [`in_group`](https://github.com/codebar/planner/blob/master/app/models/member.rb#L35) scope already takes `not_banned` into account so not all methods would have to be updated it seems.

```
  def chapter_students(chapter)
    Member.in_group(chapter.groups.students)
  end

  def chapter_coaches(chapter)
    Member.in_group(chapter.groups.coaches)
  end
end
```
https://github.com/codebar/planner/blob/master/app/models/invitation_manager.rb#L45

**However**, I am mostly interested in the tests being expanded to cover this scenario even for the methods that don't require any change, and this would include tests for methods included in https://github.com/codebar/planner/blob/master/app/models/concerns/workshop_invitation_manager_concerns.rb as well.

And it would be an added bonus to also move this in the `InvitationManager` https://github.com/codebar/planner/blob/master/app/controllers/admin/meetings_controller.rb#L54 and handly emails being sent out asynchronously
