### ISSUE TITLE
Install imagemagick via docker container

### ISSUE THREAD

**Issue by despo** [codebar/planner#1263]
## Description of the issue 📄
Update Dockerfile to also install imagemagick required for creating new sponsors.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by koddsson** [comment]
Hey hey! I just checked this out by setting up a fresh docker instance and I can see sponsor thumb images and it seems that imagemagick is installed in the docker container.

```sh
root@eb2a65b9109b:/planner# convert --version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-11-16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

root@eb2a65b9109b:/planner#
```

I dug through the docker images and I can see that imagemagick is installed in the buildpack image right here:

https://github.com/docker-library/buildpack-deps/blob/4d7c3e93fd1cafae3e319925fb6dcf43537e1ca9/debian/jessie/Dockerfile#L15

**Comment by despo** [comment]
@koddsson Hmmm. I opened this issue after getting some errors when trying to setup the project on someone else's laptop last weekend. Unfortunately we did not keep a copy of the error so I don't even remember what it was exactly. 🤦‍♀️ 

Closing as per your feedback.
