### ISSUE TITLE
User Chapter `active` scope to ensure that only active chapters and subscriptions are rendered

### ISSUE THREAD

**Issue by despo** [codebar/planner#1264]
## Description of the issue 📄

Places to check and test 
- [ ] /subscriptions
- [ ] /admin/members/[id]
- [ ] /profile

If you think of any other locations please add a comment to this issue

## Steps to fix 🛠
Using existing Chapter `active` scope

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by Rosa-Fox** [comment]
I would like to claim this.

**Comment by despo** [comment]
@Rosa-Fox I've assigned it to you!
