### ISSUE TITLE
Set up information in README

### ISSUE THREAD

**Issue by Rosa-Fox** [codebar/planner#1265]
## Description of the issue 📄

Some set up information to add to the README for running without Docker.

## Steps to fix 🛠
Following commands could be useful for people less familiar with Rails:
- `bundle`
- `bundle exec rake db:migrate`
-  brew install imagemagick
- `bundle exec rake db:drop db:create db:migrate db:seed` (for setting up the db with seed data)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
[You would want to review the current instructions](https://github.com/codebar/planner/blob/master/native-installation-instructions.md) 

Which is linked here: 

> 3. Install and set up the environment
> 
> We recommend using Docker to install and run the application. However alternatively if you prefer, you can install directly to your system environment instead.

It might be that the link should be clearer about what it is about? Installing directly onto your system vs without docker. I think a big issue is that the README is dominated by Docker and there's just this one link taking you to a completely different page and if you miss it you're lost.
