### ISSUE TITLE
Don't show not invitable label on workshop page unless members cannot RSVP

### ISSUE THREAD

**Issue by despo** [codebar/planner#1278]
## Description of the issue 📄
At the moment workshops who have an rsvp opening time set always get the non invitable text on the admin page as only the [`invitable`](https://github.com/codebar/planner/blob/master/db/schema.rb#L562) attribute is checked instead of both that the rsvp opening time is in the past **or** invitable is checked (look at `invitable_yet?`, defined in the `workshop_model`.

## Screenshots 📷

<img width="586" alt="Screen Shot 2020-05-15 at 15 52 29 1" src="https://user-images.githubusercontent.com/159200/82064222-60cc9c80-96c4-11ea-8e99-34afe2471a82.png">

## Steps to fix 🛠
- update check to be `rsvp opening times || invitable` for non invitable label
- update text when rsvps are available to specify since when `RSVPs opened up at XX:XX on XX/XX/XXXX` 

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by AFed29** [comment]
Got the docker setup working! Would quite like to take this up if that's ok! I'll check what was fixed in #1335 and try and resolve this issue 😄

**Comment by matyikriszta** [comment]
@AFed29 yes, go ahead

**Comment by Indrajitnaiya09** [comment]
@AFed29 Are you working on this? Else I'd like to pick it up.

**Comment by AFed29** [comment]
Go for it! I've been swamped recently so haven't looked much at it!
