### ISSUE TITLE
Add ends_at on Meeting and Course models

### ISSUE THREAD

**Issue by despo** [codebar/planner#1306]
## Description of the issue 📄
Meetings already specify an end time (eg [here](https://codebar.io/meetings/monthly-jan-2020), [here](https://codebar.io/meetings/monthly-feb-2020) or [here](https://codebar.io/meetings/monthly-oct-2018)!) as part of their agenda and in an effort to keep the Course model active and probably reintroduce we should also keep it similar to all other Event models.

## Steps to fix 🛠
- add migrations that add an `ends_at` datetime column on meetings and courses
- update views and calls to humanize_date to include `ends_at` (similar to workshop and event pages)
- update Course and Meeting email content to include end time (no need to include in email title even if date is mentioned)
- update tests to reflect changes

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by mattlindsey** [comment]
Hi. Retired programmer here who also works on another rails site  [https://github.com/AgileVentures/WebsiteOne] would like to try adding this and the next one #1307

**Comment by despo** [comment]
@mattlindsey Hi Matt. 

Thanks for offering to help. If you can pick this up that would be great! 
Workshops already have an `ends_at` so that's a good place to start.

Let me know if you have any questions.

**Comment by mattlindsey** [comment]
great @despo. Only question so far is how to make myself an admin or organizer. I see that it's through the Rolify gem in the console, but I don't know the command. I'll try to look it up, or let me know.

**Comment by despo** [comment]
@mattlindsey I don't think we have a course management page. We have not used that event type in a while and at the time used the command line to insert data 🙄 (but have legacy data in our system), however if we manage to get it up to date its something that we would like to reintroduce and add some admin views for, as it makes sense of some types of events. 

The purpose of this change is to eventually update the `Listable` module (`/app/models/concerns/listable.rb`) to retrieve upcoming events based on their `ends_at` time.

Meetings should be in `app/views/admin/meetings`
