### ISSUE TITLE
When meeting invitation emails are sent, 'MeetingInvitations' should be created

### ISSUE THREAD

**Issue by despo** [codebar/planner#1317]
## Description of the issue 📄

Currently we track meeting invitations emailed out by [updating a value on the meeting model](https://github.com/codebar/planner/blob/master/app/controllers/admin/meetings_controller.rb#L54). There are a couple of issues with that, such as:
- Emails are all emailed out from the controller and don't utilise a delayed job
- This process often fails due to the amount of emails and thus the variable is not set
- It makes the process prone to errors and we've had issues with repeat emails multiple times!

## Steps to fix 🛠

In order to be able to both track and manage meeting invitations the same way we do for other events, 
- The meeting invitation sent process should be moved to the `InvitationManager` model and an invitation should be sent out **only if no MeetingInvitation associated with the Meeting and Member does not exist**, similar to WorkshopInvitations etc
- A `MeetingInvitation` entry should be created and be associated with each email
- The appropriate changes need to happen in the relevant Meeting views and controllers so that on RSVP the model is updated rather than created
- The MeetingInvitation mailed needs to be updated to accept a model
- Any other required changes to the `MeetingInvitation` model to support this functionality

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by gnclmorais** [comment]
I’m happy to take this, @despo! 🙋

**Comment by despo** [comment]
@gnclmorais assigned!

**Comment by despo** [comment]
Resolved by #1454
