### ISSUE TITLE
Display more details in attendance warning confirmation dialog

### ISSUE THREAD

**Issue by despo** [codebar/planner#1319]
## Description of the issue 📄
If a member has already received an attendance warning, **render the details** on the dialog confirming sending out one again.

e.g. if attendance warning already sent change text to render 
> ((member name)) has already received a warning about missing too many workshops on ((datetime)). Are you sure you want to proceed with sending another one?

## Screenshots 📷

<img width="1329" alt="attendance-warning" src="https://user-images.githubusercontent.com/159200/82568473-c6ae9d80-9b76-11ea-919e-80ad8d9b9d92.png">

## Steps to fix 🛠
To get to the page on your local environment you need to grant yourself the admin role
`Member.find(:id).add_role(:admin)`

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by naveenk97** [comment]
Can I do it? I am a beginner in this.

**Comment by despo** [comment]
@naveenk97 of course. Let us know if you have any questions.

**Comment by mkoltonski** [comment]
Hi, can i take this issue ?

**Comment by matyikriszta** [comment]
@mkoltonski yes, please do.
