### ISSUE TITLE
Codebar.io Sign up / Sign in issue

### ISSUE THREAD

**Issue by maxxfrazer** [codebar/planner#1355]
## Description of the issue 📄

When signing up or attempting to sign in on codebar.io I'm shown the "Something went wrong" page, as shown in screenshot. Based on the screenshot it seems to be an issue with GitHub? I checked my account settings > Applications > Authorized OAuth Apps, and codebar.io is where it should be with appropriate account access.

## Screenshots 📷
<img width="677" alt="Screen Shot 2020-06-09 at 10 23 55" src="https://user-images.githubusercontent.com/5754073/84132343-af5c2500-aa3d-11ea-8427-80a0440566e2.png">

Retracted some of the data from this, not sure which parts would be sensitive.
<img width="807" alt="Screen Shot 2020-06-09 at 10 38 24" src="https://user-images.githubusercontent.com/5754073/84132362-b2efac00-aa3d-11ea-8435-570ce76bef79.png">

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
@maxxfrazer Do you have a public email address set on your GitHub account? Someone else encountered the same problem and that was the issue we identified.

**Comment by despo** [comment]
Resolved as part of #1457
