### ISSUE TITLE
New Postgres image requires password to be set

### ISSUE THREAD

**Issue by AFed29** [codebar/planner#1380]
## Description of the issue 📄

Newer versions of the Postgres image require a password to be set using using the POSTGRES_PASSWORD environment variable. [(postgres image info)](https://hub.docker.com/_/postgres)

The lack of this causes the postgres container when building and running  from the docker-compose YAML file, to not start and the web container to fall over immediately, as it depends upon it.

## Steps to fix 🛠

Add default environment variables for POSTGRES_PASSWORD (possibly just password) for use in local development.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by AFed29** [comment]
I'd like to claim this, I've got a wee fix!

**Comment by despo** [comment]
@AFed29 I think to do this you should configure a DB_USER variable in `docker-compose.env` and probably follow the same pattern in the database configuration. This way non-docker users should not be impacted.

As the configuration is specific to the test and development environments it should not impact deployment and the staging or production environments.

**Comment by despo** [comment]
Resolved by #1382
