### ISSUE TITLE
I can not add a workshop 

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/planner#1385]
## Description of the issue 📄
When attempting to select a date from the calendar, I can't get the present month , this prevents me for creating a new workshop. I would expect the default month is August 2020, but instead I get June 2020

## Screenshots 📷
![calender](https://user-images.githubusercontent.com/4013283/90512389-9fec0d00-e14d-11ea-94ca-aa5eedb759be.gif)

## Steps to fix 🛠
I have no idea currently

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
@khamiltonuk I can't replicate this. 

What browser are you using and can you work around it by using a different browser? I tried the date field on Firefox and it works as expected for me.

**Comment by khamiltonuk** [comment]
@despo It's happening to me in chrome, but I can get around it by using incognito, or firefox

**Comment by despo** [comment]
@khamiltonuk was the one off or are you still experiencing this issue? Could there have been something wrong with your laptop's system date at the time?
