### ISSUE TITLE
Adding people from the waiting list manually can make them disappear

### ISSUE THREAD

**Issue by Drescoding** [codebar/planner#1474]
## Description of the issue 📄

On an event, I tried to add someone manually (+), they confirmed that they got an email but their name doesn't appear anywhere (CSV, email list or the attendees). I then tried to add them from "Select a member to RSVP", it says it worked (see screenshots) but then they still don't appear.

It happened with Jean Francois (see screenshot) for the Oxford chapter and Toni Georgieva on Wednesday 20/01/2021 for the London chapter.

## Screenshots 📷
![image](https://user-images.githubusercontent.com/37814413/105472043-5ae77c00-5c93-11eb-8343-4e002c02a429.png)
![image](https://user-images.githubusercontent.com/37814413/105472056-5de26c80-5c93-11eb-8d54-4644b8cbd0cd.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by gnclmorais** [comment]
I’ve address this on https://github.com/codebar/planner/pull/1475, thanks to @despo’s insight 🕵️🕵️‍♀️
