### ISSUE TITLE
Sign-up flow needs checking

### ISSUE THREAD

**Issue by ambrwlsn** [codebar/planner#1486]
## Description of the issue 📄

A new coach went to sign up and when clicking on the link to join codebar Slack, said they were told they were not authorised to do so. A link under "How to join" led this person to see an error message.

## Screenshots 📷

![Screenshot 2021-02-22 at 09 49 39](https://user-images.githubusercontent.com/20335874/108692424-dfc8ee00-74fc-11eb-8eb6-737097533698.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
I don't think this is related to the sign up flow. However the link to slack is indeed not generated correctly which is probably what caused the confusion as clicking it would just refresh the current page, and then attempting to join the berlin chapter would display the unauthorised error.

[This line](https://github.com/codebar/planner/blob/44a2e2e835bbb0520a6d2b151b0a15d827b494ad/app/views/invitation/show.html.haml#L97) should be updated to link to the displayed path.

```ruby
  %li= t('workshop.virtual.invitation.info.line_1_html', slack_link: link_to(nil, t('social_media_links.slack_html')))
```
