### ISSUE TITLE
Further updates/considerations for admin/member page

### ISSUE THREAD

**Issue by despo** [codebar/planner#1501]
Feedback left on PR #1455 that can be addressed now that the PR has been merged.

---
Will the "attendance summary" include the number of missed workshops over the past 6 months? It would be good for this screen to have some guidance too, such as:

1. If someone is marked has a no show marker and no attendance warning, admins should send one
2. If they have more no-shows after an attendance warning, it might time to consider a short suspension
3. If they keep not showing up, consider a long suspension

This should always be at the discretion of the chapter admin so just some lightweight guidance would do.

When dealing with no-shows, is it important to identify whether the chapters they've no-showed at are administed by the admin? For example, if you have someone who attends Cambridge and Oxford and only has no-shows with Cambridge, would it be useful for both chapters to know that? Cambridge may want to take action but not Oxford.

---

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
I've noticed in the new view we don't show what the student worked on in the workshops, this was often something I used before chatting with people so it would be good to have it added back in somehow.
