### ISSUE TITLE
Add social link to youtube in footer

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1504]
## Description of the issue 📄

There is no link on our website to out youtube channel. Add a social link to youtube in our footer https://www.youtube.com/channel/UCEYz232agE47GHUq8wneBCA

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by poly4concept** [comment]
I claim this issue and want to start working on it

**Comment by KimberleyCook** [comment]
@poly4concept please do :)

**Comment by poly4concept** [comment]
Hello! I really wanted to contribute to this project, but I got stuck when I want to install docker on my system. My current system version can't install docker and therefore I'm unable to have the project running locally on my computer. I hope to get it updated soon. So I'm sorry not to have contributed yet

**Comment by jalencheng** [comment]
Hi may i have a chance to work on this issue?

**Comment by matyikriszta** [comment]
@jalencheng yes, please do

**Comment by msantamaria86** [comment]
would like to claim this if it hasn't been implemented

**Comment by KimberleyCook** [comment]
@msantamaria86 please do

**Comment by rickr** [comment]
Good Morning - I'd like to take this for hacktobersfest. Do you mind adding the hacktoberfest topic to the repo as well?

**Comment by tacoelho** [comment]
Did it https://github.com/codebar/planner/pull/1644
