### ISSUE TITLE
Application Error when accessing admin area of an event

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1551]
## Description of the issue 📄
When trying to access the admin area of a single event (i.e panel event) I get an application error.

## Screenshots 📷
![Screenshot 2021-05-25 at 11 06 48](https://user-images.githubusercontent.com/2683270/119471178-f4f22a80-bd40-11eb-8cae-5b54e1bea131.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
This was related to running out of database connections which has also affected other areas of the app. Closing as it should now be resolves as I've upgraded our plan, but if you notice this problem again please feel free to reopen the issue and add a note.
