### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by brunogirin** [codebar/planner#1560]
## Description of the issue 📄
I get an error when I click the "sign-in" button. It goes to the `https://codebar.io/dashboard` URL and gives me an error.

## Screenshots 📷
![Screenshot 2021-06-08 at 19-45-42 We're sorry, but something went wrong (500)](https://user-images.githubusercontent.com/216028/121240583-67f7b700-c892-11eb-8032-243a58601533.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by brunogirin** [comment]
Refreshing the page works so it might have been temporary.

**Comment by despo** [comment]
This was related to running out of database connections which has also affected other areas of the app. Closing as it should now be resolves as I've upgraded our plan, but if you notice this problem again please feel free to reopen the issue and add a note.
