### ISSUE TITLE
Add what happens if you breach the code of conduct

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1569]
## Description of the issue 📄

Our code of conduct does not mention what happens if you breach it. This doc [here](https://docs.google.com/document/d/1Af2bob9sQ7KodHbIdjPUsHJedlvKtAFERN1Q_o22PIo/edit?usp=sharing) needs implementing. 

My initial thought is to create a new page on the codebar website and add it as a link somewhere in the current code of conduct. But open to other options?

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@KimberleyCook can this issue be closed now that Breach of CoC page is live on the site?
