### ISSUE TITLE
An event page with no host location (virtual event) doesn't need a map

### ISSUE THREAD

**Issue by harry-wood** [codebar/planner#1613]
## Description of the issue 📄

If an event is virtual like [this](https://codebar.io/events/uncodebar-7-day-1 ) we get a zoomed out map of the whole world. The "host" is "codebar". 

In these cases there's no need to show a map. And maybe a message like  _"No venue location. Virtual event"_  there would make it clearer.

## Screenshots 📷

<img width="600" alt="Screenshot 2021-09-10 at 11 32 26" src="https://user-images.githubusercontent.com/227525/132841291-5c25af59-f035-482a-a10b-efef94e2b8fc.png">

## Steps to fix 🛠

Investigate. How's a vitual event represented?

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
@harry-wood Thanks for creating this issue.

I think we could go a little further and in the admin area have an option that says "virtual" which will mean no need to add a location/sponsor and then the above text will show.

**Comment by matyikriszta** [comment]
@harry-wood there is currently no way to mark an event as virtual, as @KimberleyCook said we could extend the event model with a virtual field (similarly to how it works with workshops).

**Comment by matyikriszta** [comment]
This issue has been addressed by #1798
