### ISSUE TITLE
Black blobs on attendee page

### ISSUE THREAD

**Issue by brunogirin** [codebar/planner#1662]
## Description of the issue 📄
I opened an attendee page to check attendance records and there is a list of actions taken with black blobs on it. This is on Firefox 93 on Windows.

## Screenshots 📷
![Screenshot 2021-10-27 at 15-26-41 codebar](https://user-images.githubusercontent.com/216028/139086452-9b8a0012-1dbf-4830-9fca-131ffcd24371.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
All fixed 🎉
