### ISSUE TITLE
Not possible to add a coach to feedback, but coach is required

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/planner#1665]
## Description of the issue 📄
When a student is attempting to give feedback about a coaches performance the coaches look up is not working.
<s>The coaches name is a required field
If a student can not remember the coaches name, they would be unable to leave feedback.</s>

## Screenshots 📷
The student in this video is attempting to find a coach called "liska"
https://user-images.githubusercontent.com/4013283/140178102-b0377f58-56d8-4d14-b7b3-fcabd6230151.mp4

## Steps to fix 🛠
I don't know

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by gnclmorais** [comment]
Thanks for raising this!

Which path should we take, @KimberleyCook? Make the coach not required (i.e. make it optional)? Keep it required but allow any text input (e.g. `It ended with Smith`)?

**Comment by KimberleyCook** [comment]
Great question @gnclmorais, I think your suggestion of making the coach field optional is a good way forward

**Comment by despo** [comment]
The coach field is already optiona (you can see that by looking at existing feedback as there are a number of entries without the coach being specified), so if there are any issues with leaving feedback without selecting a coach I wonder if they may be related to the the switch to bootstrap.

**Comment by despo** [comment]
In relation to this I can see that the last piece of feedback we had was on the 1st of October so It looks like something  broke this page when bootstrap was merged.

**Comment by gnclmorais** [comment]
I have a fix for this, I’ll put it online this week and give you a rundown of the issue(s). I’m just trying to resolve a quirky 404 image issue with Capybara…

**Comment by gnclmorais** [comment]
If you want to know more about the issues I ran into while going down this rabbit hole, read on: https://github.com/codebar/planner/pull/1672
