### ISSUE TITLE
Hide RSVP buttons if the event is in the past

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1703]
## Description of the issue 📄

Currently you can RSVP to past "Events"

## Screenshots 📷
![screencapture-codebar-io-events-speedrunning-web-development-with-anvil-2022-01-19-14_18_36](https://user-images.githubusercontent.com/2683270/150138642-d93b751f-4c1d-45e9-aae1-d64bb3e4f89c.png)

## Steps to fix 🛠

Update some of the logic in this file `app/views/events/_event_actions.html.haml`

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by joaoguiIherme** [comment]
Hi, i would like to claim this issue.

**Comment by KimberleyCook** [comment]
Hey @joaoguiIherme please do :)
