### ISSUE TITLE
The application should be able to support multiple languages

### ISSUE THREAD

**Issue by despo** [codebar/planner#173]
this involves mostly moving all the text in config/locales/en.yml

**Comment by Unicornelia** [comment]
I will add some translations in German, let me know if somebody already started working on this.

**Comment by despo** [comment]
Support for multiple languages has now been merged in 👍 
Can we close this one @matyikriszta and add individual tasks for areas we would like translated?

**Comment by matyikriszta** [comment]
@despo yes, I will close this issue. @Unicornelia I will create a new ticket for the German translation and assign it to you.

**Comment by revolunet** [comment]
Hi!

We didnt make it in Paris, but we have some crowdsourced CoC translation available here : https://github.com/codebar/paris/blob/master/code-of-conduct.md

happy to help for the FR translations !

**Comment by Unicornelia** [comment]
Sounds good, thanks! I might ask some details as the whole repo is new to me still but im defo keen :)
