### ISSUE TITLE
Can't edit sponsor description

### ISSUE THREAD

**Issue by hellenward** [codebar/planner#1747]
## Description of the issue 📄
When I go to a sponsor as an admin and click edit, put something new in the description field and click save changes, the changes do not show up in the description field when the page re-loads (it just says 'No description provided').  I can't see any errors in the console or network tab when I do this, so I'm not sure exactly what's causing the issue.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by aq-simei** [comment]
I would like to try this one, can I get the issue?

**Comment by aq-simei** [comment]
I would like to try to solve this one, can I get the assign?

**Comment by hellenward** [comment]
> Hi @hellenward, I would like to try to solve this issue, can I get the assign?

Hi, sorry I'm not sure how to assign this to you

**Comment by matyikriszta** [comment]
This issue has been fixed by #1793
