### ISSUE TITLE
Add paragraph break or markdown support for sponsor description and direction fields

### ISSUE THREAD

**Issue by brunogirin** [codebar/planner#1769]
## Description of the issue 📄

Sponsor fields like description and directions can potentially take large amounts of text as those can be complex. At present, there is no way to format the text and all carriage returns in the text are ignored. Options for improvements:
- Transform double carriage returns into a paragraph break
- Fully support markdown

## Screenshots 📷

The text as entered in the field for directions with several options:

![Screenshot 2022-06-22 154512](https://user-images.githubusercontent.com/216028/175059624-ae8d0475-239c-4565-8bf1-b36898c984d2.png)

The same text as displayed in the sponsor page is more difficult to read:

![Screenshot 2022-06-22 154442](https://user-images.githubusercontent.com/216028/175059768-251f8c5b-1157-4011-9e90-ae5ff7541781.png)

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [x] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@brunogirin for some reason I can't tag you in it but I opened a PR that addresses this issue here: https://github.com/codebar/planner/pull/1830
