### ISSUE TITLE
Waitlist button alignment

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1779]
## Description of the issue 📄

The alignment of these buttons for waitlist members is funky

![Screenshot 2022-07-08 at 13 34 26](https://user-images.githubusercontent.com/2683270/177984784-9c9744f1-32df-4f5e-b234-dc66aee98557.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@KimberleyCook is this on the workshop page?

**Comment by KimberleyCook** [comment]
@matyikriszta yeah

**Comment by matyikriszta** [comment]
@KimberleyCook this has been fixed in the latest code that's on staging

<img width="776" alt="Screenshot 2022-08-20 at 6 15 36 pm" src="https://user-images.githubusercontent.com/5873816/185771296-0e90d3a5-3917-4602-b225-8e58f4873005.png">

**Comment by KimberleyCook** [comment]
Ok, seems to be fixed now
