### ISSUE TITLE
[Event] Remove mention of student and coach for email invite = general invite

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1797]
## Description of the issue 📄
When sending out invites for an event you receive an invite as a student or a coach. However, some events do not need students and/or coaches and are open to everyone. So we need an invite option that invites everyone regardless of whether they are a student or coach.

## Steps to fix 🛠
- New checkbox option in the admin area to invite everyone regardless of coach or student
- New version of the invite email that removes all mention of being invited as a student or coach, and is a general invite.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by jhackett1** [comment]
not sure i understand this one.

in the form at `/admin/event/new`, it says:

> Optionally, specify if invitations should only be sent to students or coaches (ex. a CV workshop targeted toward students may not need invites sent to the entire coach listserv) If left blank, all subscribers to a chapter will be invited via email

which seems to imply this functionality already exists.

additionally, the `app/views/event_invitation_mailer/invite_student.html.haml` view does not contain any mention of being a student or a coach.

assuming this all works, what needs to be done on top of it?
