### ISSUE TITLE
Update my Twitter handle under coaches page

### ISSUE THREAD

**Issue by sl4m** [codebar/planner#183]
Hi, this is more data related. Can I get my Twitter handle updated. It should be @skim.

Thanks!
skim

**Comment by despo** [comment]
@sl4m if you logging and access profile from the left hand menu - or http://codebar.io/profile -  you should be able to update it on your own.

**Comment by sl4m** [comment]
Thanks @despo! I didn't know about the profile endpoint. Cheers!
