### ISSUE TITLE
Waiting list not prioritised to attendances through website

### ISSUE THREAD

**Issue by heruku** [codebar/planner#184]
Today I was able to sign up for an event through the website even though @christopgockel was on the waiting list. He didn't receive an email about an opening and is presumably still on the waiting list. I assume people on the waiting list should be prioritised when a spot opens up.

I'm not sure how the waiting list works. Is there a background job to send emails out to people on the waiting list if there are openings?

**Comment by despo** [comment]
When someone changes their attendance the next waiting list spot is allocated from the controller - https://github.com/codebar/planner/blob/90488d5cbfa9d8e6dc6acb7a2567bfb37da6374b/app/controllers/concerns/invitation_controller_concerns.rb#L30

However, if an admin updates someone's attendance then it's not.
https://github.com/codebar/planner/blob/90488d5cbfa9d8e6dc6acb7a2567bfb37da6374b/app/controllers/admin/invitation_controller.rb#L28

**Comment by heruku** [comment]
Thanks for clearing it up.

Is this desired behaviour or should admin cancelling also allocate a waiting list spot?

**Comment by despo** [comment]
@heruku no, it was just missed. The admin cancelling should also allocate a spot - but only if this condition is met https://github.com/codebar/planner/blob/90488d5cbfa9d8e6dc6acb7a2567bfb37da6374b/app/controllers/concerns/invitation_controller_concerns.rb#L31 as most people can't make it without a couple of hours notice.

**Comment by heruku** [comment]
I'll take a stab at it.

**Comment by creature** [comment]
As discussed in person, this will also be the case if someone [declines an invite from the web interface](https://github.com/codebar/planner/blob/a01c4b219b30a17476766345b9d91b2888e44f91/app/controllers/workshops_controller.rb#L48-L56).
