### ISSUE TITLE
Broken link in the Eligibility Criteria section of the student guide

### ISSUE THREAD

**Issue by camillef** [codebar/planner#1856]
## Description of the issue 📄

The link "underrepresented ethnic groups in tech" in the [Eligibility Criteria section of the student guide](https://codebar.io/student-guide#eligibility) leads to a [404 page](http://sciencecampaign.org.uk/CaSEDiversityinSTEMreport2014.pdf).

## Screenshots 📷

![Screenshot 2023-03-17 at 15 09 10](https://user-images.githubusercontent.com/5774647/225944547-0331e80f-f602-45c6-b201-85fe79b0002e.png)

## Steps to fix 🛠

Replace the link with a working one. 

I'm not sure if this is the same report that was originally linked, but I have found this CaSE Diversity in STEM report from 2014 that has a working URL: https://www.sciencecentres.org.uk/documents/360/casediversityinstemreport2014.pdf

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by camillef** [comment]
Happy to raise a PR to fix, but might also be a nice beginner issue for someone to pick up!

**Comment by enochval** [comment]
@camillef I will love to fix this issue, let me know if I can proceed. thanks

**Comment by matyikriszta** [comment]
@enochval please do

**Comment by enochval** [comment]
@matyikriszta I've attempted to fix this issue, kindly review my pull request. cheers.

**Comment by matyikriszta** [comment]
Fixed in #1865
