### ISSUE TITLE
LinkedIn social is missing from website footer

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1866]
## Description of the issue 📄
We've started being more active on LinkedIn and the URL for it is missing from our wbesite footer.

URL -> https://www.linkedin.com/company/codebarcommunity/

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by enochval** [comment]
@KimberleyCook can I work on this, and can you assign this task to me?

**Comment by KimberleyCook** [comment]
@enochval done, thank you very much for picking it up

**Comment by enochval** [comment]
@KimberleyCook my pleasure, I am glad to contribute.

**Comment by enochval** [comment]
@KimberleyCook I've made this update, kindly review it, thanks

**Comment by KimberleyCook** [comment]
Thank you so much @enochval for helping us, we really appreciate it.
