### ISSUE TITLE
Fresh project setup fails because of out of support base operating system

### ISSUE THREAD

**Issue by biggianteye** [codebar/planner#1869]
## Description of the issue 📄

When trying to run `./bin/dbuild` in a freshly checked out repo, it fails with this error:

```
failed to solve: process "/bin/sh -c curl -sL https://deb.nodesource.com/setup_12.x | bash -" did not complete successfully: exit code: 1
```

There is a deprecation warning about Node 12 earlier on in the output but this is a red herring. The problem arises from the fact that the node installation script first tries to update the list of available operating system packages.

<details>
<summary>Error output</summary>

```
#0 20.26 ## Installing the NodeSource Node.js 12.x repo...
#0 20.26
#0 20.27
#0 20.27 ## Populating apt-get cache...
#0 20.27
#0 20.27 + apt-get update
#0 22.52 Ign http://security.debian.org jessie/updates InRelease
#0 22.52 Ign http://deb.debian.org jessie InRelease
#0 22.54 Ign http://security.debian.org jessie/updates Release.gpg
#0 22.57 Ign http://security.debian.org jessie/updates Release
#0 22.57 Ign http://deb.debian.org jessie-updates InRelease
#0 22.61 Ign http://deb.debian.org jessie Release.gpg
#0 22.63 Err http://security.debian.org jessie/updates/main arm64 Packages
#0 22.63
#0 22.66 Ign http://deb.debian.org jessie-updates Release.gpg
#0 22.67 Err http://security.debian.org jessie/updates/main arm64 Packages
#0 22.67
#0 22.68 Ign http://deb.debian.org jessie Release
#0 22.71 Ign http://deb.debian.org jessie-updates Release
#0 22.71 Err http://security.debian.org jessie/updates/main arm64 Packages
#0 22.71
#0 22.76 Err http://security.debian.org jessie/updates/main arm64 Packages
#0 22.76
#0 22.80 Err http://security.debian.org jessie/updates/main arm64 Packages
#0 22.80   404  Not Found [IP: 151.101.66.132 80]
#0 23.50 Err http://deb.debian.org jessie/main arm64 Packages
#0 23.50   404  Not Found
#0 23.60 Err http://deb.debian.org jessie-updates/main arm64 Packages
#0 23.60   404  Not Found
#0 23.61 W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-arm64/Packages  404  Not Found [IP: 151.101.66.132 80]
#0 23.61
#0 23.61 W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-arm64/Packages  404  Not Found
#0 23.61
#0 23.61 W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-arm64/Packages  404  Not Found
#0 23.61
#0 23.61 E: Some index files failed to download. They have been ignored, or old ones used instead.
#0 23.61 Error executing command, exiting
------
failed to solve: process "/bin/sh -c curl -sL https://deb.nodesource.com/setup_12.x | bash -" did not complete successfully: exit code: 1
```
</details>

The docker image used by the project is built on top of the [`ruby:2.4.2`](https://hub.docker.com/layers/library/ruby/2.4.2/images/sha256-2a867526d4724cf92c845c70b67e53d61e0a76e324a6051262c3731ddcc2f568?context=explore) image which is now 6 years old. This uses Debian Jessie which reached [end of Long Term Support in June 2020](https://www.debian.org/releases/jessie/) and now the package repositories return a 404 as seen in the output above.

This is not a good experience for anyone new wanting to contribute to the project.

## Screenshots 📷
n/a

## Steps to fix 🛠

The fix would be to upgrade the base operating system. I don't know what the project's needs are in terms of Ruby versions and underlying operating system, but here are some options:

- Latest 2.4.x: [`ruby:2.4.10`](https://hub.docker.com/layers/library/ruby/2.4.10/images/sha256-def31cac5bbd53f6b00ec3e9c8a51cb71cb7c9e846889fc4a1f1617bbcbbdf3b?context=explore) &rarr; Debian 10.3
- Latest 2.x: [`ruby:2.7.8`](https://hub.docker.com/layers/library/ruby/2.7.8/images/sha256-f4420f957a9b4fae91a8d8c7fab8ba43e5a76bd640c87cb2b20ef669039e1319?context=explore) &rarr; Debian 11.7

According to the [Debian releases page](https://www.debian.org/releases/):
- Debian 11 (bullseye) — current _oldstable_ release
- Debian 10 (buster) — current _oldoldstable_ release, under LTS support

If there is going to be effort spent on upgrading, it would be worth spending it on something more recent than those options.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [x] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by biggianteye** [comment]
I bumped up the docker image to `ruby:2.4.10` and the build succeeded. Though as mentioned, this is a temporary measure rather than a proper fix.

There were a couple of test failures like this one but I suspect they are transient problems unrelated to the version bump.

```
1) Admin managing members Admin managing members can unsubscribe a member from group
Failure/Error: visit admin_member_path(member)

Selenium::WebDriver::Error::UnknownError:
  unknown error: Chrome failed to start: crashed.
    (chrome not reachable)
    (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by gnclmorais** [comment]
I think I was able to (temporarily) solve this at https://github.com/codebar/planner/pull/1874.

**Comment by gnclmorais** [comment]
I worked on this https://github.com/codebar/planner/pull/1874, but it seems @asideofcode-dev fixed it marvellously as a consequence with https://github.com/codebar/planner/pull/1882! Great job :)
