### ISSUE TITLE
modernizr is nowhere to be found

### ISSUE THREAD

**Issue by asideofcode-dev** [codebar/planner#1880]
## Description of the issue 📄

There's an include tag for `modernizr` in the application view template.

https://github.com/codebar/planner/blob/2d4726b292270ed1f238b1debbb59ab95d9e2d31/app/views/layouts/application.html.haml#L13

Perhaps this used to be available in some earlier version of some gem, but now it's nowhere to be found. If you run the site from scratch you'll notice a 404 for that particular resource in the Javascript console.

I'm a little bit confused about how this file is available in production, though I suspect caching might be to blame.

I also noticed this warning in the logs:
```
 (called from _app_views_layouts_application_html_haml__4168757267524813890_60640 at /planner/app/views/layouts/application.html.haml:13)
DEPRECATION WARNING: The asset "vendor/modernizr.js" is not present in the asset pipeline.
Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
```

## Steps to fix 🛠

Not sure if necessary. Might be a good time to be rid of it.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@asideofcode-dev if I remember correctly an older version of Foundation we were using required modernizer which is why that line is there. We have now migrated to Bootstrap which does not rely on modernizer (or if it does under the hood it's bundled with the gem and does not have to be imported separately) so this could be removed.
