### ISSUE TITLE
"Selecting a member to RSVP" doesn't update the page without reload

### ISSUE THREAD

**Issue by asideofcode-dev** [codebar/planner#1883]
## Description of the issue 📄

For invitation management as an admin, "Selecting a member to RSVP" doesn't update the page without reload. 

## Screenshots 📷

<img width="610" alt="image" src="https://github.com/codebar/planner/assets/133222359/67f14da8-8dc8-4a6d-87e8-714248745fa5">

## Steps to fix 🛠

This is purely because the selector used for the event listener for `ajax:success` is specific to anchor elements (e.g. the button to cancel an RSVP) and neglects the select element.

https://github.com/codebar/planner/blob/2d4726b292270ed1f238b1debbb59ab95d9e2d31/app/assets/javascripts/invitations.js#L2

A more appropriate selector would be `#invitations [data-remote]`.
## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by gnclmorais** [comment]
Actually, this action has been _erring_ since… forever? I was never able to manually RSVP someone (for example, when an extra coach shows up and ends up staying and coaching a student). Was this found & fixed as well, @asideofcode-dev?

**Comment by asideofcode-dev** [comment]
@gnclmorais Yup, found and fixed :)

**Comment by gnclmorais** [comment]
![YUSSSSSæ!](https://media.tenor.com/Vy7mmYAqqREAAAAC/yus-adventure-time.gif)

**Comment by KimberleyCook** [comment]
Woooooooo 🎉 thanks @asideofcode-dev
