### ISSUE TITLE
Large logos can make the invite email hard to use

### ISSUE THREAD

**Issue by creature** [codebar/planner#189]
If we have a large sponsor logo included in the [invitation email](https://github.com/codebar/planner/blob/master/app/views/session_invitation_mailer/invite_coach.html.haml), the workshop details and the RSVP button can get pushed way off to the right side. That's hard to notice, and may even be hidden by some email clients - resulting in people getting an email where there's no RSVP button. 

Adding a max-width to this email should help with that.

**Comment by despo** [comment]
i think we may be able to use the thumbnail version of it.
