### ISSUE TITLE
Improve the ranking of coaches on the coaches page

### ISSUE THREAD

**Issue by creature** [codebar/planner#191]
At the moment, the [Codebar coaches page](http://codebar.io/coaches) shows everyone who's ever come to an event. But this has some problems, such as:
- People who haven't attended for months may still be at the top of the page, because they attended a lot in the past.
- If someone is trying to figure out who they talked to at the last meeting, they might be all the way at the bottom of the page because they've only attended a few times.

Some ideas: 
- Splitting the page up into two sections; something like "attended recently" (if they've come to an event in the last month) and "previous coaches" (people we haven't seen for a while).
- Some kind of decaying algorithm, where people get more "points" for attending an event more recently.
- A random selection (changing the page to a "Some of our coaches") - maybe with more chance of someone showing up if they've come to Codebar a lot.
- Something else?

**Comment by christophgockel** [comment]
I thought I give it a try, and picked up this feature to add some decay based on the last attendance of a coach to the ranking.

So coaches that have a high number of attendances but haven't shown up for 3+ months won't be ranked higher than coaches that have a smaller number of attendances but attended more frequently.

The code for sorting the data works fine now, but I can't yet really figure out from where to pull the data I need.
There's the `SessionInvitation` model and currently the coaches list is sorted by `SessionInvitation.to_coaches.attended.by_member.count(:member_id)` which returns the overall amount of attendances per coach.

The data structure I'd like to have looks like the following:
```
{
  <coach_id_1>: {
    attendances: 42,
    weeks_since_last_attendance: 5
  },
  <coach_id_2>: {
    ...
  }
}
```
Is my assumption correct, that I'd have to go through the `SessionInvitation`s where a coach attendended (i.e. `attended = true`), then "join" `Session` based on `session_invitation.sessions_id` to get the session's `date_and_time` (given the fact, that I order everything correctly and such...)?

Or is there an easier way for me to get a date where a coach has been attended a session the last time?

**Comment by despo** [comment]
In short, I don't think there is a better way to do that. 

But on the road so will have a better look when I get back home later.

**Comment by alexanderkustov** [comment]
@deniseyu mind if i take that approach that @creature mentioned and come up with something beatiful?
