### ISSUE TITLE
Deprecated Node install script when building Docker image

### ISSUE THREAD

**Issue by CodeHex** [codebar/planner#1926]
## Description of the issue 📄
Running the line
`curl -fsSL https://deb.nodesource.com/setup_20.x` in the Dockerfile comes up with a script deprecation warning and freezes the build for 60 secs. Looking at the contents of the scrpt, the warning says

```
This script, located at ${bold}https://deb.nodesource.com/setup_X${normal}, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource ${bold}distributions${normal} Github and follow the
  instructions to migrate your repo.
  ${underline}${green}${bold}https://github.com/nodesource/distributions${normal}

  The ${bold}NodeSource${normal} Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  ${underline}${green}${bold}https://github.com/nodesource/distributions${normal}


                          ${underline}${bold}${yellow}SCRIPT DEPRECATION WARNING${normal}
"

        echo
        echo "${cyan}${bold}TO AVOID THIS WAIT MIGRATE THE SCRIPT${normal}"
        echo "Continuing in 60 seconds (press Ctrl-C to abort) ..."
        echo
        sleep 60
```
## Steps to fix 🛠
Replace using the script with the [updated commands](https://github.com/nodesource/distributions/blob/master/README.md#debian-and-ubuntu-based-distributions) described in the nodesource repo readme.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [x] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by CodeHex** [comment]
Hi 👋, I'm happy to have a crack at fixing this if its ok for me to work on it

**Comment by asideofcode-dev** [comment]
@CodeHex Thanks for creating the issue. It's a recent deprecation.

Please go ahead. Happy to review the work

**Comment by matyikriszta** [comment]
As of 26 Jul 2024 the install scripts are working again. Closing this issue.
