### ISSUE TITLE
Coaches webpage gives 404 when moving to next page

### ISSUE THREAD

**Issue by CodeHex** [codebar/planner#1928]
## Description of the issue 📄
On the `/coaches` route, clicking on either a number or `Next ->` on the paging control at the bottom of the page causes a 404. 

The URL displays `https://codebar.io/{:controller=>"dashboard", :action=>"wall_of_fame", :only_path=>true, :page=>2}` which seems odd.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [x] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by CodeHex** [comment]
I was thinking of looking at this by adding more coaches in the local database, but I haven't used Postgres before and my Rails knowledge is a lttle rusty, so might take a little time. Happy to give it a go if its free?

**Comment by matyikriszta** [comment]
@CodeHex go for it!

**Comment by CodeHex** [comment]
Interesting..., looks like the href for the link is being generated incorrectly e.g. 
```
<a class="next_page" aria-label="Next page" rel="next" href="{:controller=>&quot;admin/feedback&quot;, :action=>&quot;index&quot;, :only_path=>true, :page=>2}">Next →</a>
```

**Comment by CodeHex** [comment]
Its seems to be related to how `will_paginate` is rendering the links. I tested this monkey patch ([original here](https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers/action_view.rb#L108-L119)) which fixed it
```ruby
module WillPaginate
  module ActionView
    class LinkRenderer < ViewHelpers::LinkRenderer
      protected

      def url(page)
        @base_url_params ||= begin
          url_params = merge_get_params(default_url_params)
          url_params[:only_path] = true
          merge_optional_params(url_params)
        end

        url_params = @base_url_params.dup
        add_current_page_param(url_params, page)

        #@template.url_for(url_params)  - this line is producing a String version of url_params hash
        Rails.application.routes.url_helpers.url_for(url_params)
      end
    end
  end
end
```
The `@template.url_for` method used is defined in `actionview-7.0.6/lib/action_view/routing_url_for.rb` which seems to be taking the hash and just converting it into a String version. I think `@template` is the ActionView the control is on. The url_params hash that I'm testing with is `{:controller=>"admin/feedback", :action=>"index", :only_path=>true, :page=>2}`

**Comment by CodeHex** [comment]
Ok, getting somewhere, looks like its using this for the url
```shell
From: /planner/app/helpers/email_helper.rb:5 EmailHelper#full_url_for:

    4: def full_url_for(path)
 => 5:   "#{@host}#{path}"
    6: end
 ```
