### ISSUE TITLE
Change image storage back end from cloudinary to aws

### ISSUE THREAD

**Issue by despo** [codebar/planner#193]
This is urgent as we seem to have exceeded the cloudinary storage - and cannot justify paying so much for hosting images.

It doesnt need to be AWS but it must be a service that is cheap or free.

**Comment by barisbalic** [comment]
On this note, AWS free tier carries some constraints, like 20,000 GETs per month.  Depending on traffic you may want to work out if this will cover you.  Also I do not know if the free tier rolls over each year, the content says "for one year."

**Comment by knuxus** [comment]
What images do we have on our planning site except company logos and some faces? Anyway I can set you up a bucket for those, or for uploading next ones...

**Comment by despo** [comment]
@knuxus thanks but this is now sorted!
