### ISSUE TITLE
Followup with people who have stopped coming to Codebar.

### ISSUE THREAD

**Issue by creature** [codebar/planner#194]
If someone's come to Codebar a few times and then they stop coming, we should email them and ask why. That way, we can find out about problems with the event & try to fix them. It should probably direct them to a feedback form - if we ask people to email us, then they might not be as honest as in an anonymous form.

I'd recommend an approach along these lines: 
- [ ] Set up a Google form to capture their feedback
- [ ] Add a field to the member with a timestamp so we only send them a single reminder
- [ ] Add a new mailer method & template with a link to the form
- [ ] Add a Rake task that finds members who have attended at least 5 times, and haven't attended in 2 months, and haven't ever been emailed before. Send them an email and update the new timestamp.

**Comment by despo** [comment]
Maybe restrict it to the last 4-6 months.

**Comment by deniseyu** [comment]
Closing this for now, can revisit in future if there is interest.
