### ISSUE TITLE
Coach feedback

### ISSUE THREAD

**Issue by despo** [codebar/planner#206]
Currently all attending students receive an email the day after a workshop asking them for feedback.

The student feedback is anonymous, however I'm not sure if this should apply to the coaches. Maybe optionally anonymous.

-----
Refactor and utilise existing feedback model to achieve this.

**Comment by notapatch** [comment]
A rake task runs everyday which checks for workshops that were completed the day before. The rake task puts the `Workshop` and `Member` information into a FeebackRequest object and calls `create`.

```ruby
# lib/tasks/feedback.rake - with logging removed
task request: :environment do
  workshops = Workshop.completed_since_yesterday
  workshops.each do |workshop|
    WorkshopInvitation.accepted.where(workshop: workshop, role: 'Student').map do |invitation|
      FeedbackRequest.create(member: invitation.member, workshop: workshop, submited: false)
    end
  end
end
```

`FeedbackRequest` adds a unique token to the the object which it saves along with the Workshop and Member information to the database. After the save an email, using `FeedbackRequestMailer.request_feeback`, is sent out which asks the Member to give feedback.

```ruby
# app/models/feedback_request.rb
class FeedbackRequest < ActiveRecord::Base
  ...
  validates :token, uniqueness: { case_sensitive: false }
   ...
  before_validation :set_token
  after_create :email

  private

  def set_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.where(token: random_token).exists?
    end
  end

  def email
    FeedbackRequestMailer.request_feedback(workshop, member, self).deliver_now
  end
end
```

The request_feedback email is a standard email with the exception of a link feedback controller using the token created in the FeedbackRequest.
```haml
# app/views/feedback_request_mailer/request_feedback.html.haml
.content
%table{ bgcolor: "#FFFFFF" }
  %tr
    %td
      %p
        =link_to "Submit feedback", full_url_for(feedback_url(@feedback_request.token)), class: 'btn'
```

feedback_url is routed to `FeedbackController#show` and uses the `FeedbackRequest` token to link the request to the Feedback. The show has a feedback form on it and behaves more like a `new` action than a show. 

```ruby
class FeedbackController < ApplicationController
  def show
    feedback_request = FeedbackRequest.find_by(token: params[:id], submited: false)

    if feedback_request.nil?
      flash[:notice] = I18n.t('messages.feedback_not_found')
      return redirect_to root_path
    end

    set_coaches(feedback_request.workshop)

    @workshop = feedback_request.workshop
    @feedback = Feedback.new
  end
 ...
```

The form submits to `submit_feedback_path` which routes to` feedback#submit`

```haml
= simple_form_for @feedback, url: submit_feedback_path(params[:id]), html: {method: "patch"} do |f|
  = f.hidden_field :token, :value => params[:id]
  = f.hidden_field :rating
  .row
    .large-6.columns
      %label.required
        %abbr(title='required') *
        =t('feedback_form.rating')
      .rating{:data => {:rating_max => 5 }}
  .row
    .large-6.columns
      = f.association :coach, collection: @coaches, label_method: :full_name, value_method: :id, label: t('feedback.coach')
  .row
    .large-6.columns
      = f.association :tutorial, label_method: :title, value_method: :id, label: t('feedback_form.tutorial'), include_blank: t('feedback_form.select_tutorial')
  .row
    .large-12.columns
      = f.input :request, label: t('feedback_form.request')
  .row
    .large-12.columns
      = f.input :suggestions, label: t('feedback_form.suggestions')
  .row
    .large-12.columns.text-right
      = f.submit 'Submit feedback', class: 'button round right'
```
The `Feedback#submit `acts more like a `Feedback#create` where the feedback information is passed to `Feedback.submit_feedback`

```ruby
# app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def submit
    if Feedback.submit_feedback(feedback_params, params[:id])
      flash[:notice] = I18n.t('messages.feedback_saved')

      redirect_to root_path
    else
      feedback_request = FeedbackRequest.find_by(token: params[:id], submited: false)
      set_coaches(feedback_request.workshop)

      @workshop = feedback_request.workshop
      @feedback = Feedback.new(feedback_params)
      @feedback.valid?

      flash[:alert] = @feedback.errors.full_messages.to_sentence
      render 'show'
    end
  end
```

Feedback.submit_feedback takes the student information and saves it back to the database changing the flag submited from false to true. The Feedback system is complete.

```ruby
# app/models/feedback.rb
class Feedback < ActiveRecord::Base
  ...
  def self.submit_feedback(params, token)
    return false unless feedback_request = FeedbackRequest.find_by(token: token)

    feedback = Feedback.new(params)
    feedback.workshop = feedback_request.workshop

    if feedback.valid? && !feedback_request.submited
      feedback_request.update(submited: true)
      feedback.save
    else
      false
    end
  end
end
```

**Comment by notapatch** [comment]
@despo - I don't know the admin section very well - I've only ever used the system as a coach.

When I look at the admin section of the feedback. I see the names of the users and their opinions. So we are not talking about complete anonymity. Is it anonymous in the sense that the feedback isn't given to anyone but the organiser? So the coach is left out the loop? 

_if_ you didn't want the coach feedback to be anonymous you would want it being sent to the Student? I'm guessing you'd want the organiser to view the feedback first?

### Menu => view feedback path: http://localhost:3000/admin/feedback 

![feedback admin](https://user-images.githubusercontent.com/1710795/83269890-a22e7300-a1bf-11ea-8ca0-891d65726775.png)

**Comment by despo** [comment]
@notapatch feedback is not associated with the user that submitted it so it is anonymous. Optionally, the coach name can be selected (which should be the name you are seeing) and this enables specific feedback to be dealt with if required from the organisers.

I think it would be good to also enable the coaches to submit it anonymously, as an option. Noone should feel that they might be judged for expressing their opinion which is why we kept it anonymous on the first place, but I can definitely see the benefits in named feedback too. In the past, feedback used to be available to verified coaches, minus the coach association details unless they were the coach, but unfortunately as people kept writing the coach name in the text area and we never got around to reviewing it we decided it was best to keep it only available to organisers as our intention was to improve things and not to put anyone potentially in a diffficult situation. Saying that the feedback we receive tends to be positive especially when coaches are attached to it.

However, the same applies to both parties so reusing the existing model and enabling an optional member/feedback owner association would be good.

Does this make sense?

**Comment by notapatch** [comment]
The anonymous makes sense. I should have looked harder before asking - but your real experience with the system was very helpful to get an idea about how it would be used. 

So looking at the organiser feedback (there seems to be a coach feedback index as well - but I'll cross that bridge later)

> However, the same applies to both parties so reusing the existing model and enabling an optional member/feedback owner association would be good.

So you would like it that the feedback would have an optional member association to the person who sent this but would otherwise remain the same? So the changes would be:

1. Feedbacks will still display the name which the feedback is going to, the feedbackee (see yellow box), but it could now be the coach or the student.
2. Optionally the person it is from, the feedbacker (see blue box), would be displayed who could be the coach or the student - 1

![feedback-item](https://user-images.githubusercontent.com/1710795/83291613-87202b00-a1e0-11ea-951c-8677f08d31af.png)

Anywhere near?

.1 - I hope I got the ee and er the right way around
