### ISSUE TITLE
Remove Docker support and reinstate local installation instructions

### ISSUE THREAD

**Issue by biggianteye** [codebar/planner#2099]
The README currently says to use Docker for development. This is a problem for a number of reasons:

- The current Docker support is out of date/incomplete.
  - I have tried to address one aspect here: https://github.com/codebar/planner/pull/1900
  - If you follow the current README instructions verbatim, you do not have a running system. There are further steps needed as per the conversation here: https://github.com/codebar/planner/pull/1882#issuecomment-2094351062
- The primary developers on the project do not use Docker.

All of the above means that it is both difficult for people to contribute to the project and also difficult for the project maintainers to easily assess contributions.

I propose that we do the following:
1. Reinstate the local installation steps as the way to develop on the project. These instructions are currently at https://github.com/codebar/planner/blob/master/native-installation-instructions.md
2. Bring the above document up to date.
3. Remove Docker support completely.

A variation of item 3 is to keep Docker but flag it as unsupported. I don't think this is a good idea though as it adds extra maintainer burden, even if unsupported.

Note that all of the above proposals do not need to be done in the same PR.

**Comment by matyikriszta** [comment]
@biggianteye fixed up the Docker installation in this PR: https://github.com/codebar/planner/pull/2103. The primary developers will move over using Docker in the future so we can keep the instructions etc. up to date. Ultimately it's an useful tool, in the past we were getting a lot of feedback that going through the native installation is too burdensome for some.

**Comment by matyikriszta** [comment]
Modernized and fixed Docker setup and instructions, closing this issue
