### ISSUE TITLE
Sponsor website links not working in admin interface

### ISSUE THREAD

**Issue by biggianteye** [codebar/planner#2152]
## Description of the issue 📄
Sponsor pages in the admin interface contain a link to the sponsor's website. These links do not work though. The link text is correct, but the link target points to `https://codebar.io/admin/sponsors/{:only_path=>true}`

## Screenshots 📷

<img width="264" alt="image" src="https://github.com/user-attachments/assets/2d23e4e4-759c-4271-b3af-0c8495b3c7e0" />

^ Correct link text, but broken link.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by HelenEBates** [comment]
I have some time to have a go at this, I have the project running locally, andI have created a sponsor

**Comment by Zelda-Cat** [comment]
I have created a new account to work on this, and opened a PR from my fork

**Comment by matyikriszta** [comment]
Addressed by #2156
