### ISSUE TITLE
remove attachment from course invitation email

### ISSUE THREAD

**Issue by despo** [codebar/planner#221]

**Comment by lpil** [comment]
Is this the calendar file?

**Comment by despo** [comment]
The old logo. Now we just link directly to it and don't need to have the attachment included in the email.

![screen shot 2015-05-15 at 14 14 10](https://cloud.githubusercontent.com/assets/159200/7653301/a102b266-fb0c-11e4-92b8-fad6f7f25f87.png)

**Comment by lpil** [comment]
Is this the student invitation? I don't seem to have it on mine.

**Comment by despo** [comment]
It's the course invitation. These are only emailed out to students, it's a different type of event.

https://github.com/codebar/planner/blob/master/app/mailers/course_invitation_mailer.rb#L11

**Comment by lpil** [comment]
Thanks, not familiar with the lingo we're using here. :)
