### ISSUE TITLE
Some people unfamiliar with web icons don't know how to login or signup

### ISSUE THREAD

**Issue by knuxus** [codebar/planner#228]
![Login icon](https://cldup.com/FWkKRl62NX-3000x3000.png)

This is our current login/signup icon, for anyone looking for a button to enroll I think it's even hard to explain if this is a button of a door opening, or an arrow entering a box.

Should we change to something more obvious? What are your thoughts?

**Comment by despo** [comment]
i added some text for now, 'sign in' and 'sign out'.

**Comment by knuxus** [comment]
Looking great
