### ISSUE TITLE
Enable organisers to set rsvp_close_time

### ISSUE THREAD

**Issue by despo** [codebar/planner#238]
This controls what time people can RSVP until.

https://github.com/codebar/planner/blob/master/app/models/sessions.rb#L59

**Comment by docljn** [comment]
Hello @despo and @deniseyu :  I've been unable to follow the link above (404 error). Is this still an issue you would like to see worked on?

**Comment by biggianteye** [comment]
`sessions.rb` was renamed to `workshop.rb` in 40829a108ad6c0cf7ccac1498e4524ac9d518e9a

https://github.com/codebar/planner/blob/master/app/models/workshop.rb

**Comment by despo** [comment]
Closing in favor of #1237
