### ISSUE TITLE
Why is production running sqlite3?

### ISSUE THREAD

**Issue by pedromaltez** [codebar/planner#241]
`config/database.yml` seems to be completely backwards to what tends to happen. sqlite for development and postgresql for production. Just wondering, of course.

**Comment by despo** [comment]
That is just left over code. It's not being utilised as we are on heroku.

**Comment by lpil** [comment]
> sqlite for development and postgresql for production.

You really should use the same DB in dev and prod!

sqlite is surprisingly performant if you're only doing reads. The sqlite site runs off sqlite :)

**Comment by despo** [comment]
@pedromaltez we do only us PG. The production entry in the config file is not utilised/needed.

**Comment by pedromaltez** [comment]
Thanks @despo! Might sound daft, so pardon my ignorance, but how does rails know where to look for the database in Heroku? Shouldn't the database location be described somewhere? At the very least the production environment should specify postgresql, according to https://devcenter.heroku.com/articles/getting-started-with-rails4#write-your-app.

**Comment by despo** [comment]
I think that is referring to the development environment - as it says right above the code block.

> The development section of your config/database.yml file should look something like this

Heroku doesn't support sqlite and knows that we are using postgres because the pg gem is used. The connection details are retrieved from the `DATABASE_URL`.

**Comment by pedromaltez** [comment]
@despo oh ok, great. :D thanks! I'll remove the dead bit of configuration in a PR in a sec - and some now irrelevant information on the readme too.
