### ISSUE TITLE
Do not call mailchimp API on development

### ISSUE THREAD

**Issue by pedromaltez** [codebar/planner#243]
>Mailchimp is not really required for development - it's called when subscribing and unsubscribing to different groups to update our mailing lists. I missed this because I was using my own account when initially developing to verify.

>https://github.com/codebar/planner/blob/5271b16cbc9b56b7eeab62d2dc9a1860e2b89ce8/lib/services/mailing_list.rb#L9 - this should probably change to reflect that, I should add an issue.

— @despo, [#242]

I took the liberty of creating the issue myself. Hope you don't mind!

[#242]: https://github.com/codebar/planner/issues/242#issuecomment-102443714

**Comment by despo** [comment]
:+1:
