### ISSUE TITLE
Add eligibility criteria confirmation attribute to every student

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#246]
As a student
When I RSVP to the next workshop via an email invitation or on the website
Then I should be redirected to a page containing the eligibility criteria
And prompted to provide a digital signature affirming that I meet the eligibility criteria

When I indicate that I do meet the eligibility criteria
Then I will be redirected to the RSVP confirmation page

If I indicate that I do not meet the eligibility criteria
Then I will receive a pop-up confirmation alert
And, on clicking 'yes', will be redirected to a page explaining why the eligibility criteria exist
And I will no longer receive invitations to RSVP as a student

**Comment by pedromaltez** [comment]
Please no 'pop-up alerts', but otherwise sounds good.

**Comment by deniseyu** [comment]
Hahah fair enough :-)

**Comment by margOnline** [comment]
@deniseyu I can have a look at this. Presumably, a student should only need to do this once if eligibility is confirmed?
