### ISSUE TITLE
Add an identifying gender and preferred pronoun field to new user sign-up form

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#248]
For example can be radio buttons: Female, Male, _____ (with custom input)

If 'Male' is selected, page will display polite message asking for verification of meeting eligibility criteria.

**Comment by jkbits1** [comment]
Does this have any issues relating to LGBT and ethnic minority attendees?

**Comment by pedromaltez** [comment]
How do you intend to verify someone's sexuality?

**Comment by deniseyu** [comment]
Sorry poor phrasing - can't verify it, what I meant was ask for a digital signature or checkbox to state that new attendee meets eligibility criteria.

@jkbits1 it is related, but it also is a way to make non-binary individuals feel more included if we allow for preferred pronoun usage.

**Comment by jkbits1** [comment]
@deniseyu yes, I am completely for supporting non-binary individuals and allowing for choice of pronoun.

I probably wasn't clear that I was thinking about your second sentence. If we ask people to clarify their reason for meeting the acceptance criteria, it can be uncomfortable for people to do that. If someone is lgbt or part of an ethnic minority, we should consider what statement or action they might have to state/perform carefully in advance.


I wonder if the transcode organizers and those of other groups could offer us some advice, and share experience of what potential attendees might feel is suitable.

**Comment by deniseyu** [comment]
@jkbits1 have discussed w organizers, and we decided that instead of asking for gender, we will just state the eligibility criteria as static text. Below we have a text box that asks user to retype sentence like "By digitally signing this document, I acknowledge that I meet one or more of the codebar eligibility criteria." and an optional field for elaboration about which one they meet, if a student chooses to disclose.

**Comment by jkbits1** [comment]
@deniseyu that all sounds great. As organisers setting up the site, etc and and having to be aware of so many different aspects of codebar, it can then be very hard sometimes to put ourselves in the position of a specific person and look at things through their perspective, and to see the site as they might. Giving people the option to say more if they wish, is an excellent decision - we will probably learn a lot from that.

**Comment by deniseyu** [comment]
Closed because preferred pronoun feature addresses this sufficiently :-)
