### ISSUE TITLE
donate.codebar.io should always use HTTPS

### ISSUE THREAD

**Issue by passy** [codebar/planner#251]
Hey,

I don't know if this has been brought up before but I noticed that http://donate.codebar.io/ is not served via HTTPS if you go there from http://codebar.io. Thus, it would be possible for an attacker to run a Person-In-The-Middle attack against the site and collect the credit card information or use their own stripe credentials.

Since HTTPS is already set up, it should make sure that at least for this page it never uses the plain HTTP version. It would be even better to use [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) headers to make sure the browser remembers the certificate and won't allow unencrypted/unauthenticated access. That could either be done for just the subdomain or the entire website.

**Comment by matyikriszta** [comment]
Hey,

This is a really good point, we're looking into implementing this as soon as possible. Thanks for raising it :)

K

**Comment by despo** [comment]
This is done!

**Comment by passy** [comment]
Woo! Well done.
