### ISSUE TITLE
Random spot allocation for workshops

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#254]
When coach and student invitations go out for each workshop, instead of RSVPing directly to the event, they should be invited to "Request a spot". They can also be invited to indicate whether they would like to join the waitlist in the event they are not allocated a spot.

At 9PM on that evening, invitations will be allocated. If (Number of People Requesting Slots) > Capacity, then slots will be randomly assigned. Otherwise, everyone will receive a slot.

**Comment by asuffield** [comment]
I'm taking a shot at this one.
