### ISSUE TITLE
Re-organise the sponsors page

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#278]
We want to set up a tiered sponsorship model, similar to Rails Girls: http://railsgirlssummerofcode.org/

The categories can be something like:
- Venue Sponsors: companies that have donated venue space & food
- Bronze Sponsors: companies that have donated venue space, food, and <= £500 (incl. event sponsorship)
- Silver Sponsors: companies that have donated venue space, food, and <= £1000 (incl. event sponsorship)
- Gold Sponsors: companies that have donated venue space, food, and <= £2500 (incl. event sponsorship)
- Platinum Sponsors: companies that have donated venue space, food, and > £2500 (incl. event sponsorship)

In the admin views, the sponsor form will be updated with an additional option for sponsorship tier, with "Venue Sponsor" as the default. Existing sponsors should be seeded with the default.

**Comment by heruku** [comment]
How and where should these tiers be displayed? Would the tiers be visible on an event page like this: http://codebar.io/workshops/174?

**Comment by deniseyu** [comment]
@heruku these would only be displayed on codebar.io/sponsors, not on the individual event or workshop pages. Don't worry about this issue yet, as we are still having some discussions about what the tiers should be.

**Comment by heruku** [comment]
Thanks @deniseyu

**Comment by skattyadz** [comment]
Assigning myself to this
