### ISSUE TITLE
Create a unified navigation element across all codebar.io sites

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#280]
tutorials.codebar.io, donate.codebar.io, manual.codebar.io, calendar.codebar.io, etc. should have a common UI element that at least provides a link back to www.codebar.io . Possibly also provide navigation between these subdomains.

**Comment by docljn** [comment]
I've had a quick look at the urls mentioned.
- manual.codebar.io : who should have access to this? The only reference I can find on the main site is in the footer "Becoming a Sponsor"
- the codebar blog isn't mentioned, and is linked from the main site, but doesn't have a quick link back to the main site
- calendar.codebar.io is empty as far as I can see
- donate has been done
- tutorials is an obvious candidate for standardising

Is this still a 'wanted' feature?

**Comment by despo** [comment]
Stale issue, closing.
