### ISSUE TITLE
Add a nicer 404 page

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#295]

**Comment by knuxus** [comment]
https://better-error-pages.statuspage.io/ ?

**Comment by deniseyu** [comment]
@knuxus that might be a bit of a sledgehammer in this case :smile: 

Should be possible from within the app. http://easyactiverecord.com/blog/2014/08/19/redirecting-to-custom-404-and-500-pages-in-rails/

We actually only need to rescue 500 errors, because 404s are automatically being redirected to the homepage at the moment.

**Comment by alexanderkustov** [comment]
Feel free to use the https://github.com/codebar/static_pages as a template.
