### ISSUE TITLE
Incorrect maps for sponsors

### ISSUE THREAD

**Issue by margOnline** [codebar/planner#301]
The maps generated by the google maps api for some sponsors are incorrect - Graze and NoTHS are examples. The current workaround is reliant on someone noticing that the map is incorrect and admin sending out an appropriate email to attendees.

One possible solution is to provide an option on the sponsor model indicating that supplied coordinates be used to generate the map. Whilst not an ideal solution, at least the correct map is displayed. 

Happy to consider alternative solutions, but I'm going to look at this one in the meantime.

**Comment by deniseyu** [comment]
Currently being worked on by @margOnline
