### ISSUE TITLE
Coach expertise tags

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#317]
Feature request:

Coaches should be able to add tags to their own profiles for technologies that they are comfortable teaching. This should be editable from the /profiles route.

The tags should be a many-to-many relationship, so that students and other coaches can click on the "Rails" tag on Denise's profile and see a list of all coaches that have listed "Rails" under their areas of expertise.

A migration should also be written to pre-seed the tags table with common things, like HTML, CSS, JavaScript, jQuery, etc. It would be great if the UX for adding tags included some type of auto-complete/prompt feature that scans the database for existing tags, to try to encourage re-use. Similar to tumblr tags.

**Comment by margOnline** [comment]
@deniseyu I can have a look at this.

**Comment by deniseyu** [comment]
@margOnline cool - happy to pair on it with you as well :)

**Comment by margOnline** [comment]
@deniseyu great! [here's](https://github.com/margOnline/planner/tree/coach_tags) what I've done so far. I've used the ActsAsTaggableOn gem. 

Haven't looked at it in a couple of weeks, any questions slack me.
