### ISSUE TITLE
Investigate memory leaks

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#322]
The codebar app has some memory leak problems. Right now they are not bad enough to make the app fall over but it is important that we understand what methods are causing them. If you have experience debugging and resolving memory leaks in Ruby/Rails apps, please get in touch.

**Comment by despo** [comment]
Relevant article
https://blog.codeship.com/debugging-a-memory-leak-on-heroku/

**Comment by asuffield** [comment]
Let's start by upgrading redcarpet to 3.3.3, because of https://github.com/vmg/redcarpet/pull/516 (leaks ~300 bytes on every markdown render).

If it's still leaking after that, I'll take a closer look.
