### ISSUE TITLE
Change contact email in workshop invitations to chapter contact email

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#333]
Invitations and reminder emails for regular workshops contain instructions to email hello@codebar.io -- this should be changed to {{chapter}}@codebar.io (i.e. brighton@codebar.io) as the primary recipient, with hello@codebar.io moved to CC.

**Comment by jenwei** [comment]
@deniseyu = I'd like to help! This is my first time contributing to anything open source. I checked waffle, and it doesn't seem like anyone else has taken ownership of this yet.

This entails modifying the files in `planner/app/views/workshops`, right?

If so, I'll make a new branch and work on this!

**Comment by deniseyu** [comment]
Hey @jenwei thanks for popping by :)

Waffle is a bit out-of-date unfortunately.

The relevant partial is here: https://github.com/codebar/planner/blob/master/app/views/shared_mailers/_social.html.haml

To get the chapter email, I'm not sure off the top of my head exactly how but you should be able to traverse the Session model to get to the Chapter email model. Because it's a partial, the parameter will also need to be passed through the student and coach top-level views in the app/views/mailers/ folder . Alternatively you can add another argument in app/mailer/sessions_invitation_mailer and modify how that gets called by its controller.

**Comment by jenwei** [comment]
Hey @deniseyu - sorry for not responding in a while - I ended up having more coursework than I had anticipated, and I don't think I'll have the bandwidth to do this at the moment.

Sorry about that - hope all is well on your end!
