### ISSUE TITLE
fix broken logo in coaches invitation email

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#337]
Currently the logo is broken in the session_invitation emails. Please see attached screenshot for a visual representation of the issue.
![screen shot 2015-11-13 at 12 28 12](https://cloud.githubusercontent.com/assets/5873816/11146019/8503575c-8a02-11e5-97c4-fb1291553771.png)
Correct link of logo is: https://github.com/codebar/assets/blob/master/logo/png/160x160px/logotype-160.png

Relevant partial can be found under `app/views/shared_mailers/_body_header.html.haml`

**Comment by despo** [comment]
https://github.com/codebar/planner/pull/359
