### ISSUE TITLE
'other' option when signing up for a workshop

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#339]
If 'other' is selected when a student is signing up for the workshop, it would be great if we could display a textfield asking what it is the student plans to work on. As finding out on the day that a student wants to do a really niche thing isn't always that helpful when planning.

**Comment by deniseyu** [comment]
Spoke to @despo once about this -- there used to be an option, but people wrote too much in it or misunderstood and would write things like "I am a vegetarian". I am not opposed to bringing it back, but definitely with a max char limit and clear instructions!
