### ISSUE TITLE
Do not use `Date.today` without zone. 

### ISSUE THREAD

**Issue by alexanderkustov** [codebar/planner#341]
Use `Time.zone.today` instead.

Easily fixed by a search and replace.

**Comment by alvynmcq** [comment]
I would be happy to do this

**Comment by alexanderkustov** [comment]
@alvynmcq cool, leave it for the event 24PR

**Comment by alvynmcq** [comment]
Ok cool. Will get it done on the 1st :-)

**Comment by KimberleyCook** [comment]
@alvynmcq Hey could you please leave this PR for our event coming up as it is a really great beginner PR. Thanks
