### ISSUE TITLE
Spelling error: "You must be logged in to acess this page."

### ISSUE THREAD

**Issue by asuffield** [codebar/planner#347]
Can be seen on any page that requires logging in, when not logged in. http://codebar.io/dashboard is a good one.

**Comment by asuffield** [comment]
![acess_spelling](https://cloud.githubusercontent.com/assets/1300408/11387842/e5a94f08-9326-11e5-88e8-88e1267bd7e4.png)

**Comment by KimberleyCook** [comment]
@asuffield Thanks for this Andrew :)
