### ISSUE TITLE
Minor issue with workshop waitlist reminder email 

### ISSUE THREAD

**Issue by harshisuresh** [codebar/planner#370]
I received a "WORKSHOP WAITING LIST REMINDER" email for worshop scheduled to happen on the same day. But the content of the email mentioned  <b>tomorrow</b> instead of <b>today</b>

"This is a quick email to remind you that you're on the waiting list for <b>tomorrow's</b> workshop.

If an attendee drops out, the next person on the waiting list will automatically get their place. We'll email you if this happens. Attendees often drop out at short notice, so you should keep your laptop with you and check your email <b>tomorrow</b> afternoon."

I guess this could be improved

**Comment by despo** [comment]
Closed as fixed in PR mentioned above.
