### ISSUE TITLE
Delete a workshop

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#371]
Admin needs to be able to delete a workshop in the interface. This can currently only be done in the console.

**Comment by boddhisattva** [comment]
@KimberleyCook I would like to give this a shot. Please suggest how could I assign this issue to myself on Github issues and on the waffle board. Thank you.

**Comment by KimberleyCook** [comment]
@boddhisattva We don't really assign as such but if you want a shot at it people will read this thread and know someone is working on it so please go ahead. Thank you very much :D

**Comment by boddhisattva** [comment]
Thanks @KimberleyCook :)

**Comment by despo** [comment]
This should be constrained to workshops where no invitations have been emailed out and that have been created within X time. Maybe a couple of hours.

**Comment by boddhisattva** [comment]
@despo Thanks for letting me know about this. Just wanted to better understand, how would it help to check if a workshop is created within X hours from the current time before deciding to delete it ?

**Comment by despo** [comment]
@boddhisattva we need this functionality to be plugged in in case someone accidentally creates multiple workshops and constraining it would ensure that we dont remove information that has been on our website for a while. We dont promote deleting workshops. If a workshop is cancelled it should be updated so that people can find that information out.

Does this make sense?

**Comment by boddhisattva** [comment]
@despo This definitely makes it more clear, thank you for the explanation :).

**Comment by boddhisattva** [comment]
@despo Based on your point [here](https://github.com/codebar/planner/issues/371#issuecomment-169356782) . I've assumed the value of 'X' to be 4 hours. Please let me know if this is okay or request you to suggest an alternate value of 'X'. Thanks.

**Comment by despo** [comment]
https://github.com/codebar/planner/pull/374
