### ISSUE TITLE
Only display skills label if a coach has skills set

### ISSUE THREAD

**Issue by despo** [codebar/planner#378]
<img width="1035" alt="coaches_skills" src="https://cloud.githubusercontent.com/assets/159200/12436126/52fa09bc-bf0a-11e5-9c35-b96708b8439b.png">

**Comment by Endi1** [comment]
I wanna give this a go. Can I?

**Comment by KimberleyCook** [comment]
@Endi1 By all means :)

**Comment by Endi1** [comment]
@KimberleyCook Thanks! I'll try to get it done in a couple of days :)

**Comment by despo** [comment]
https://github.com/codebar/planner/pull/381
