### ISSUE TITLE
"Updating Profile" mangles skills list

### ISSUE THREAD

**Issue by thecodeite** [codebar/planner#395]
If you go to update your skills list at http://codebar.io/member/edit then when it loads it loads your skills as a space separated list rather than a comma separated list. If you don't notice and click Save then all your skills are combined into one mega skill.

**Comment by deniseyu** [comment]
what, you haven't heard of the new Javascript framework called rubyjavascriptrailsnodecsshtml?

**Comment by margOnline** [comment]
I'll have a look at this.
