### ISSUE TITLE
Static html maintenance pages

### ISSUE THREAD

**Issue by despo** [codebar/planner#411]
The maintenance page is what users see when the application is down (usually this happens when we are deploying a new release).

They need to be static and standalone! It would be great if the design matches the current website but we are definitely up for a fancy new design!

So we keep the code together it would be great if they are added in public/ until we figure out where we'll be hosting them.

You can see some examples here even though I'm sure there are much better ones around :)
https://www.smashingmagazine.com/2009/06/effective-maintenance-pages-examples-and-best-practices/

**Comment by alexanderkustov** [comment]
Should this be a new github branch? Like a small middleman app just showcasing that page?

If so I can help you with that

**Comment by despo** [comment]
@alexanderkustov not sure if it might be best to keep this in a different repository entirely rather that a different branch - so it can be found easier, it's not deleted accidently when doing maintenance etc. What do you think? 

I would prefer to keep it completely static and ruby free is possible though. The reason for that is  to enable people who are not familiar with Ruby to help out and submit PRs in the future - if needed.

**Comment by alexanderkustov** [comment]
Sorry thats what I meant, you want to start an empty repo? Ill push some simple htmls into it.

**Comment by despo** [comment]
@alexanderkustov https://github.com/codebar/static_pages/

**Comment by alexanderkustov** [comment]
Fixed.

**Comment by despo** [comment]
Done and configure on heroku.

@alexanderkustov you can briefly see on staging as I enabled maintenace mode -> http://codebar-staging.herokuapp.com

**Comment by despo** [comment]
:ship:
