### ISSUE TITLE
Edit sponsor pages loses saved image

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#440]
When I go into the admin area and edit a sponsor I lose the saved image that was previously saved to this sponsor.

**Comment by logeshmallow** [comment]
I can help you on this. So, do you want to preview the image in the edit screen?

**Comment by KimberleyCook** [comment]
@logeshmallow yeah if possible please. It's mainly frustrating that if you need to edit something all the other fields are still saved, image you have to re-upload even when it's the same.

**Comment by logeshmallow** [comment]
Ok, I will fix it soon and send you a pull request. Just to confirm, if you go to edit screen and change the fields except image and save it, what is it happening
1) Is the image that you saved previously is lost? 
2) Or just not show up on the edit screen?

I hope, it should be the first one happening. So, you are uploading the same image again on edit. Pls let me know otherwise.

**Comment by KimberleyCook** [comment]
yes first option, it gets lost. 

Sorry if I didn't explain it that well.

**Comment by logeshmallow** [comment]
Thanks. I will fix it and send you PR soon.

**Comment by KimberleyCook** [comment]
Hey @logeshmallow, how did you get on with this?

**Comment by logeshmallow** [comment]
Hi @KimberleyCook, I was occupied with few other works and just that today I started looking into again and surprise that you too got back. Will look into it today and fix it and let you know ASAP.

**Comment by KimberleyCook** [comment]
@logeshmallow Awesome, thank you :)

**Comment by logeshmallow** [comment]
Hi @KimberleyCook, I have made the change and below is the link to the video of how it is implemented now. Please look into it and let me know and I shall send you the pull request.

https://www.opentest.co/share/96792910b21c11e697503368643fa78e

In the above video, the new sponsor page does not have any change. 

The image was actually present even during edit and just that in our Sponsor model file, there is a validation written as avatar mandatory during the edit also. It does not need validation during the edit as there will be image already present and I just removed it and hence we won't have the '*' before the avatar label during edit.

Please let me know, if this is fine.

**Comment by matyikriszta** [comment]
@KimberleyCook currently the images are being uploaded to our own server via SFTP. I reckon our best bet is to get an S3 bucket going that can store all the images. This will require some code changes but shouldn't be too difficult for an experienced rails dev.
