### ISSUE TITLE
Enhance feedback collection mechanism and extend for Events and Meetings.

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#455]
Currently, only students who attended a workshop receive an automated email shortly after for their feedback.

Feedback is important to us! Especially since we've just upgraded our Sendgrid plan, we can afford to send more emails.

The full enhancement would look something like:
- Build out the coach feedback mechanism, similar to student feedback. Only organisers should be able to see coach feedback.
- Add feedback collection data layers for Events and Meetings, and corresponding rake tasks to send them automatically 24 hours after the event.

I'm happy to pair with someone on this, send me an email at denise@codebar.io and we can arrange something.

**Comment by docljn** [comment]
This looks like an extension of Coach feedback #206
I'm aware that some chapters have implemented separate anonymous feedback mechanisms via third party providers (e.g. Edinburgh for their students only) to give attendees total confidence that feedback cannot be traced to an individual.

**Comment by docljn** [comment]
@deniseyu is this (or #206) still something that the team would like to implement? Just wondering, as it's been sitting open for a very long time....  Thank you.
