### ISSUE TITLE
Add length validation to Member model's 'about_you' field (255)

### ISSUE THREAD

**Issue by Dan-Q** [codebar/planner#471]
members table has column 'about_you' which is of type string and so defaults to a database type with a maximum length of 255 characters. This is reflected int the view (the <textarea> has maxlength="255") however this is not sufficient to avoid ugly exceptions being thrown because browsers count "characters" differently - e.g. Firefox on Windows counts a carriage return/line feed as one character, but submits two characters, and there are probably also issues with multibyte characters. It's also the case that all validation _should_ be on the server side, because you can't rely on browsers to respect any given HTML attribute correctly (the browser is a hostile environment).

The correct solution is to add a length validation to the about_you column in the Members model, with a maximum length of 255, so that proper error messages rather than HTTP code 500s are the result of invalid submissions.

**Comment by mptap** [comment]
I'll take a stab at this.

**Comment by razasayed** [comment]
Sent PR https://github.com/codebar/planner/pull/475 , please review.
