### ISSUE TITLE
Update outdated blog link in footer

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#482]
## The issue

The link to our blog in the footer currently links to our old blog. Update the link to link to our new blog, https://medium.com/the-codelog.
## Steps to fix 🔧
- [ ]  Claim the issue (comment below or if you are part of the codebar org assign it to yourself)
- [ ] Fork and clone the repository
- [ ] Follow the `README` to set up the project
- [ ] Create new branch `updating-footer-blog-link`
- [ ] Update the blog link `href` in `app/views/layouts/_footer.html.haml` from http://tutorials.codebar.io to https://medium.com/the-codelog
- [ ] Commit your changes as one commit titled `fix: updating blog link in footer`
- [ ] Submit a pull request, make sure you mention #codebar24PR2016 in your PR description
- [ ] Get your pull request reviewed & merged

**Comment by tgturner** [comment]
I'd love to a shot at this!

**Comment by matyikriszta** [comment]
fixed by #485, closing the ticket
