### ISSUE TITLE
Adding extra address information to individual workshop page & email

### ISSUE THREAD

**Issue by dondonz** [codebar/planner#489]
## The issue

In Berlin, the hippest tech offices are often in converted factories. For a single address, there might be more than 10 separate entrances. I get lost all the time too.

It would be fantastic to add a little "extra address information" box near the Google map on the individual workshop page. Extra address instructions are usually about three sentences long.

For bonus points, it would be awesome to have this also in the email confirmations and reminders.

## To do

- [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
- [x] Fork and clone the repository
- [x] Commit your changes as one commit entitled `enhancement: adding extra address information`
- [x] Submit a Pull Request, make sure you mention #codebar24PR2016 in the description
- [x] Have your Pull Request reviewed & merged

**Comment by KimberleyCook** [comment]
@dondonz added this to our spreadsheet for 24 pull requests :)

**Comment by takumab** [comment]
@dondonz I will work on this and I was wondering if you wanted to add the extra address info per workshop, per address, or per host?

**Comment by KimberleyCook** [comment]
@takumab could we have per sponsor please? So when we create a new sponsor and put in their address, have another optional field.
