### ISSUE TITLE
Consolidate text of 'Update your attendance' buttons across workshop invitations mailers

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#494]
## The issue

When participants register for a workshop or join a waitlist, they receive a number of emails (workshop confirmation, workshop reminder, waiting list reminder) that all contain a link to the workshop page where they can amend their RSVP status (attending and not attending) and see workshop details such as who will be there at the given workshop. Currently, these buttons all have different call to actions and two of them do not describe the button's purpose well (they are primarily there so you can update your attendance). Update these buttons so they all have the call to action 'Update your attendance'.

## Steps to fix 🔧

- [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
- [ ] Fork and clone the repository
- [ ] Update 
  - [ ] 'Who else will be there' button to 'Update your attendance' in [views/session_invitation_mailer/attending.html.haml](https://github.com/codebar/planner/blob/master/app/views/session_invitation_mailer/attending.html.haml)
  - [ ] 'Can't make it anymore' button to 'Update your attendance' in [views/session_invitation_mailer/attending_reminder.html.haml](https://github.com/codebar/planner/blob/master/app/views/session_invitation_mailer/attending_reminder.html.haml)
  - [ ] 'See who will be there and update your attendance' button to 'Update your attendance' in [views/session_invitation_mailer/waiting_list_reminder.html.haml](https://github.com/codebar/planner/blob/master/app/views/session_invitation_mailer/waiting_list_reminder.html.haml)
- [ ] Commit your changes as one commit entitled `enhancement: consolidating 'Update your attendance' buttons`
- [ ] Submit a Pull Request, make sure you mention #codebar24PR2016 in the description
- [ ] Have your Pull Request reviewed & merged

**Comment by pinglinh** [comment]
Claimed 💯

**Comment by matyikriszta** [comment]
Addressed by #501 , thanks @pinglinh. Closing the issue.
