### ISSUE TITLE
Add Sponsors section to events pages

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#495]
## The issue

Display a Sponsors section on individual events pages if the event has a sponsor and the sponsor does not equal the host. This section should go between the general information and FAQ sections and should list the sponsors in a similarly layout to the Organisers section. Show sponsor logos wrapper in a link to the sponsors website. For a sample event page see [https://codebar.io/events/24-pull-requests-2016](https://codebar.io/events/24-pull-requests-2016).

![codebar-event-page-screenshot](https://cloud.githubusercontent.com/assets/5873816/20763179/e28f9132-b720-11e6-843c-438f2765fab3.png)

## To do

- [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
- [ ] Fork and clone the repository
- [ ] Update [/views/events/show.html.haml](https://github.com/codebar/planner/blob/master/app/views/events/show.html.haml) with Sponsors section
- [ ] Commit your changes as one commit entitled `enhancement: adding Sponsors section to events pages`
- [ ] Submit a Pull Request, make sure you mention #codebar24PR2016 in the description
- [ ]  Have your Pull Request reviewed & merged

**Comment by pinglinh** [comment]
Claimed 💯
