### ISSUE TITLE
Fix workshop/event listing sponsor logos layout issue

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#497]
## The issue

<img width="663" alt="screen shot 2016-11-30 at 20 31 42" src="https://cloud.githubusercontent.com/assets/5873816/20770607/33c40084-b73e-11e6-8c1b-4c382ed45792.png">

As seen on the image above, when an event/workshop has more than one sponsor, the sponsor logos do not stack neatly upon each other, both on the homepage and events page. Add styling to make the logos stack on top of each other. Use Bootstrap if applicable.

## To do 

- [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
- [ ] Fork and clone the repository
- [ ] Markup and CSS can be found in: 
  - [ ] [app/views/events/_event.html.haml](https://github.com/codebar/planner/blob/master/app/views/events/_event.html.haml)
  - [ ] [app/assets/stylesheets/partials/_sponsors.scss](https://github.com/codebar/planner/blob/master/app/assets/stylesheets/partials/_sponsors.scss)
- [ ] Commit your changes as one commit entitled `fix: workshop/event listing sponsor logos layout`
- [ ] Submit a Pull Request, make sure you mention #codebar24PR2016 in the description
- [ ] Have your Pull Request reviewed & merged

**Comment by Bybreen** [comment]
Anna, Suzy and Bybreen are working to revise this as part of the 24 Pull Event.

**Comment by lisowska** [comment]
Anna, Bybreen and Suzy will be working on this issues
