### ISSUE TITLE
Change some gems to use https

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#499]
Heroku warns about this when building:

```
remote:        The git source `git://github.com/Compass/compass-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
remote:        The git source `git://github.com/nixme/jazz_hands.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

We want to switch to the https protocol, not disable it.

Update the Gemfile, run `bundle install`, and, assuming all tests pass, commit along with the updated Gemfile.lock.

**Comment by jemagee** [comment]
I would like to help with this - but jazz_hands is causing me an issue on trying to install my cloned fork.  When I attempt to run `bundle exec rake db:create`, I receive:

```
/Users/john/Documents/forks/planner/config/application.rb:12:in `<top (required)>'
/Users/john/Documents/forks/planner/Rakefile:4:in `require'
/Users/john/Documents/forks/planner/Rakefile:4:in `<top (required)>'
NameError: uninitialized constant Byebug::LocalInterface::Readline
/Users/john/Documents/forks/planner/config/application.rb:12:in `<top (required)>'
/Users/john/Documents/forks/planner/Rakefile:4:in `require'
/Users/john/Documents/forks/planner/Rakefile:4:in `<top (required)>'
```
I'm running Mac OSX 10.11.8

**Comment by hanmd82** [comment]
@deniseyu these would trigger Bundler to bump up the versions of these gems (and their dependencies) as well. Would you want to upgrade them at the same time, or lock in the current versions for `compass-rails` and `jazz_hands`?

**Comment by hanmd82** [comment]
#509 ready for review

**Comment by deniseyu** [comment]
@hanmd82 OK to bump versions as long as all tests are still passing in CI.
