### ISSUE TITLE
Update the copy of the coach guide

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#500]
We had a copywriter amend the copy of the coach guide page.

Whoever does this come and find me and I'll forward you the email.

**Comment by SaphMB** [comment]
Just checking - since the updated copy is quite a significant departure from copy currently on the website - whether you wanted to replace all of the copy with the content of the email

**Comment by matyikriszta** [comment]
@KimberleyCook can you copy and paste the new copy in here? so we can make this change and close this issue

**Comment by matyikriszta** [comment]
@KimberleyCook what's the status of this issue? Is it still relevant? Has this been done? Can we close it if so?

**Comment by KimberleyCook** [comment]
I'm pretty sure this was done at a 24PR, let's close.
