### ISSUE TITLE
Validate Group names

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#510]
For every chapter, our convention is to have two different groups, one named `Students` and one named `Coaches`. Membership in one of these groups is represented by a user subscribing to one of them.

We only have used two strings for names, `Students` and `Coaches` in the last three years, so it is fairly safe to say that these are the only two group types that should exist in every chapter. This should be documented and enforced via a model validation.

In `app/models/group.rb`, we need a custom validator that verifies if the name is either 'Students' or 'Coaches'.

In `app/views/admin/group/new.html.erb` the user interface should be updated to use some sort of preset input (such as a dropdown box or radio buttons) so Students or Coaches are the only options available.

Add a quick unit test for the validation in the Group spec file as well.

**Comment by ajay2507** [comment]
Hi deniseyu, Can I work on this enhancement?

**Comment by deniseyu** [comment]
Sure @ajay2507, go for it.

**Comment by ajay2507** [comment]
okay.. thank you @deniseyu

**Comment by margOnline** [comment]
oops, I didnt see anyone assigned to this and have only just noticed that someone opted to do it. Sorry @ajay2507 maybe you could review the pr?

**Comment by ajay2507** [comment]
@margOnline  I am looking at another issue.. I didn't start this enhancement.. It would take some time.. Is it okay?

**Comment by margOnline** [comment]
This is addressed by #530 which is ready for review. I dont have admin access to view the changes to the form so would be good if someone could check the ui.

**Comment by matyikriszta** [comment]
Addressed by #530, closing this issue
