### ISSUE TITLE
This project is looking for maintainers and administrators.

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#520]
Over the last year or two, I have been mostly closing PRs and building features, and piling on a lot of bad code into here, sorry everybody about that ☹️ 

I'm taking at least six months' hiatus for various life reasons. We're looking for people who can take on ownership of this application. There are a few parts to this, which can potentially be split into multiple roles: maintaining the open-source code, stewardship of the production database, and resuscitating the web server when it occasionally (ok, often) falls over. Ideally we'd like someone who is physically based in the UK, either London or Brighton. All of these responsibilities will involve coming into contact with confidential data, so we'd **strongly** prefer if you are an active member of the codebar community who knows some of the organisers. But if proximity or other circumstance has prevented you from getting involved in person, send us an email at london@codebar.io and tell us why you're interested in helping.

If you have any questions, ping me at @ denise on [codebar Slack](https://codebar.slack.com), and if you need to [sign up, do so here](https://codebar-slack.herokuapp.com). I'll be available until the end of February to do some handover tasks. You can also reach me directly at denise@codebar.io until that time.

**Comment by despo** [comment]
No longer relevant.
