### ISSUE TITLE
Standardise on sign up flow for Workhops, Events and Meetings

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#528]
Currently, the sign up process for Workshops, Events and Meetings all differ from each other. 

When you visit a workshop link (through Slack or Twitter for example) and you are not signed in, you are prompted to either Sign up or Log in. Once you log in and go back to that Workshop page, you are prompted to attend the workshop (either as a coach or a student). 

If you go to an Event page when you are not signed in, you are prompted to attend (either as a student or a coach), without being prompted to log in first if you are not already logged in. Clicking either of these buttons will send you to the homepage with a not authorised message. To sign up to the Event, you have to log in and navigate back to the Event page without having been explicitly told you have to do this first. 

Whereas on Meetings, if you visit the page while not logged in, you receive a message saying you must be logged in to RSVP but there is no explicit call to action (e.g. a button). 

We should standardise on a single format for these three journeys, and we suggest they all follow the format of Workshops. If you are not signed in and you visit a Workshop, Event or Meeting page, you should have a button to Sign up or Log in. Once you are logged in, Workshop and Event pages should prompt you to attend either as a coach or students, while Meeting pages should prompt you to attend regardless of role. 

---

On the Event page:
* When displaying CTA buttons check if the user is signed in
** If they are not signed in show two "Sign up" and "Log in" buttons (instead of currently showing the 'attend' buttons that trigger errors)
 
On the meeting page:
* When displaying CTA buttons check if the user is signed in
** If they are not signed in show two "Sign up" and "Log in" buttons (instead of currently showing a "you must be logged in first" message)

It should be possible to abstract the logic in [_workshop_actions.html.haml](https://github.com/codebar/planner/blob/95d0765fe59f94a4805b1cd42411892d39ce4a7d/app/views/workshops/_workshop_actions.html.haml) to handle all three cases.

**Comment by AELSchauer** [comment]
I would like to work on this!

**Comment by AELSchauer** [comment]
I will work on this.

**Comment by AELSchauer** [comment]
I've submitted a PR for this issue. #556

**Comment by docljn** [comment]
Based on the PR at https://github.com/codebar/planner/pull/556 it looks like this work has been completed?

**Comment by AELSchauer** [comment]
@docljn Yes, it is complete.
