### ISSUE TITLE
Audit site for inefficient ORM usage

### ISSUE THREAD

**Issue by BPScott** [codebar/planner#529]
Looks like there's a few places where we're requesting way too much data from the DB, and relying on lazy-lookups to show information.

Use something like https://github.com/flyerhzm/bullet to spot and avoid lazy loading of entities in order to drastically reduce the number of queries public-facing pages require.

**Comment by dondonz** [comment]
I'm happy to take this on (and happy to work with others!). I'm going to start with changing the Events page request (I'll pop this in a separate ticket), to reduce the number of events called from the DB.

**Comment by BPScott** [comment]
Fantastic, thanks @dondonz

**Comment by despo** [comment]
Addressed on #692
