### ISSUE TITLE
Correct image in the emails

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#531]
In all of the codebar emails there is the wrong image in the top left header. We would like to start using the new one.

If you are interested in this issue, let me know and I'll send you over the correct image.

**Comment by clairgriffiths** [comment]
Hey @KimberleyCook I'd like to take a look at this please!

**Comment by KimberleyCook** [comment]
@clairgriffiths yes, please do lovely :)

**Comment by clairgriffiths** [comment]
Cool, could you please email me the correct image when you get a moment? Cheers

**Comment by KimberleyCook** [comment]
@clairgriffiths Hey, Clair. Did you get round to looking at this? :)

**Comment by MikeRogers0** [comment]
@KimberleyCook I have some spare time coming up! If you want email me (me@mikerogers.io) I can probably get this done :)

**Comment by clairgriffiths** [comment]
I did, but then I'm not convinced I'm doing it right, so it would probably be a good idea for someone else to take this on. Sorry I sat on it for so long...
