### ISSUE TITLE
Mixed content warning for uploaded images

### ISSUE THREAD

**Issue by conorcussell** [codebar/planner#533]
It seems all user uploaded content is being served over `http` rather than `https` resulting in lots of mixed content warnings and the connection being marked as 'not fully secure'

`Mixed Content: The page at 'https://codebar.io/events' was loaded over HTTPS, but requested an insecure image 'http://assets.codebar.io/b//uploads/sponsor/avatar/1/reevoo.png'. This content should also be served over HTTPS.`

**Comment by louiseswift** [comment]
Hey, just been looking into this issue as a trial run for an open-source mentoring session we're planning (inspired by Codebar's #FirstPR event last year - it was awesome!).

(We're not necessarily wanting to take this away from someone else seeking to complete their first PR, but keen to add extra info here if useful.)

So - from our initial investigation, it looks possible that this issue could be in the production app's environment variables. Potentially this line? https://github.com/codebar/planner/blob/master/config/initializers/carrier_wave.rb#L5

**Comment by KimberleyCook** [comment]
@louiseswift if you know someone who would be interested in looking into this issue it would be greatly appreciated :D

**Comment by louiseswift** [comment]
@KimberleyCook No problem! We've got our first code mentoring sessions scheduled now for August (10th & 31st) so if this issue is still open I'll absolutely see if our attendees would like to tackle it. Thanks!

**Comment by matyikriszta** [comment]
@conorcussell this is now fixed, could you verify the site now works as expected? This is what I get in FF

<img width="679" alt="screen shot 2017-08-02 at 20 23 44" src="https://user-images.githubusercontent.com/5873816/28891038-0a14f74a-77c1-11e7-9d1a-78a717b3bd46.png">

**Comment by conorcussell** [comment]
Yeah @matyikriszta looks good to me! 👍

**Comment by matyikriszta** [comment]
@conorcussell great, awesome. @louiseswift sorry for jumping in on this but the issue was with a setting on our server as opposed to a code issue. Only someone with proper access to the server could fix it. Thanks for considering it though. Closing this issue.
