### ISSUE TITLE
Use thumbnail for avatars

### ISSUE THREAD

**Issue by conorcussell** [codebar/planner#534]
The avatars used throughout the site are displaying the full size images as they were uploaded, which means at its worst, a 7.3 mb image is being loaded to be displayed at 90x50px

<img width="818" alt="screen shot 2017-03-08 at 12 28 39" src="https://cloud.githubusercontent.com/assets/4960622/23704028/d3ac1290-03fa-11e7-9b95-dd36a69b94d5.png">

The [avatar uploader](https://github.com/codebar/planner/blob/master/app/uploaders/avatar_uploader.rb#L30) has a method to create the thumbs, so I guess this means they'll be available on `avatar.thumb` as per the [carrierwave docs](https://github.com/carrierwaveuploader/carrierwave#adding-versions). I was unable to test this locally as presumably images are only uploaded on production?

**Comment by KimberleyCook** [comment]
Heyy @conorcussell, thanks for noting this down. All examples I just looked at on the website are either pulling in 26px x 26px (homepage and event page) or 56px x 56px (single workshop page)  size images. Are you able to tell me where on the website you saw this happening. Thanks.

**Comment by conorcussell** [comment]
Hey @KimberleyCook. Sorry I thought it was everywhere, but it seems its just on the events page https://codebar.io/events

**Comment by matyikriszta** [comment]
@conorcussell as Kim mentioned this seems to be a non issue, looking at the code the 56px z 56px version of the images are served on the events page. I'm going to close this issue as we could not replicate it.

**Comment by conorcussell** [comment]
@matyikriszta its still an issue as far as I can see. Check the company images on this page https://codebar.io/events

Thoughtbot, Net Native etc are all over 1000px wide and displayed at a max width of 90px.

<img width="329" alt="screen shot 2017-10-22 at 18 15 19" src="https://user-images.githubusercontent.com/4960622/31864421-030992e8-b755-11e7-87ec-9a66330acd8d.png">

**Comment by matyikriszta** [comment]
@conorcussell I'v opened a PR for this at #613, would be good if you could review it. After more digging I noticed we have a thumb size defined for sponsor avatars but we are currently not making use of it. As I don't have intimate knowledge of how image resizing works in Rails I'm not sure if this is a fix but maybe.

**Comment by conorcussell** [comment]
@matyikriszta as per my PR comment, thats the code I would expect to fix it! I did mention it in my initial issue description but didn't make a PR because i was unable to test locally. Sorry, probably should have just gone ahead and asked someone else to check! Thanks for sorting!

**Comment by docljn** [comment]
Hello the team. Looking at the events page, and the code, it would appear that this has been dealt with and can be closed?

**Comment by conorcussell** [comment]
This was fixed by https://github.com/codebar/planner/pull/613
