### ISSUE TITLE
Security warning in Firefox

### ISSUE THREAD

**Issue by danielquinn** [codebar/planner#535]
The home page warns about insecure elements on the homepage:

![codebar](https://cloud.githubusercontent.com/assets/218205/24103489/578f4188-0d77-11e7-9840-ec3300a30966.png)

Environment:
* Firefox 52 64-bit
* Ubuntu Linux 16.10, GNOME 3.x.

**Comment by BPScott** [comment]
Looks like things loaded from assets.codebar.io are always loaded over HTTP. We should update that to be either protocol-less or always load over HTTPS.

**Comment by danielquinn** [comment]
👍 for always over HTTPS.  Moar encryption == moar better :-)  http://codebar.io/ appears to redirect to https:// anyway, so there likely isn't a case where you'll be pulling from an unencrypted place anyway.

**Comment by matyikriszta** [comment]
@danielquinn this is now fixed, thanks for bringing this to our attention. Could you verify it works as expected in your browser? This is what I get in FF now 

<img width="679" alt="screen shot 2017-08-02 at 20 23 44" src="https://user-images.githubusercontent.com/5873816/28890970-d4f8fffc-77c0-11e7-946d-f2b924b9f379.png">

**Comment by danielquinn** [comment]
Yup.  Looks good to me :-)

**Comment by matyikriszta** [comment]
excellent, closing this issue 👍
