### ISSUE TITLE
Coaches page displays every coach

### ISSUE THREAD

**Issue by dondonz** [codebar/planner#540]
Hello,

At the moment our coaches page is displaying all coaches. I think it's great to demonstrate the very high number of coaches at Codebar. At the moment we have a few hundred coaches on the Wall of Fame and it's a bit difficult to navigate. 

I'd like to hear what you think - should we:
+ Continue to display all coaches, or 
+ Only display a selection, with a line to recognise the total number of coaches that have visited Codebar since 2013, or
+ Introduce pagination

If we do decide to change the coaches page - I can also help with an earlier ticket regarding ranking coaches on the Wall of Fame (#191).

**Comment by MikeRogers0** [comment]
That is a big page, what if it was organised it by chapter (showing most recently active first)?

What kind of data do we have on the coaches (I can't see a Coach table in the schema)?

**Comment by matyikriszta** [comment]
@MikeRogers0 I think that's a good idea, would either one of you be able to pick this up and implement? coaches are Members who are associated with a group for a workshop through subscriptions.

**Comment by dondonz** [comment]
@MikeRogers0 Mike, happy for you to take this one on 👍

**Comment by MikeRogers0** [comment]
Cool! I'll give it a shot :)

**Comment by docljn** [comment]
MR #552 mentions that this issue is closed, and I'm wondering if this should be the case?

The coaches page appears to be organised by year, rather than chapter, but otherwise this does appear to have been implemented.

**Comment by KimberleyCook** [comment]
@docljn yeah this has been done, I'll close. 

And thank you for the work you're doing on our repo, we really appreciate it :)

**Comment by docljn** [comment]
Most welcome @kimberleycook - this is something I really enjoy.
