### ISSUE TITLE
Sign up email should read workshops not weekly workshops

### ISSUE THREAD

**Issue by robinVR** [codebar/planner#541]
The email that goes out to students after they sign up reads "You'll automatically receive invitations to our weekly workshops via email."

Not all chapters run weekly we should change it to "You'll automatically receive invitations to our workshops via email."

**Comment by dondonz** [comment]
Hello! That's a good spot - in Berlin we run workshops every fortnight. I'm happy to make this change, unless someone else wants to jump in.

**Comment by KimberleyCook** [comment]
@dondonz I have a PR in that has lots of copy amends. I can add this to that one as I need to do something else before merging it in anyway :)
