### ISSUE TITLE
Monitoring website performance externally

### ISSUE THREAD

**Issue by dondonz** [codebar/planner#542]
I'd like to start monitoring website performance with an external service. I think it would be useful in identifying the slowest pages/processes on our site, and it would be useful to monitor the effectiveness of performance-related code refactoring.

I suggest we use [Skylight](skylight.io). I've heard good things about it, and as an added bonus they have a free tier (websites with less than 100,000 requests per month are free).

I'd like to hear your suggestions too.

**Comment by KimberleyCook** [comment]
Hey @dondonz,  we do in currently have New Relic installed on the production server of the codebar app if you want to go in and take a look?

**Comment by dondonz** [comment]
Hello, I'm happy to open this to others that would like to take a look.
