### ISSUE TITLE
Organisers (and Chapters) Page

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#544]
It'd be nice to have a page listing all of the organisers behind the various chapters of codebar :) also, in the process, listing what all the current different chapters are!

**Comment by matyikriszta** [comment]
@BNewing we already have a section listing the chapters, on the homepage. This could obviously done a bit nicer/could be more visually appealling
<img width="1426" alt="screen shot 2017-08-22 at 14 12 11" src="https://user-images.githubusercontent.com/5873816/29567070-fc2b59b6-8743-11e7-839b-54bbc39af810.png">
Furthermore, the standalone chapter pages (e.g. https://codebar.io/london) have a Team section, this could be expanded to include a bit more info about each organiser
