### ISSUE TITLE
Allow different timezone for chapters throughout website

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#559]
## Description

Now that codebar is operating internationally outside of the UK, we need a way to store event times so they can be translated to different timezones. Currently all times are saved in UK time which is causing issue for our New York chapter. Please refer to @tomafro's description below to see what steps need to be taken to fix this bug.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by tomafro** [comment]
Hey, I saw a call-for-help on twitter and thought I'd take a quick look. I'm not sure I understand the exact problem (a little more detail would be really useful) but I did find something that might help.

In `Event` there's a `future` scope to find future events:

    > Event.future(1)
    Event Load (0.8ms)  SELECT  "events".* FROM "events" WHERE (date_and_time > '2017-07-21')  ORDER BY date_and_time LIMIT 1

It passes in `Date.current` to the query - the date now in the current timezone. This might not be what you want, as postgres will convert it to the start of the day in UTC, not the user's timezone. As you're comparing against a datetime column, you should probably pass a time into the query, maybe `Time.now`. Hope this is helpful.

If you give more information about what is going wrong (what exact actions fail and how; in which timezones; etc.) I'll try and dig deeper over the weekend unless someone else picks up the baton.

**Comment by KimberleyCook** [comment]
Hey @tomafro so a few examples where this timezone issue is a problem. 

- On the events page attendees are no longer able RSVP after 3pm on the day of the event, which is NYC is 10am in the morning. 

- Also on the events page we have text that says "1 hour ago" which again in NYC still be 1pm in the afternoon. (https://codebar.io/workshops/538)

- On the admin page for the chapter, I can no longer see the event listed as it's passed but again in NYC the event has no passed yet as it's only 1pm let's say.

**Comment by tomafro** [comment]
Thanks for the extra info. I think I understand the problem a bit more now, but as I've only spent an hour looking at the codebase, I could well be wrong, so take all this with a pinch of salt!

Here's what I think needs fixing. It won't be that easy.

- Events should be stored at the time they take place in a single timezone, preferably UTC. So an event happening at 8:30pm on 24th July in London would be stored as `2017-07-24 19:30:00 UTC` while an event at 8:30pm in New York would be `2017-07-25 00:30:00 UTC`. Right now I think all times are stored in London time, and if an event is in New York it is still stored as though it happened at 8:30pm in London. This means finding past and future events doesn't always work.

- Events dates and times should be translated and displayed in the time zone of the place they occur. If times are stored in UTC, they must be translated when viewing or they won't be user-friendly. To do this, a time-zone needs to be added to the Chapter (or maybe the venue?) and used whenever displaying events.

I may be able to help with this next weekend, but not before then.

**Comment by KimberleyCook** [comment]
@tomafro Hey Tom, did you find time to take a look at this by any chance?

**Comment by skattyadz** [comment]
I'm having a look at this today (I'm in PST time zone, by coincidence)

**Comment by KimberleyCook** [comment]
@skattyadz Yaaaass 👐
