### ISSUE TITLE
Specify different roles

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#563]
Currently in the codebar app we have 2 different roles, admin and organiser. This has become too simple and we need to be able to grant granular roles. 

- **Chapter organisers** should be able to create sponsors and set up workshops
- **Event organisers** should be able to create sponsors and set up events
- **Monthly organisers** should be able to create sponsors and set up monthly events

One person should be able to have multiple roles if they're involved in multiple codebar things.

- **Admins** should still be able to do everything

**Comment by marten** [comment]
I would suggest calling monthly organisers something else when coding this, maybe **recurring organisers**?

**Comment by KimberleyCook** [comment]
@marten well they are a monthly organiser and in the admin area of the app is says monthlies. But in terms of what they're called I'm not that fussed as long as I can separate out the different roles.

**Comment by matyikriszta** [comment]
@KimberleyCook @marten we do have the monthlies organiser role already in the app, it just wasn't documented. that leaves us with the event *organiser role* to implement

**Comment by marten** [comment]
I figured that anything that's called monthly now has a high chance of being on some other schedule at some point, but if it's already built in there, then ¯\_(ツ)_/¯
