### ISSUE TITLE
Add venue images to event pages

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#565]
I think having venue images on the event page would be useful and make it seem more attractive, we could also use this in the sharing image on Twitter.

Thoughts?

**Comment by matyikriszta** [comment]
Not sure if this is necessary @zaccolley, if it's meant to encourage attendance not sure if we need that. I reckon it would also be hard to get high quality images for most venues. This sounds like added complexity for organisers that we don't really need.

**Comment by zaccolley** [comment]
yep you're right
