### ISSUE TITLE
improve the layout of the jobs listing page

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#569]
the job listings page is currently pretty bare-bone and could use some work, specifically the job listings preview. At the least I think the job listing should display the company and the application date, possibly a little blurb about the job.

**Comment by zaccolley** [comment]
This seems like a good one to get to grips with the codebase, so may give it a stab.

**Comment by zaccolley** [comment]
ok im working on this today

**Comment by docljn** [comment]
It looks like this work has been done already?

**Comment by zaccolley** [comment]
can close ye

**Comment by docljn** [comment]
Thanks @zaccolley - I don't have (or want!) admin privileges so could you please do so?

**Comment by zaccolley** [comment]
i dont either @matyikriszta can close the issue tho
