### ISSUE TITLE
[Usability] Change double menu for most users

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#580]
I feel like (and other people have mentioned) the navigation being confusing on mobile.
To get to some parts there are two menus, I don't think students/coaches neccessarily need the second menu so here's my ideas for using a dropdown for what is in the menu for them.

I'm thinking we have two states for the navigation for whether or not your logged in.

**Logged out:**

![image](https://user-images.githubusercontent.com/2591901/29526881-fadc3dce-868e-11e7-993b-fbadb25e7135.png)

----

**Logged in:**

![image](https://user-images.githubusercontent.com/2591901/29526903-0d7fd788-868f-11e7-8b43-a6d2cfed50eb.png)

If you're admin:

![image](https://user-images.githubusercontent.com/2591901/29526950-36178146-868f-11e7-9c42-de0fd1a1b492.png)

Your name dropdown:

![image](https://user-images.githubusercontent.com/2591901/29527110-b66a1b9c-868f-11e7-8a2c-125698372d57.png)

On mobile these all compress together, and the dropdown shows more or less results.

**Comment by matyikriszta** [comment]
@KimberleyCook is addressing this as part of the Bootstrap migration.

**Comment by matyikriszta** [comment]
Will be addressed by #1472
