### ISSUE TITLE
[Accessibility] `ids` used multiple times

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#586]
There's places where we uses `ids` multiple times such as #sponsors, or #minified. This can cause issues with assistive technology.

We could use classes instead here.

**Comment by alagram** [comment]
@zaccolley this still up for grabs. I'm a beginner and I'd like to help if no one is working on it. please let me know

**Comment by KimberleyCook** [comment]
@alagram no-one is working on it so please do :D :D

**Comment by alagram** [comment]
@KimberleyCook great!

**Comment by alagram** [comment]
@KimberleyCook just to get a bit of clarity: do we want to find and fix places in the views where `ids` are used multiple times, such as `.large-3.small-6.columns#sponsors#sponsors` and change it to use classes instead?

Please let me know. An example would be super helpful.

**Comment by zaccolley** [comment]
Yeah that's the one.

Really IDs should be unique and once per page.

I'd only use them for linking to parts of the page itself and not for CSS.

Happy to help review anything you cook up @alagram

**Comment by stphnnnn** [comment]
Looks like this may have got lost, is anyone still working on this issue?

If not I’ll claim it 👍

**Comment by zaccolley** [comment]
@alagram did you make any progress here?

**Comment by docljn** [comment]
Hello all. I'm trying to understand the change request as clarified by @zaccolley 
```
Really IDs should be unique and once per page.
I'd only use them for linking to parts of the page itself and not for CSS.
```

Does this mean that if an ID is not used in either a `link-to` or `%a{` situation that your preference would be to have all IDs replaced by classes?  

I've had a look in the javascripts folder and I cannot see any use of an element's ID to select it, but wonder if I'm missing something.

Many thanks.

**Comment by zaccolley** [comment]
Hey @docljn, thanks for picking this up.

What I'm talking about here when linking is document fragments which you can read about here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#Document_fragments Sorry that wasn't very clear.

What I'd do to check if there are duplicate IDs is to search the HTML (via inspecting, or the view source option) for the HTML attributes `id=`. A tool like [Lighthouse](https://developers.google.com/web/tools/lighthouse/) will also find these automatically, but not specifically.

Looking at the website and this issue I can't see where there are multiple so I'm assuming they have been fixed, will close this issue. People can reopen if they don't agree.

**Comment by docljn** [comment]
Thanks @zaccolley I did have a hunt, and was also unable to find any obvious duplicates.  I don't have access to all the admin screens, though, so perhaps they are lurking somewhere in there.  Thanks also for closing the issue, and confirming that fragments (what I used to think of as anchors) was indeed what you were referring to.

**Comment by zaccolley** [comment]
@docljn i thought they were called anchors too, but when i googled it seemed like that wasn't the term lol 😸
