### ISSUE TITLE
[Accessibility] Links with no text

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#587]
Some links we have no text and only use an icon. These links will not be announced by assistive tech.

The most important on here is the menu icon on smaller viewports: 
![image](https://user-images.githubusercontent.com/2591901/29587453-f32c937e-8785-11e7-803e-1bb3c34e6c10.png)

This would also be a big usability win if we added 'menu' as the hamburger style navigation icon is known for being confusing.

![image](https://user-images.githubusercontent.com/2591901/29587583-4f18bb0e-8786-11e7-9d93-d595abb84c16.png)

Something like this would work well.

----

Other places with no text are our social media buttons in the footer, these aren't as important but we could still add text here too.

**Comment by ZooeyMiller** [comment]
If we didn't want to change the design we could use a "screen reader only" class for CSS, this won't solve the issue of the hamburger menu (I agree with your proposed solution :+1:), but could be good for the icons (we can set `aria-hidden=true` on the icons as well so that they don't confuse things). 

```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  clip-path: inset(50%);
  border: 0;
}
```

**Comment by zaccolley** [comment]
The visual change would improve usability too.

Can read more here:
https://www.lukew.com/ff/entry.asp?1945
https://sitesforprofit.com/mobile-menu-abtest

**Comment by docljn** [comment]
Is this description what you were referring to regarding adding text to the social media buttons?
https://fontawesome.com/how-to-use/accessibility
```html
<i aria-hidden class="fas fa-car" title="Time to destination by car"></i>
<span class="sr-only">Time to destination by car:</span>
<span>4 minutes</span>
```

**Comment by zaccolley** [comment]
Yes, something like:

```html
<button>
  Menu
  <span class="icon" aria-hidden></span>
</button>
```

Would work

**Comment by docljn** [comment]
Working on it...

**Comment by docljn** [comment]
@zaccolley Your example button is white with a black border and black text, while all the other buttons on the code bar site appear to be grey with white text.  Is there a reason you went for a different style here?

**Comment by zaccolley** [comment]
Can't remember why I suggested that.
Go with what you think but the grey button could work:

![image](https://user-images.githubusercontent.com/2591901/35834752-009a9fe8-0acf-11e8-8377-9a3ed4d10783.png)

**Comment by zaccolley** [comment]
Looks like you could tweak the HTML to this:

```
<li class="toggle-topbar menu-icon">
  <button>
    <div class="fa fa-bars" aria-hidden></div>
    Menu
  </button>
</li>
```

And then tweak remove the font size as it makes it smaller

```css
.top-bar .button, .top-bar button {
    font-size: 0.75rem;
   /* etc ... */
}
```

**Comment by docljn** [comment]
Thanks again for your help with this one, @zaccolley .
