### ISSUE TITLE
[Accessibility] Using labels for countries

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#588]
In the events component we use `<label>` elements when these could be using `<span>` maybe

**Comment by clairgriffiths** [comment]
Hey @zaccolley I'd like to make this change but could I ask for a brief explanation as to why the change needs to be made? Thanks!

**Comment by zaccolley** [comment]
Hi @clairgriffiths!

Labels are typically used for forms, specifically for labelling input fields. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

We use labels for the countries but I don't think we're using  them correctly.

Making sure we use the right elements for content would hopefully mean assistive technology can understand it better. (Screen readers)

**Comment by clairgriffiths** [comment]
Awesome, thanks for the explanation, I'm going to have a go at making the change. Thanks!
