### ISSUE TITLE
[Usability] People think they've signed up to workshops but they haven't

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#589]
There seems to be a problem with people trying to sign-up for workshops.

@KimberleyCook:
> From what I’ve seen a few times, people go to the event page, if they’re not signed up they go through the process of signing up then don’t realise they need to go to the event page and RSVP
> coming from the event page they think they’ve done that part

I think https://github.com/codebar/planner/pull/527 would work to improve this problem already.

My theory is that the actions you can take on the site aren't clear. Here the "sign up" but on a workshop is supposed to mean "sign up for codebar website" whereas the students think it means "sign up for this workshop"

Maybe a quick fix is to change the "sign up" button to "log in / create an account" that way it's clearer what that action does.

Then we give the user a clear action after that "now you can sign up to this workshop". Cheap to try and see if it improves things too.

A more tech heavy solution could be to track what action a user clicked and then automatically sign them up for the workshop too.

**Comment by BNewing** [comment]
I've had a go at implementing a slight variation on this idea over here :) :

https://github.com/codebar/planner/pull/608

Thoughts welcome!
