### ISSUE TITLE
[Usability] [Idea] When logged in, make homepage the dashboard

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#590]
Currently when you're logged in the homepage shows you:

The mission statement, about section, testimonials, all upcoming events, chapters list.

I think if you're logged in this information is less important as the first three are to give you context as to what codebar is and sign up.

Maybe we could make this page become the 'My Dashboard'.

**Comment by BPScott** [comment]
I disagree with this. It means logged-in people aren't sure where to direct new people to (as the homepage doesn't show intro stuff for them) and more importantly it makes http caching for the homepage more complex. Currently we can send a reasonably timed `cache-control: max-age` header and be done with it. If this were to happen then the homepage differs for every user which means we have to hit the backend every time. We should be able to mitigate that with some cunning use of `vary` - sending cachable responses if the user doesn't have an "I'm signed in" cookie and uncachable responses if they don't. I don't think that level of increased complexity to maintain the current performance characteristics is worth the benefit to the end user.

**Comment by zaccolley** [comment]
Nice, good points - I agree.
