### ISSUE TITLE
Clarify text around the sign up process

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#599]
At the moment, we publicise codebar Oxford by mostly directing people to codebar.io/oxford to sign up. However not all of them have much context for what codebar is, and so I imagine that the current sign up page comes across a bit empty. I'd like to propose some changes to the text on the sign up page, so that it reads as follows:

> "Hi and welcome to codebar! Check out our <a href='http://codebar.io/faq'>FAQ</a> page for any questions you might have, and feel free to email us at `chapteremailaddress` if you can't find the answer you're looking for. Otherwise, use the button below to start the sign-up process."

And then on the following page which talks about eligbility, could we add in a paragraph about GitHub? If they are complete beginners, they'll have no idea what it is or why they're being sent there and it might be super off-putting and mean they don't sign up. The text I'd like to suggest is:

> "To sign up, you'll be taken to something called GitHub. If you don't have an account with GitHub yet, you'll need to create one to sign up. It doesn't take long and it's something that will come in handy when you get started with coding. 

> If you have any questions about the process or would like help with it, feel free to contact the chapter at `chapteremailaddress` "

The above is just first draft text, very open to feedback! It do think adding more text in would make a huge difference to the user journey.

If it all sounds okay I'd like to have a go at implementing it with some help from @marten if he's interested :D

**Comment by matyikriszta** [comment]
Fixed by #600
