### ISSUE TITLE
Readme installation instructions don't mention installing PostGres

### ISSUE THREAD

**Issue by richardwestenra** [codebar/planner#603]
I had issues running `bundle install`, because it failed to install `pg`. At the suggestion of [this Stackoverflow answer](https://stackoverflow.com/a/19620569/1651713), I installed PostGres with homebrew, and that step worked. I imagine homebrew isn't the only way to do it, but maybe we should include homebrew instructions plus a non-homebrew alternative?
e.g.
> ## Install and run PostgreSQL
> [The PostgreSQL Wiki has detailed installation guides](https://wiki.postgresql.org/wiki/Detailed_installation_guides) for various platforms, but probably the simplest and most common method for Mac users is with Homebrew:
> ### Using [Homebrew](https://brew.sh/) on a Mac
> - Install another build of Xcode Tools (typing `brew update` in the terminal will prompt you to update the Xcode build tools)
> - `brew update`
> - `brew install postgresql`
> - `brew services start postgresql`

**Comment by ZooeyMiller** [comment]
There should definitely be a non-brew based installation guide for postgres, it can be quite a faff on linux machines though. 

This is the [guide we've used at founders and coders](https://github.com/macintoshhelper/learn-sql/blob/master/postgresql/setup.md) with some more info [in this issue from the linked repo](https://github.com/macintoshhelper/learn-sql/issues/12). If we use some of this information then I think we should be covering the bases quite well :+1:

**Comment by richardwestenra** [comment]
Nice, thanks @ZooeyMiller! I've updated my instructions to link to a detailed set of guides that I found on the PostgreSQL wiki. That's probably the easiest option. I might make a PR for this now, myself.
