### ISSUE TITLE
Welcome email instructions are inaccurate

### ISSUE THREAD

**Issue by richardwestenra** [codebar/planner#615]
The welcome email to students to students and coaches includes the following:

```
%p
  - if @member.subscriptions.any?
    You'll automatically receive invitations to our workshops via email.
  - else
    We send out invitations to our events via email.
    = link_to "Sign up from the subscriptions page", subscriptions_url
    to receive invitations to our workshops.
  Places are limited, so be sure to respond quickly if you want to attend.
```
(See `welcome_student.html.haml` and `welcome_coach.html.haml`)

This is inaccurate for the London chapter, and possibly some of the other chapters too, as we no longer send out invite emails for London workshops. We should realign our instructions with better information about how to sign up for workshops.

**Comment by matyikriszta** [comment]
Opened a PR for this at #619
