### ISSUE TITLE
[accessibility] Keyboard focus - visual issues

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#616]
When tabbing through the site and you get to the footer, the focus changes the text colour so that links are very hard to read:

![image](https://user-images.githubusercontent.com/16868713/32127042-061d04a4-bb6c-11e7-880b-6daa1cb7ce36.png)

It's also recommended in Heydon Pickering's "Inclusive Design Patterns" that you add a background colour to things keyboard focus is on (something that the gov.uk website does):

![image](https://user-images.githubusercontent.com/16868713/32127027-ec2d8816-bb6b-11e7-9833-510469e2dcc0.png)

Lastly, the outline on nav elements looks a little odd:

![image](https://user-images.githubusercontent.com/16868713/32126961-8505385a-bb6b-11e7-8c1f-6e382b98b0b4.png)

**Comment by turger** [comment]
Seems that the footer links are nowadays easier to read, but I can fix outline from nav elements and add a background colour to hovered items.

**Comment by turger** [comment]
https://github.com/codebar/planner/pull/1114

**Comment by BNewing** [comment]
Looks good! 

If you wanted to go one step further, you could also check out the colour contrast against AA and AAA :) I think at the moment from looking at it, it might pass AA but not AAA. I often use this [colour contrast tool](https://contrast-checker.glitch.me) for that, as you can tweak around the hues and things. 
 
It is still great as it is though, just sharing in case you're interested :)

**Comment by turger** [comment]
Cool thanks Newing! I will check the colour contrasts and make some edits if needed.

**Comment by turger** [comment]
I edited colours so that they now get AAA from text contrast with object background and AA from object contrast with page background.

**Comment by BNewing** [comment]
Awesome! :D
