### ISSUE TITLE
Are the options under "what do you plan to work on?" misleading?

### ISSUE THREAD

**Issue by pablobm** [codebar/planner#620]
Recently I had a chat with a codebar student where I realised that the "What do you plan to work on?" selector (shown to students on workshop pages) could lead to confusion.

![study-topics](https://user-images.githubusercontent.com/36066/32323846-42d0a5dc-bfc1-11e7-973f-210cd36d6400.png)

This selector is a dropdown with options populated from the titles of the codebar tutorials. This student's perception was that students should select one of those options if and only if they were following one of those tutorials. In any other case, they should select "Other".

For example, if a student is working on Ruby, but not following any codebar tutorial, they should select "Other".

My assumption is that this is incorrect, and students are expected to select the topic closest to their current focus, regardless of the material they are following.

This may or may not be a real issue. It may be worth asking around a bit to see what other students think, and see if changes are needed.

**Comment by matyikriszta** [comment]
@pablobm I agree this flow is not very intuitive and we could re-think it to help us capture more accurate information about what students are planning to work on

**Comment by despo** [comment]
Closing this as it is tackled by #1325 which enables the students to select a tutorial as well as add an extra note with further details when they RSVP.
