### ISSUE TITLE
link-to border-bottom and images

### ISSUE THREAD

**Issue by revolunet** [codebar/planner#623]
Hello

There is a small graphic glitch on the sponsor logo on the [workshop detail page](http://codebar.io/workshops/623) (see that dashed border?) it happens with transparent PNG logos. (i since replaced the logo with jpg to prevent this)

<img width="140" alt="capture d ecran 2017-11-20 a 16 19 46" src="https://user-images.githubusercontent.com/124937/33025623-c77fab38-ce0e-11e7-8c07-cb532773c225.png">

The `<a>` has a default border-bottom which should be present only for text content

Chrome, OSX

**Comment by zaccolley** [comment]
Fixed this in #591

**Comment by revolunet** [comment]
thanks !
