### ISSUE TITLE
Add app icons to the repo

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#628]
## Description of the issue 📄

For easier access to the codebar app, some people like to add an icon the website to their home screen on their phone. Currently, the icon shows a screenshot of the homepage or nothing at all. Update the repo by adding app icons to it.

## Screenshots 📷

![image uploaded from ios](https://user-images.githubusercontent.com/5873816/33224183-9aba3912-d15e-11e7-9d28-1ee9598bfca3.png)

## Steps to fix 🛠

There are a number of apps online that will generate app icons for you. We like this option: http://appiconmaker.co/. Ask @KimberleyCook or @matyikriszta to provide you with an image.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by gsouquet** [comment]
I'll take care of this task.
Will contact @KimberleyCook or @matyikriszta on Slack to get the images
