### ISSUE TITLE
Chapter page - chapter sponsors

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#629]
## Description of the issue 📄
At the moment, there is no clear way of seeing who sponsors a particular codebar chapter. There is a chapter page, but it only details past events and who the organisers are.

## Screenshots 📷
![image](https://user-images.githubusercontent.com/16868713/33347399-a56a638a-d48a-11e7-9d7a-102b7e113ed3.png)

## Steps to fix 🛠
Add in a section that shows who the sponsors for that chapter are, maybe underneath team :)

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [x] Mention this issue in the PR description by including it's number
* [x] Have your pull request reviewed & merged by a codebar team member

**Comment by BNewing** [comment]
That would be nice! Would it be hard to do?

**Comment by matyikriszta** [comment]
@BNewing it shouldn't be that hard to do

**Comment by matyikriszta** [comment]
@BNewing there's a PR for this at #847, if you would like to review it
