### ISSUE TITLE
Allow for more authentication options

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#630]
## Description of the issue 📄
At the moment, it's only possible to sign up to codebar with GitHub. This isn't very complete beginner-friendly though, and I have met one person at an event who had gotten completely stuck with it to the point that they  hadn't been able to use the website to sign up. It was lucky that she came along and it got me wondering how many other people this might have happened to.

I've added in some info to the website through another PR to explain what GitHub does, but this extra functionality would be very nice.
## Steps to fix 🛠
Add in another authentication method, like Twitter or Facebook maybe.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by kkavita92** [comment]
Is there a reason codebar has not allowed/done this before?

**Comment by skattyadz** [comment]
I assume it's because it adds more complexity to the site. Password reset flows, avatar upload, things like that. Also, it's probably never important enough to take priority over more pressing issues!

**Comment by matyikriszta** [comment]
As @skattyadz mentioned it adds quite a bit of complexity to the website but I do think it would be important to add at least email signup to the site. @BNewing would you mind me closing this issue and adding a new one for adding email signup to the site? I would not bother with any other service (e.g. Facebook, Google, Twitter, etc.)

**Comment by BNewing** [comment]
Go for it! Emails would be better than any of those other services :)

**Comment by matyikriszta** [comment]
@BNewing great, closing this one and opening another issue.
