### ISSUE TITLE
Add managing events permission to chapter organisers

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#631]
## Description 📄

Chapter organisers should be able to create, view and update events. Currently, they can only manage workshops.

## Steps to fix 🛠

Extend the organiser role to allow for the above actions. The app uses the rolify gem to manage roles. 

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by BNewing** [comment]
Just to chip in, this would be great!

**Comment by matyikriszta** [comment]
On further inspection organisers already have the ability to create events, we just need to add the link to the new event page in the left hand side off-canvas nav.
