### ISSUE TITLE
Add organisers to workshop attendees CSV download

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#632]
## Description of the issue 📄

From the admin workshop view, organisers can download a CSV formatted file with a list of all the attendees of the workshop. This list currently includes coaches and students. We use this file to generate the name labels we print for the workshops. We would like to extend this list to include organisers as well.

## Screenshots 📷

<img width="1280" alt="screen shot 2017-11-29 at 20 22 33" src="https://user-images.githubusercontent.com/5873816/33397271-15e2849a-d543-11e7-8ff1-082865113464.png">

Clicking on the Labels button will download a CSV formatted file of all the coach and student attendees of a workshop

## Steps to fix 🛠

The CSV is generated by a method defined in the `app/presenters/workshop_presenter.rb` file. Update this method so the CSV includes organisers. Make sure that the second item of the row in the CSV is set to 'ORGANISER'.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [x] Mention this issue in the PR description by including it's number
* [x] Have your pull request reviewed & merged by a codebar team member

**Comment by kkavita92** [comment]
I've submitted a PR :)

**Comment by matyikriszta** [comment]
@kkavita92 thanks for tackling this one, very helpful
