### ISSUE TITLE
Ability for admins to archive job submissions

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#637]
## Description of the issue 📄

Currently there is no way for admin to disapprove a job submission to the job board. This means there is no way to remove a job from the list of jobs pending approval. We would like to add a button next to the 'Approve job' button (in the single job page) that 'archives' the job.

## Screenshots 📷

<img width="1280" alt="screen shot 2017-11-29 at 21 28 06" src="https://user-images.githubusercontent.com/5873816/33399947-3af08206-d54c-11e7-964f-24913e4e6285.png">

## Steps to fix 🛠

Implementing this feature will likely involve adding a new `archived` column to the jobs table in the DB (set to false by default). Add an 'Archive' button to `app/views/'admin/jobs/index.html.haml` next to the 'Approve button'. `POST` to an action in `app/controllers/admin/jobs_controller.rb` that sets the `archived` column to `true`.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by m-rwash** [comment]
Hey @matyikriszta I'd like to take this one. But shouldn't we add an `archived_by_id` column as well?

**Comment by BPScott** [comment]
@m-rwash I'm not sure what that column would do, could you elaborate on the usecase for it please?

**Comment by m-rwash** [comment]
@BPScott that column should hold the id of the admin who archived the job. Just like the approving process, there're `approved` and `approved_by_id ` .

**Comment by m-rwash** [comment]
@matyikriszta Also in index view for jobs. we should list jobs that hasn't been approved and not archived as well. We should also provide a link to list archived jobs, maybe just right after `view all jobs` link

**Comment by koskoci** [comment]
@m-rwash Are you still working on this? If not, I can do it

**Comment by m-rwash** [comment]
@koskoci I've finished it but still waiting for review #645

**Comment by koskoci** [comment]
@m-rwash ah okay sorry

**Comment by matyikriszta** [comment]
@m-rwash hey, thanks for tackling this one and sorry for the lack of response on my part -- I will review your Pr in the next few days

**Comment by despo** [comment]
Closing as there are a number of changes in how jobs work in #837 and we should consider using status to achieve this, if its still something we want to implement.
