### ISSUE TITLE
Ability to edit job submission after it has been submitted for approval

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#638]
## Description of the issue 📄

Currently once a job has been submitted for approval there is no way to edit it by either the person who has submitted it or the admins. We'd like to modify this behaviour so submitters can edit their job submissions after it has been submitted. 

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Fixed by #731
