### ISSUE TITLE
Migrate from Mailchimp to Mail for Good

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#641]
## Description of the issue 📄

Mail for Good: https://github.com/freeCodeCamp/mail-for-good

Setup guide: https://github.com/freeCodeCamp/mail-for-good/blob/master/docs/aws_deploy.md

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Closing this as it's no longer relevant.
