### ISSUE TITLE
Site does not sign out

### ISSUE THREAD

**Issue by dansteele** [codebar/planner#648]
## Description of the issue 📄
1) Sign in
2) Click menu > sign out
3) ✅ Correctly taken to the homepage
4) ✅ Sign in button visible
5) Click 'Sign in'
6) 🚫 ❗️ Immediately taken to dashboard without authentication

It seems like the session being properly invalidated, though I haven't taken a proper look (yet)

**Comment by skattyadz** [comment]
If you try to access the [dashboard page](http://codebar.io/dashboard) after signing out you'll see that it is behaving as expected. It looks like this is more of a UX problem.

The site uses GitHub for auth so if you're logged in on GitHub your codebar log in will happen very quickly with no intermediate step. It's actually so fast it's a bit jarring!

Also it doesn't look like there's a sign out flash at the moment

**Comment by despo** [comment]
Closing as this is the expected behavior as per @codeincontext's comment.
