### ISSUE TITLE
Change monthlies waitlist to link to Airtable form instead of email 

### ISSUE THREAD

**Issue by kkavita92** [codebar/planner#658]
## Description of the issue 📄

Currently, joining the waitlist for the codebar monthlies event requires sending an email to monthlies@codebar.io. This should be replaced with a direct link to the monthlies Airtable form which allows attendees to directly input their particulars onto the waitlist. 

## Steps to fix 🛠

Change link in https://github.com/codebar/planner/blob/570403acb902efec321eff6f760336f81b748d2d/app/views/meetings/_meeting_actions.html.haml from email link to Airtable form link. 

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [x] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by zaccolley** [comment]
@KimberleyCook this is closed now
