### ISSUE TITLE
Unknown members attending

### ISSUE THREAD

**Issue by daniellevass** [codebar/planner#661]
## Description of the issue 📄
If a user hasn't filled out their name, we get literally no information to go from as an organizer :( 

## Screenshots 📷
![Imgur](https://i.imgur.com/trDY9nb.png)

## Steps to fix 🛠

1. have form validation to not let people sign up with no name?

2. If they have no name characters present, can we show their email address instead?

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by zaccolley** [comment]
Email address is a good idea

**Comment by matyikriszta** [comment]
ideally we shouldn't allow people to sign up if they haven't provided a name, but this would require re-working the signup process. I'm happy to display emails for now (ideally in the future we would spend some time improving the sign up process).

**Comment by KimberleyCook** [comment]
Filling in your name is on the codebar website is a required field which is where this information comes from right?

**Comment by despo** [comment]
I think this has been resolved as there have been some improvements implemented around the sign up process a while ago so closing. Please reopen if it's still an issue.
