### ISSUE TITLE
Blog issue and sign out issue

### ISSUE THREAD

**Issue by solufemi91** [codebar/planner#664]
## Description of the issue :page_facing_up:
[Raising issue- Rough Draft.pdf](https://github.com/codebar/planner/files/1663623/Raising.issue-.Rough.Draft.pdf)

## To do :clipboard:

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Closing as there is not enough information provided. If you are still having trouble please provide an accurate description of the problem when opening a new issue!

Thanks
