### ISSUE TITLE
Amount of help needed - drop down

### ISSUE THREAD

**Issue by cassieevans** [codebar/planner#676]
## Description of the issue 📄

Brighton crew would really love a way for students to be able to state how much coaching they need when they sign up for a workshop. Main priority being a way for students who don't need a coach to be able to state this

Ideally a drop down, like the "what do you want to work on" would be what we're after. 

At the moment we have a big waiting list every week and after the spots are filled I'd really like to be able to add anyone off the waiting list that doesn't need a coach, they could all just sit and work together. 
## Screenshots 📷
![screen shot 2018-02-08 at 09 42 24](https://user-images.githubusercontent.com/19754257/35965985-71d4bac2-0cb4-11e8-9b73-fc00dcc5852d.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by margOnline** [comment]
The 'motivation' for this issue is something that the W London chapter also experiences. The difficulty is managing total numbers. Even if we're low on coaches, how do we ensure that we don't end up with a total number of attendees exceeding the total that the host has specified? As much as I like this issue, I do think we need to proceed with caution to ensure that sponsors with a smaller space are not overloaded.

Would be good for other chapter organisers to comment vis a vis their experiences and I've posted this link in the slack organisers channel to encourage discussion.

**Comment by Scanvin** [comment]
The NYC chapter does sometimes gather a large waitlist, and do become dependent on coach numbers, so not all student who want to come are able to.

We also do have lots of students in similar programs. This could be a great opportunity to use this function as a 'study group' so our coaches would be able to help those who are self teaching and would be more rewarding to have that 1:1. It would also be a great networking opportunity for those students. 

Not all our sponsors have the space. So not every workshop would need to have this option. But I can see a benefit of this!

**Comment by cassieevans** [comment]
@marg We usually open up our workshops (if they're eg 30 person capacity) with 12 coach spots and 10 students spots

As the coach spots fill up and we can accomodate more students we manually svp people off the waiting list until we've reached either venue capacity or the students to coach ratio is at a logical place. 

For example right now, we've got a couple more spots left capacity-wise, but not enough coaches to allow more students on.

If I could see on the waiting list, next to the students name that they didn't need a coach, I could add them on confidently without messing up the ratio.





I

**Comment by margOnline** [comment]
@cassieevans the issue for W London and possible other chapters is that our student and coach list is very fluid on the day of the workshop. We also experience too high of a rate of no-shows, both coaches and students that makes this difficult to work for us. 

All that having been said, I like this idea and think its worth exploring how it could work, for example, per chapter? What are you thinking that the options for that dropdown would be? What about a simple checkbox `I don't need a coach`?

**Comment by cassieevans** [comment]
Yeah, no shows make it pretty difficult to plan properly. 

A simple checkbox would be perfect.

**Comment by despo** [comment]
I think this can be closed as it's tackled by #1325 which adds an extra field to the invitation and enables both students and coaches to set a note. 

A chapter can explicitly request for this information to be set (if a coach is required) by editing the workshop description.
