### ISSUE TITLE
Swap current date picker on new monthlies (meeting) admin page

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#682]
## Description of the issue 📄
Swap current date picker on new monthlies (meeting) admin page with a date picker in the style of new workshops admin page.

## Screenshots 📷
![codebar io_admin_workshops_new laptop with mdpi screen](https://user-images.githubusercontent.com/5873816/36950251-6edc045e-1fa8-11e8-92da-4a3295909af2.png)
![codebar io_admin_workshops_new laptop with mdpi screen 1](https://user-images.githubusercontent.com/5873816/36950256-7c01fe40-1fa8-11e8-810d-8a1c6bee6955.png)
date and time picker on new workshop admin page

![codebar io_admin_meetings_new laptop with mdpi screen](https://user-images.githubusercontent.com/5873816/36950276-ab44723c-1fa8-11e8-86e1-6618be52e132.png)
date and time picker on new monthlies admin page

## Steps to fix 🛠
Replicate the date and time picker inputs in `app/views/admin/workshops/_new.html.haml` in `app/new/admin/meetings/_new.htm.haml`. You specifically want to take a look at the `:local_date` and `:local_time` fields.

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by docljn** [comment]
I was trying to look into this, and noticed that I would need to be an organiser in order to gain access to this part of the site's functionality.

Once I had the site running locally I:
1. Registered as a user (coach)
2. Used sql to find my user_id in the planner_development database
3. Used sql to find the permission_id associated with an organiser
4. Inserted my user_id with the organiser's permission_id into the users_permissions table

On reloading the site, I now have access to the Admin section of the menu, which allows me to create a new Workshop.  I cannot find reference to a link to create a new Meeting, though I can access it via `http://localhost:3000/admin/meetings/new` (lucky guess).

I also cannot find either of the files referenced above, and am wondering if the changes should be in _form.html.haml?

Many thanks.

**Comment by despo** [comment]
Hi @docljn, 

I think to get the link on the sidebar you need to specifically have access as a meetings organiser 
eg `member.add_role(:organiser, Meeting)` even though as an admin you can do anything!

In general to grant permissions to your user you need to 
1. Find your user's member account
2. Grant the access you want
- Access everything`member.add_role(:admin)`  - but this wont give you the organiser menu on the side
- Chapter organiser`member.add_role(:organiser, Chapter.find(:id))` 
- Meeting organiser `member.add_role(:organiser, Meeting)` 


The details to the date fields are in the form that you mentioned above, and to configure them you need to follow the pattern here  https://github.com/codebar/planner/blob/master/app/assets/javascripts/application.js#L35 and here https://github.com/codebar/planner/blob/master/app/assets/javascripts/application.js#L30

I hope this helps! Let me know if you have any more questions.

**Comment by docljn** [comment]
Thank you.

**Comment by docljn** [comment]
Hello again. 

I must be missing something about how to add the role permissions, as I cannot work out how to do it at all.  However, adding a new meeting seems to have given me the access and menu items I need.

Query (hoping I've not dived down the wrong rabbithole):
:local_date and :local_time for a workshop refer to a timezone which is associated with the relevant chapter.
A meeting doesn't appear to be associated with a chapter in the same way, so how would the local timezone be determined?

**Comment by despo** [comment]
@docljn let's catch up on slack about permissions! I'll DM you.

Regarding a meeting's timezone, even though not ideal, it would be safe to assume that all chapters would be within the same timezone (at the moment London is the only location running meetings anw). 
I would not make any changes to fix Meeting timezones as part of this work as it's something we should address separately - and I think we should probably drop multiple chapter support for meetings as well.

**Comment by docljn** [comment]
Hello @despo and @MarckK should this issue still be open?

**Comment by matyikriszta** [comment]
@docljn no, I will close it now.
