### ISSUE TITLE
Add 'Supports HTML` note to Description field in new monthlies admin page

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#683]
## Description of the issue 📄
Add 'Supports HTML` note to Description field in new monthlies admin page.

## Screenshots 📷
![codebar io_admin_meetings_new laptop with mdpi screen 1](https://user-images.githubusercontent.com/5873816/36950365-c742acc8-1fa9-11e8-8f24-32d1882991e9.png)
Add note to the description field

## Steps to fix 🛠
Edit HTML in `app/views/admin/meetings/_forms.htm.haml`.

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
I started doing a few admin amends last night so will add this in as part of it.

**Comment by matyikriszta** [comment]
@KimberleyCook ok cool, thanks

**Comment by matyikriszta** [comment]
Addressed by #685
