### ISSUE TITLE
Sponsor page uses full-resolution image uploads

### ISSUE THREAD

**Issue by codeincontext** [codebar/planner#687]
## Description of the issue 📄

Images on the sponsor page aren't resized so can be as big as they like. [example](https://assets.codebar.io/b//uploads/sponsor/avatar/15/which.jpg)

## Steps to fix 🛠

Add a size to the AvatarUploader so images get resized to something sensible

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Closing this as I'm pretty sure it has been resolved at some point and is no longer an issue. Please comment if I'm getting this wrong.
