### ISSUE TITLE
Coaches page makes a database call for every coach, and there are 1040 coaches

### ISSUE THREAD

**Issue by skattyadz** [codebar/planner#695]
## Description of the issue 📄

See https://github.com/codebar/planner/blob/master/app/controllers/dashboard_controller.rb#L32

## Steps to fix 🛠

- Load coaches in a single, performant request
- Limit the number of coaches shown

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@skattyadz I think we should display only the coaches who have coached in the past year, based in how many times they have coached
