### ISSUE TITLE
Donate button does not work on Donate page in Chrome

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#699]
## Description of the issue 📄
The Donate button stopped working on the donation page in Chrome and Firefox (it works fine in Safari). When clicked a popup should appear prompting you to fill out email and card details. We use Stripe to accept payments on the site.

## Screenshots 📷
<img width="1280" alt="screen shot 2018-03-20 at 10 15 06" src="https://user-images.githubusercontent.com/5873816/37670868-9eb9e6d8-2c27-11e8-89bf-43b8cd7c85bb.png">

<img width="1237" alt="screen shot 2018-03-20 at 10 14 35" src="https://user-images.githubusercontent.com/5873816/37670879-a3fc4082-2c27-11e8-9b45-e8391f3d195e.png">

## Steps to fix 🛠
This is likely an issue with the javascript Stripe provided that power the Donate button and the popup where you have to fill in your details. 

## To do 📋
* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [x] Mention this issue in the PR description by including it's number
* [x] Have your pull request reviewed & merged by a codebar team member

**Comment by BPScott** [comment]
I've done some research into this, and found [this here thing](https://wordpress.org/support/topic/stripe-payment-is-not-working-on-google-chrome/) that suggests CloudFlare's ["Rocket Loader"](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-)  JS optimisation thing that rewrites and rehosts all JS does not play nicely with Stripe's embed JS. This is backed up by a note in the [Stripe API](https://stripe.com/docs/checkout#integration-custom) that says:

> Checkout must be loaded directly from https://checkout.stripe.com/checkout.js. Using a local copy of Checkout is unsupported, and may result in user-visible errors.

Which seems pretty damning. I think the solution to fix this is to [stop loading this script via Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-). This can be done by adding a `data-cfasync="false"` attribute *before* the src tag that loads [Stripe's JS](https://github.com/codebar/planner/blob/387c00c573455837738c7cd91e33cab5279c7039/app/views/donations/new.html.haml#L2).

**Comment by matyikriszta** [comment]
Dirty fix: I've disabled the Rocket Loader on the Donate page via "Page Rule" in the Cloudflare admin panel and the popup is working again. Fixing this by doing the cfasync thing is still a good idea so we can reclaim that page rule.

**Comment by matyikriszta** [comment]
@BPScott have opened a PR for this, you can check it out at the above link

**Comment by matyikriszta** [comment]
Once the above PR has been deployed we can update the rule in cloudflare and test the `data-cfasync` solution. Leaving issue open for now until we verify the solution works.

**Comment by matyikriszta** [comment]
@BPScott this has now been deployed. Would you be able to test if the popup works for you? I have removed the page rule in Cloudflare. If you verify it's working for you I'm happy to close the ticket.

**Comment by BPScott** [comment]
Clicking on the donate button shows me the popup now. Looks like the cfasync attribute is working as we hoped 🎉
