### ISSUE TITLE
Clicking Attend as Coach Button doesn't appear to do anything for an event 

### ISSUE THREAD

**Issue by DarrylBayliss** [codebar/planner#703]
## Description of the issue 📄

When attempting to sign up to an event as a coach. I was directed straight to the events page without any notification that I was successfully or unsuccessfully registered. There appeared to be a lot of coaches signed up already, so perhaps it's something to do with the coach limit being hit.

Ether way, it feels unintuitive and could be improved.

You can reproduce this by trying to click attend as coach over at: https://codebar.io/events/android-workshop-6

## Screenshots 📷

None sadly

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
Closing this as I can't replicate. Due to the amount of changes that have taken place in the app since then, it could have maybe been resolved?
