### ISSUE TITLE
Navigating via “Manage your invitation” sometimes results in a 404

### ISSUE THREAD

**Issue by hugo** [codebar/planner#735]
## Description of the issue 📄
Sometimes navigating to the attendance management page fails with a 404. The link on the workshop page points to a url such as `http://www.codebar.io/workshops/781/rsvp` but the required url is at something like `http://www.codebar.io/invitation/[redacted]`.

This behaviour can be reliably reproduced by disabling JavaScript.

Expected behaviour:
Using the link navigates to the manage invitation page

Observed behaviour:
A 404, not found, page is displayed

## Screenshots 📷
![0843e63e-e44e-4c12-9a1e-2c4b9913b1b3](https://user-images.githubusercontent.com/1704089/40712645-16ae5f2e-63f6-11e8-83f8-d486188db6a4.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by despo** [comment]
@hugo people are able to subscribe as both a student and a coach, so at times there are multiple invitations for them linking to the same event. Which is why a direct invitation link cannot be used here and it's not as straightforward as linking to the invitation.

**Comment by hugo** [comment]
@despo in that case, why is the button a link at all? Would it make more sense to have it disabled until the JS click handler is attached?

**Comment by despo** [comment]
@hugo yes, either that or changing the POST to a GET. It's not hard to fix but it needs some time invested for better tests around the failing issue.
