### ISSUE TITLE
Add admin chapters view that lists all active and inactive chapters with the ability to manage the status of the chapters (active/inactive)

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#738]
## Description of the issue 📄
We'd like to have a dashboard where admins could manage chapters. This view would list all active and inactive chapters codebar has. We'd like it if an admin could manage the status of a chapter from this page (set it to active or inactive).

## Screenshots 📷
This screen could be similar to the admin sponsors screen.

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message.
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by yihyang** [comment]
Hi @matyikriszta I have added created a PR here:
https://github.com/codebar/planner/pull/1069
