### ISSUE TITLE
Workshop email reminder arriving on the the day of the event says "tomorrow"

### ISSUE THREAD

**Issue by kuprinaga** [codebar/planner#743]
## Description of the issue 📄
The confirmation email for 19.06 workshop was sent at 3am Finnish time and the header said the workshop is tomorrow.

## Screenshots 📷
![image](https://user-images.githubusercontent.com/20064653/41614190-7522961e-7400-11e8-84fd-8bf015ad63a8.png)

**Comment by notapatch** [comment]
Hi kuprinaga

The website sends out an "attendance confirmation" email when you agree to go and then a "workshop reminder" email nearer the time. The email above looks like a "workshop reminder" and I think it would be less confusing if the title of the issue avoided the word "confirmation" - it could be changed to something like:

Workshop email reminder arriving on the the day of the event says "tomorrow"

**Comment by kuprinaga** [comment]
Done, thanks
