### ISSUE TITLE
Add German translations to app

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#745]
## Description of the issue 📄
Now that the app support multiple languages we would like to add German translation to the app to support our Berlin chapter. The pages of priority to translate are the CoC, the Student Guide and the Coach Guide.

## Screenshots 📷
N/A

## Steps to fix 🛠
* in `config/locales` duplicate the `en.yml` file and rename it to `de.yml`
* add German translations where appropriate/needed, replacing the English copy

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@unicornelia new ticket for German translation

**Comment by khamiltonuk** [comment]
If you stumble on this pull request and would like to add some German translations you can do so here [https://crowdin.com/project/codebar](https://crowdin.com/project/codebar)

**Comment by janhohner** [comment]
I'd like to take this issue :)

**Comment by khamiltonuk** [comment]
@janhohner Thanks so much for this, translations should go into [https://crowdin.com/project/codebar](https://crowdin.com/project/codebar) as we don't directly edit the file `config/locales/de.yml`, the crowdin web app makes a pull request on the repo, I tried to copy some of your translations over but will do more when I have time.

**Comment by janhohner** [comment]
Ah, that's a shame - I misunderstood your comment before and thought it might be to make it easier for non-coders to contribute. I'll help with the transfer :)

**Comment by janhohner** [comment]
Done 😉

**Comment by lisaschumann** [comment]
I've added some new translations to the Crowdin page.
