### ISSUE TITLE
Eligibility emails - include chapter emails that student is subscribed to

### ISSUE THREAD

**Issue by despo** [codebar/planner#746]
## Description of the issue 📄
Currently when we sent out eligibility emails, only our main mailing list that no chapters have access to is cc'ed.

Update the mailer to cc any chapters that the student is subscribed to as well in order to also enable the chapter organisers to both view elibility checks emailed out and be able to respond to them.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by beatriceo** [comment]
I'm new to open source and relatively new to Ruby, but I'd like to give this issue a shot if it is still open. It may take me a few days to figure out though.

**Comment by matyikriszta** [comment]
@beatriceo yes, this issue is still open, please do give it a shot, let me know if you have any questions and I'll try to help the best I can
