### ISSUE TITLE
Enable description field in workshop creation

### ISSUE THREAD

**Issue by nadiakiamilev** [codebar/planner#783]
## Description of the issue 📄
Currently, when you create a workshop, you are only able to add basic details about the workshop (date, time, number of seats available). Workshop sessions are missing a description field that would allow you to add text about the workshop. 

## Screenshots 📷
N/A

## Steps to fix 🛠
* add a form field for a description in the workshop creation form

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
@nadiakiamilev what type of information are you thinking of wanting to add?

**Comment by nadiakiamilev** [comment]
We wanted to be able to add personalised text about the session. Something like:

"Join us for our first Codebar workshop at Designit! If you’ve been keen on learning how to code, this is the place for you. 

Snacks & refreshments will be provided. Please bring your laptop & charger. We have coaches that can help in both Norwegian & English."

We also felt that it would allow us to have a bit more of a personalised voice in the workshop description :)

**Comment by matyikriszta** [comment]
@nadiakiamilev @KimberleyCook I think this is a good idea. I think especially for chapters outside the UK it's useful to say people can help in the local language (as currently the website is all in English and some people interpret that as the workshop being run in English as well). Maybe next to the text  area input we could show what the default text is (I think we should keep this), so people don't repeat themselves, but they could add additional details if the wanted to.

**Comment by AlexAvlonitis** [comment]
Hi, can i take this?

**Comment by turger** [comment]
I can start doing this.

**Comment by turger** [comment]
Here's the pull request: https://github.com/codebar/planner/pull/1115

**Comment by matyikriszta** [comment]
@nadiakiamilev this has now been implemented and will be deployed shortly, closing this issue.
