### ISSUE TITLE
Duplicate listing of events for any member on dashboard  when they are attending an event belonging to one of their subscribed groups

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/planner#824]
## Description of the issue 📄
When viewing `my dashboard` after logging in `https://codebar.io/dashboard` as an admin the upcoming event is listed twice 

## Screenshots 📷
<img width="1337" alt="screen shot 2018-10-04 at 09 01 25" src="https://user-images.githubusercontent.com/4013283/46457904-44f8d900-c7b4-11e8-8d36-879743f155d0.png">

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by daverick** [comment]
I have the same issues.
I think I had it before as a coach too. if I am not authenticated it is correct.
it is happening only for the events of my chapter (barcelona)
reproduced in Safari and Chrome.

**Comment by despo** [comment]
I can replicate this issue by RSVPing for workshops in a chapter that I am subscribed to.

**Comment by despo** [comment]
Fixed in #852 and :shipit:
