### ISSUE TITLE
Order chapters alphabetically on admin dashboard page

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#846]
## Description of the issue 📄
Chapters in the Chapter section of the admin dashboard page are currently ordered by [some order]. Order chapters alphabetically so it's easier to find them.

## Screenshots 📷
<img width="467" alt="screen shot 2018-10-16 at 21 53 58" src="https://user-images.githubusercontent.com/5873816/47062981-1274b600-d18e-11e8-83a9-09d32187f524.png">

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by shanodin** [comment]
Hello, I'd like to look into fixing this issue!

**Comment by despo** [comment]
@shanodin thank you, that would be great! Let me know if you need any help.

**Comment by shanodin** [comment]
@despo oops I deleted my comment because I wasn't sure if I could do it. The issue I am having is that I don't know how to create an admin account to see the page the issue is referencing so I can't see the effect of my changes. If you could tell me how to do that I might make some progress.

**Comment by shanodin** [comment]
Oh it looks like someone else has submitted a PR for this :( nevermind then

**Comment by pawgrmr** [comment]
Hello, is this still open? I noticed someone has submitted a PR for this issue but it's still open

**Comment by matyikriszta** [comment]
@pawgrmr feel free to pick this up, I have closed the previous PR as the work is not what we have asked for and there hasn't been much progress on it
