### ISSUE TITLE
Improve layout and labelling of the workshops section on the individual chapter pages

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#851]
## Description of the issue 📄
Add Upcoming events label to upcoming events section. Add better visual separation between upcoming and past events sections and between events in a specific section as well.

## Screenshots 📷
Current layout
<img width="1440" alt="screen shot 2018-10-17 at 1 35 43 pm" src="https://user-images.githubusercontent.com/5873816/47114949-07fc0000-d212-11e8-8e38-7220f3303d73.png">

## Steps to fix 🛠
Update relevant templates and CSS files.

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by rubyrox** [comment]
I would like to claim this issue

**Comment by stphnnnn** [comment]
I would like to claim this issue if it's still available?
These event cards could definitely be made to look a lot clearer 👍

**Comment by matyikriszta** [comment]
@stphnnnn yes, this is still available. Our main concern is that Latest events have a label while upcoming events do not, and it would be good to have better separation between upcoming and latest events and the events themselves.

**Comment by stphnnnn** [comment]
@matyikriszta brilliant! I've made a start on this but though it best to post an update here to start a discussion around design.

Here's where I have go to:
<img width="1519" alt="screenshot 2019-01-28 at 16 35 32" src="https://user-images.githubusercontent.com/53346/51851014-eafbc080-231a-11e9-8244-445ccc2acee0.png">

And how the event card design works on the homepage:
<img width="1514" alt="screenshot 2019-01-28 at 16 40 08" src="https://user-images.githubusercontent.com/53346/51851270-75442480-231b-11e9-9baa-df2714712395.png">

As you can see, I've added "Upcoming Events" and "Past Events" labels which should help distinguish between the two.

I've also faded the past events out to give them less prominence on the page and tweaked the event cards themselves to make them feel more structured and hopefully a bit easier to digest.

Let me know what you think. This has knock-on effects throughout the site but I think that changes are beneficial.

**Comment by brunogirin** [comment]
The border and separation between upcoming and past events makes sense. Shading of past events too. All this adds clarity which is good.

I find the content of the tiles clearer on the existing design, in particular the time. In the current design, the time is very obvious whereas on this new one it gets drowned by the "Time:" label and the date which is repeated from the header.

This new design results in taller tiles which will require more scrolling. Considering the number of events is generally increasing, will that become a problem? With the current design, I can fit 3 to 4 events on a 13.3" laptop screen. Based on the screenshots above the new design will bring this down to 2.
