### ISSUE TITLE
Ability to mark a workshop as cancelled

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#856]
## Description of the issue 📄
Recently a workshop had to be cancelled and the only way to let people know was tweet, then close RSVP for the workshop. It would be good to have a little check box maybe that says "cancel workshop" then a little note shows on the event page saying it's been cancelled.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by turger** [comment]
I'll do this.

**Comment by turger** [comment]
https://github.com/codebar/planner/pull/1113

**Comment by matyikriszta** [comment]
There's an open PR for this here: https://github.com/codebar/planner/pull/1113. It's currently on hold until the maintainers clarify some aspects of the feature.

**Comment by despo** [comment]
Closing in favour of #1251
