### ISSUE TITLE
Hosts on chapter pages

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#863]
## Description of the issue 📄
The new chapter pages look great! It's so nice to have more information on them. 

At Oxford, we tend to have hosts be separate to sponsors. We've been hosted by the Oxfordshire County Council and Innovation Centre a few times, but it looks like only sponsors get displayed in the sponsor grid. Would it be possible for hosts to be included as well?  

## Screenshots 📷
![image](https://user-images.githubusercontent.com/16868713/47555064-c995cd80-d902-11e8-916b-021528fe2f88.png)

## Steps to fix 🛠
Add in hosts into sponsor grid (if possible) 

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by fan70m** [comment]
Hi, I would like to work on this issue!

**Comment by despo** [comment]
Closing this as we identified that this was due to the expected host not being part of the last six companies that hosted.

Hosts as well as sponsors are listed on the chapter. page.
