### ISSUE TITLE
Prevent accidental removal of RSVP with a confirm dialogue 

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/planner#867]
## Description of the issue 📄
As an admin it is a little too easy to remove an RSVP by mistake.
I propose we add a confirm dialogue; just to make sure.

Dialogue should explain the attendee is removed from the workshop, but not blocked, the student can easily sign up again, I think the functionality is fine, but could be explained somewhere. 

### Helpful guide 
 [https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm)

## Screenshots 📷
<img width="1426" alt="screen shot 2018-10-31 at 09 36 14" src="https://user-images.githubusercontent.com/4013283/47775710-ba42c580-dcf0-11e8-9d0d-9485efeaf4c3.png">

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@khamiltonuk these are great suggestion but I feel like these are separate issues and should be addressed as separate PRs. Would you mind breaking these into separate issues accordingly? For the icon bit, do you have an idea what icon would be better? Maybe a trash can?

Re: the email, I think it would be nice to send an email. This again could be it's own item though.

**Comment by khamiltonuk** [comment]
@matyikriszta Ok updated the issue just to be about the confirm dialogue

**Comment by matyikriszta** [comment]
@khamiltonuk great, thanks

**Comment by matyikriszta** [comment]
@khamiltonuk there's a PR for this now at #948

**Comment by khamiltonuk** [comment]
Done
