### ISSUE TITLE
Calender invitation does not respect timezone of the chapter's start time

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/planner#875]
## Description of the issue 📄
A student recently sent a message to Berlin organisers saying 

> "Hi there - it looks like the calendar invite is defaulted to PST instead of CST :) 
Can we move this event to Mon, Nov 19, 6:30 PM?
codebar @ Thoughtworks Berlin
Scheduled: Tuesday, Nov 20, 2018 from 3:30 AM to 6:00 AM
Location: ThoughtWorks Deutschland GmbH, Zimmerstraße 23, Berlin, 10969
Invitees: codebar Berlin"

I think it might even be the users calender default calender timezone, i am yet to replicate myslef, either way the calender invite should have a specific timezone set in the invite depending on the codebar chapter's location

This has never knowingly caused a student or coach to be late to date in Berlin.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@acaporrini sorry, we missed this message. Feel free to claim the issue of you are still interested.

**Comment by JacobAbrahamShopify** [comment]
Im new to open source and would like to work on this 🤚

**Comment by JacobAbrahamShopify** [comment]
@matyikriszta 2 questions
1. i ran the app locally but i tried making changes to the view file and reload the page it doesnt get reflected. how do i go about doing this?
2. how can I open the rails console? when i do `rails console` i get this
```
/opt/rubies/2.4.2/lib/ruby/2.4.0/irb/completion.rb:10:in `require': dlopen(/opt/rubies/2.4.2/lib/ruby/2.4.0/x86_64-darwin17/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib (LoadError)
```

**Comment by notapatch** [comment]
Hi @JacobAbrahamShopify 

Not a maintainer but in regards to 2.

This is probably a problem on your development system. There are a couple of of stackoverflow threads on it:

[rails console doesn't load due to libreadline](https://stackoverflow.com/questions/25591527/rails-console-doesnt-load-due-to-libreadline)
[Rails Console Not Loading](https://stackoverflow.com/questions/12591585/rails-console-not-loading)

Googling: `rails readline` may also give you some more ideas
