### ISSUE TITLE
Create button disappears when new sponsor form has error

### ISSUE THREAD

**Issue by brunogirin** [codebar/planner#907]
## Description of the issue 📄

When creating a new sponsor and having a logo upload error in the form (tried to upload SVG), the form is presented again with the error highlighted but the "Create sponsor" button is no longer available so the form cannot be re-sent.

## Screenshots 📷

![selection_410](https://user-images.githubusercontent.com/216028/50559918-5722de80-0cf3-11e9-91a8-614bcdfda360.png)
![selection_411](https://user-images.githubusercontent.com/216028/50559921-5b4efc00-0cf3-11e9-8547-864302b496f1.png)

## Steps to fix 🛠

Ensure the "Create sponsor" button is available when the form is presented again.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by MarinaMuttik** [comment]
Hi, I will try to give this issue a go :-)

**Comment by KimberleyCook** [comment]
@MarinaMuttik That would be hugely appreciated, thank you
