### ISSUE TITLE
Coaches / students entries in random order on registration page

### ISSUE THREAD

**Issue by brunogirin** [codebar/planner#908]
## Description of the issue 📄

On the registration page, you can register as a coach or student with any chapter. The "coaches" and "students" entries appear to be in random order.

## Screenshots 📷

![image](https://user-images.githubusercontent.com/216028/50629435-75c3e800-0f34-11e9-84eb-ba27c9d929de.png)

## Steps to fix 🛠

Choose a fixed order and order entries accordingly.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [x] Update the relevant files. Follow the steps to fix section in this issue.
* [x] Commit your changes as one commit. Use the title of this issue as your commit message
* [x] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@brunogirin there's a PR for this now at #930
