### ISSUE TITLE
Add extra information to attendee csv download

### ISSUE THREAD

**Issue by elderfd** [codebar/planner#922]
## Description of the issue 📄
On the admin page for a workshop, you can currently either download a .csv file with names and coach / student designation OR a different format with more information (such as what students want to achieve).

It would be good to be able to download all attendee info in .csv format. This allows import into Excel for student + coach matching. Currently we post-process the downloaded info from the "Attendees" button to achieve this, but would be preferable to have a button for this.

## Steps to fix 🛠
Add additional button to download all attendee data, or edit functionality of one of the existing buttons.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@elderfd could you specify what information you want to be able to download exactly? Besides name/role/what students are working on?

**Comment by elderfd** [comment]
In an ideal world we would get,

- Name
- Student / Coach
- What students want to study
- Bio
- First timer?

These are the things we currently look at when pairing up students and coaches.

**Comment by magdapoppins** [comment]
Picking this one up!

**Comment by despo** [comment]
Resolved by #1225
