### ISSUE TITLE
Ability to remove someone as attending

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#954]
## Description of the issue 📄
Right now if you check someone into the workshop by accident you can't uncheck them.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
[attended is a boolean](https://github.com/codebar/planner/blob/master/db/schema.rb#L122) so you should be using true or false, unfortunately, attended's uses true and nil states. 

When an invitation is created it's defaulted to nil and then [when a person actually gets to the meeting it gets set to true](https://github.com/codebar/planner/blob/master/app/controllers/admin/invitations_controller.rb#L27-L37). Now, if you want to stop someone being attended then you would have to set them back to nil.

```
                 Attended
      Member  -------------->   Member 
      attended: nil            attended: true
           ^      Unattended      |
           |------------------------

```

So, if someone wants to hack a fix they might want to try and set it to nil ... (Be my guest and claim the issue).

My first step would be to get it behaving like a boolean, True and False states, but I would want to know if this was really wanted before doing the work - it's going to involve a small migration change, see article, and chasing it through the system to see where it's used (which is mainly, fortunately, attended == true) but also maintainers time working with the production database.

If it goes right it will end up something like Invitation Management, which also has an attended attribute [but it defaulting to false not nil](https://github.com/codebar/planner/blob/master/db/schema.rb#L333).

### Further Reading
[avoid-the-threestate-boolean-problem
](https://thoughtbot.com/blog/avoid-the-threestate-boolean-problem
)
