### ISSUE TITLE
Add reCaptcha to donation page

### ISSUE THREAD

**Issue by despo** [codebar/planner#959]
## Description of the issue 📄

We've recently been experiencing spam requests submitted to our donation page, and we need to add a Captcha, to verify that the requests are issued from humans, before processing them.

Service to integrate: https://developers.google.com/recaptcha/docs/v3

Expectation: No requests are processed unless the returned score is above the accepted threshold.

The requests are currently processed via the [Donations](https://github.com/codebar/planner/blob/master/app/controllers/donations_controller.rb) controller.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by michiboo** [comment]
Hi! Can I try this issue?

**Comment by despo** [comment]
@michiboo of course! Let me know if you have any questions.

**Comment by despo** [comment]
No longer relevant
