### ISSUE TITLE
Add note about Google Search optimisation on new job page

### ISSUE THREAD

**Issue by despo** [codebar/planner#964]
## Description of the issue 📄

Add note on new job page, about sharing jobs with Google search when address information is filled in.

**Text to add:**
> The information below only required if you want this job post to be shared with Google Search UK.

We are also open to suggestions about how this text can be improved.

## Screenshots 📷
<img width="1231" alt="new-job" src="https://user-images.githubusercontent.com/159200/55354821-944b6800-54be-11e9-9d8f-e7cec5170f66.png">

## Steps to fix 🛠

1. Add text to locale file (there is already a members/job/new section)
https://github.com/codebar/planner/blob/master/config/locales/en.yml#L337

2. Refrence locale entry from view
https://github.com/codebar/planner/blob/master/app/views/member/jobs/_form.html.haml#L37
 
3. Verify with a test

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by klmansel** [comment]
I would like to claim this issue.

**Comment by KimberleyCook** [comment]
@klmansel yes please do :D

**Comment by klmansel** [comment]
Done :) PR submitted @KimberleyCook
