### ISSUE TITLE
This repository should be called "site".

### ISSUE THREAD

**Issue by SamirTalwar** [codebar/planner#99]
It's not a planner any more.

**Comment by docljn** [comment]
I'm just wondering if this is still an 'open' issue?

**Comment by despo** [comment]
@docljn I think we can close this. If we are ever at a more stable state and have time we can revisit but unlikely that this will happen anytime soon. 

@SamirTalwar seems like we are stuck with planner for now. Should have probably renamed this back in 2014 😄

**Comment by SamirTalwar** [comment]
I blame success for distracting you.
